### ISSUE TITLE
How to use CADDY_DOCKER_CADDYFILE_PATH?

### ISSUE THREAD

**Issue by wsw70** [lucaslorentz/caddy-docker-proxy#102]
https://github.com/lucaslorentz/caddy-docker-proxy/issues/93 mentions that 0.3.0 brings in `CADDY_DOCKER_CADDYFILE_PATH` allowing for a file-based `Caddyfile` to be added to the memory one.

I set up my service like that:

```
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    container_name: caddy
    ports:
      - 80:80
    volumes:
      - ./caddy/certs:/root/.caddy
    environment:
      - DOCKER_HOST=tcp://192.168.10.2:2375
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/docker/caddy/Caddyfile
    command: -email email@example.com -agree=true -log stdout
```

but when stating the container, the `Caddyfile` is not available:

```
root@srv /e/docker# ls /etc/docker/caddy/Caddyfile
/etc/docker/caddy/Caddyfile
root@srv /e/docker# docker-compose up caddy
Starting caddy ... done
Attaching to caddy
caddy            | 2019/05/06 03:39:11 [INFO] Docker polling interval: 30s
caddy            | 2019/05/06 03:39:11 [INFO] Caddy ContainerID: 2fdc9e0d87f18954551dd2ce7435fd2b69ed1911851e48f0d722e391c0961550
caddy            | 2019/05/06 03:39:11 [INFO] Caddy Networks: [e55022ac596cafd6908ee8c0a0e68d23efbcea95cbe810cd54727968500d618d]
caddy            | 2019/05/06 03:39:11 [INFO] Swarm is available: false
caddy            | 2019/05/06 03:39:11 [INFO][cache:0xc0002b20a0] Started certificate maintenance routine
caddy            | 2019/05/06 03:39:11 [INFO] New CaddyFile:
caddy            | # open /etc/docker/caddy/Caddyfile: no such file or directory
caddy            | # Skipping services because swarm is not available
caddy            | # Skipping configs because swarm is not available
caddy            | Activating privacy features... done.
caddy            | 2019/05/06 03:39:11 [INFO][cache:0xc0002b22d0] Started certificate maintenance routine
caddy            |
caddy            | Serving HTTP on port 2015
caddy            | http://:2015
caddy            |
caddy            | 2019/05/06 03:39:11 [INFO] Serving http://:2015
```

**Comment by wsw70** [comment]
I realized that the path is internal to the container. Changing the service description fixed the issue:

```
  caddy:
    image: lucaslorentz/caddy-docker-proxy
    container_name: caddy
    ports:
      - 80:80
    volumes:
      - ./caddy/certs:/root/.caddy
      - ./caddy/Caddyfile:/Caddyfile
    environment:
      - DOCKER_HOST=tcp://192.168.10.2:2375
      - CADDY_DOCKER_CADDYFILE_PATH=/Caddyfile
    command: -email email@example.com -agree=true -log stdout
```
