### ISSUE TITLE
How to generate a rewrite?

### ISSUE THREAD

**Issue by wsw70** [lucaslorentz/caddy-docker-proxy#103]
I tried to add a rewrite section to a container:

```
  whoami:
    image: containous/whoami
    container_name: whoami
    labels:
      caddy.address: http://whoami.local
      caddy.rewrite.if: "{remote} starts_with 127.0"
      caddy.rewrite.to: "/doesnotexisthere.txt"
```

This unfortunately generates a configuration without the rewrite:

```
 http://whoami.local {
   proxy / 172.20.0.9
 }
```

when I expected

```
 http://whoami.local {
   proxy / 172.20.0.9
   rewrite {
        if {remote} starts_with 127.0
        to /doesnotexisthere.txt
    }
 }
```

Is there something I am missing?
