### ISSUE TITLE
fastcgi proxy support request

### ISSUE THREAD

**Issue by renothing** [lucaslorentz/caddy-docker-proxy#108]
current I can only proxy http/https to containers.

is there any plan to support fastcgi ?

like this:
```
fastcgi / 127.0.0.1:9001 php {
	root /var/www/html
}
```
use `fastcgi` replace `proxy`

**Comment by pwFoo** [comment]
If that works it would be possible to have a backend container with just php instead of apache / nginx?

**Comment by unixfox** [comment]
You can already do that, you just didn't read completely the documentation: https://github.com/lucaslorentz/caddy-docker-proxy#labels-to-caddyfile-conversion

Here is an example:
````yml
labels:
      caddy.address=example.com
      caddy.fastcgi=/ 127.0.0.1:9000 php
````

**Comment by renothing** [comment]
> You can already do that, you just didn't read completely the documentation: https://github.com/lucaslorentz/caddy-docker-proxy#labels-to-caddyfile-conversion
> 
> You aren't just limited to proxy a container, check out my docker-compose I don't only use proxy but other plugins: [unixfox/docker-config/searx/docker-compose.yml](https://github.com/unixfox/docker-config/blob/master/searx/docker-compose.yml)
> 
> But if you need a simple example for fastcgi on caddy with docker-proxy here is:
> 
> ```yaml
> labels:
>       caddy.address=example.com
>       caddy.fastcgi=/ 127.0.0.1:9000 php
> ```

I read it before.
the problem is it will generate `proxy` automaticaly always.
```
  fastcgi / phpmyadmin:9000 php
  header / -Server
  proxy / 172.18.0.35
}
```
where 172.18.0.35 is the container ip

**Comment by unixfox** [comment]
Okay sorry I didn't think about that.
I tested it on my Docker swarm cluster and I can reproduce the same bug where there is the proxy directive generated even though no proxy configuration is set in the docker-compose file.

**Comment by unixfox** [comment]
@lucaslorentz Do you have plans to allow the ability to disable the proxy directive for the use of fastcgi instead?

--------------------
My temporary fix for this issue is to set the proxy directive to a random path like this:
````yml
labels:
      - 'caddy.address=example.com'
      - 'caddy.fastcgi=/ php:9000 php'
      - 'caddy.proxy=/random localhost:8080'
````

**Comment by lucaslorentz** [comment]
@unixfox 
If the label caddy.address is used, it will always generate a proxy.

But you don't need to use label caddy.address, you can control the host part setting values directly to caddy label. Example:
```
labels:
      - 'caddy=example.com'
      - 'caddy.fastcgi=/ php:9000 php'
```
Generates:
```
example.com {
    fastcgi / php:9000 php
}
```

**Comment by unixfox** [comment]
You are right! I didn't think about that.
I think you can close this issue then.

**Comment by ahoeg** [comment]
I tried with adminer php-fpm image. Works fine!
Had some problems with index file (tried without php preset, with index: index.php), but it works with php preset AND index adminer.php (instead of index.php index default).

compose
```
version: "3.7"
services:
  adminer:
    image: adminer:4.7.1-fastcgi
    networks:
      webproxy:
    labels:
      caddy: "adminer.it-dengler.de"
      caddy.fastcgi: "/ adminer:9000 php"
      caddy.fastcgi.index: "adminer.php"
      caddy.fastcgi.root: "/var/www/html"
      caddy.basicauth: "/ user1 pass1"
      caddy.log: '/ stdout "[{host}] {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size}"'
      caddy.errors: "stdout"
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 60s

# network of the proxy
networks:
  webproxy:
    external:
      name: proxy_webproxy
```
And add caching should be done with just one additional line I think.
```
      caddy.cache.path: "/tmp/caddy-cache/adminer"
```
