### ISSUE TITLE
Request IP addresses are all local

### ISSUE THREAD

**Issue by abdusco** [lucaslorentz/caddy-docker-proxy#109]
I've set up `caddy-docker-proxy` and it's proxying the requests quite fine. But, I noticed that the public IPs of requests are all point to the local IP of the caddy container (like 10.255.0.2), despite having set proxy config to transparent. I tried connecting caddy to host network, but docker swarm doesn't seem to support running services on host network. 

Here's a sample container config from my setup:
```yaml
version: '3'

services:
  server:
    image: gitea/gitea
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
    networks:
      - backend
    labels:
      caddy.address: sub.example.com
      caddy.targetport: 3000
      caddy.proxy.transparent: ""
      caddy.tls.dns: cloudflare
      caddy.tls.wildcard: ""
      caddy.log: stdout

networks:
  backend:
    external: true
```

Also the configuration for caddy:
```yaml
version: '3'

services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy
        command: -email my@email.com -agree=true -log stdout
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
            - "2015:2015"
        environment:
            - CADDY_DOCKER_CADDYFILE_PATH=/Caddyfile
            - CLOUDFLARE_EMAIL=my@email.com
            - CLOUDFLARE_API_KEY=xxxxxxxxxxxxxxxxxxxx
        volumes:
            - ./caddy/certs:/root/.caddy
            - ./caddy/Caddyfile:/Caddyfile
            - /www:/www
            - /mnt/glacier:/mnt/glacier
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /run/php/php7.2-fpm.sock:/run/php/php7.2-fpm.sock
        networks:
            - backend


networks:
    backend:
        external: true
```

How can I make sure that I get the real public IPs of requests, and not the ip of caddy container?

**Comment by unixfox** [comment]
Is the `backend` network an overlay network?

**Comment by abdusco** [comment]
Yes, `backend` is an overlay network.

```
NETWORK ID          NAME                DRIVER              SCOPE  
ojmc0r7gassr        backend             overlay             swarm  
90194d170608        bridge              bridge              local  
```

Local IP addresses appear in the caddy logs when I configure add a  `log` command either via a label for a container (`caddy.log: stdout`), or adding a site configuration manually in `Caddyfile`.

Here's a snippet of the request logs
```
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:49 +0000] "GET / HTTP/2.0" 200 39467                                                                              
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:49 +0000] "GET /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.css HTTP/2.0" 304 0                      
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:49 +0000] "GET /vendor/plugins/promise-polyfill/polyfill.min.js HTTP/2.0" 304 0                                   
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:49 +0000] "GET /vendor/plugins/moment/moment.min.js HTTP/2.0" 304 0                                               
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:49 +0000] "GET /vendor/plugins/vue-calendar-heatmap/vue-calendar-heatmap.browser.js HTTP/2.0" 304 0               
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:50 +0000] "GET /vendor/assets/lato-fonts/lato-italic.woff2 HTTP/2.0" 304 0                                        
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:50 +0000] "GET /vendor/assets/lato-fonts/lato-bold.woff2 HTTP/2.0" 304 0                                          
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:50 +0000] "GET /vendor/assets/lato-fonts/lato-regular.woff2 HTTP/2.0" 304 0                                       
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:50 +0000] "GET /img/favicon.png HTTP/2.0" 304 0                                                                   
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:50 +0000] "GET /api/v1/users/abdus/heatmap HTTP/2.0" 200 45                                                       
caddy_caddy.1.lfwumc5tgaib@alien    | 10.255.0.2 - - [14/Jun/2019:12:08:50 +0000] "GET /api/v1/repos/search?sort=updated&order=desc&uid=1&q=&limit=15&mode= HTTP/2.0" 200 8183            
```

**Comment by lucaslorentz** [comment]
@abdusco 

That ip you see is is the VIP of caddy swarm service.

To explain a bit the reason that happens:
- HTTP requests are received by any swarm host on your published port. Then those requests are forwarded to a swarm service VIP.
- The swarm service VIP is a level 3 load balancer, and it then forwards the request again to one of the caddy containers/replicas.

So, caddy container actually receives the request from the service VIP/load balancer.

To overcome that, we need to remove the service VIP/load balancer by deploying caddy on each host swarm host that might receive requests. We do that by using a swarm global distribution service instead of a replica service.

So, there are 2 ways to deploy caddy in swarm, using global distribution service or a replica service.

I suppose your swarm cluster has more than 1 host receiving requests, so, multiple caddy containers will be running. Because of that you will also need some volume plugin that supports sharing the same volume with multiple containers (I use `rexray/efs` on aws). Caddy will use automatically use lock files to orchestrate all caddy instances so they share certificate and don't issue them more than once.

That approach is the same approach Traefik describes in one of it's docs: https://docs.traefik.io/user-guide/cluster-docker-consul/

**Comment by lucaslorentz** [comment]
@abdusco 
This is the swarm file I use on production to support Request IP address.
```
version: '3.7'

services:
  docker-caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3.0-alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 2015
        published: 2015
        mode: host
    networks:
      - producao
    command: -email xxx@xxx.xxx -agree=true -log stdout -proxy-service-tasks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/root/.caddy
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 60s
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M

volumes:
  caddy:
    driver: rexray/efs

networks:
  producao:
    external: true
```
