### ISSUE TITLE
Problems with fastcgi settings

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#112]
Hi @lucaslorentz 
tried to "proxy" all requests via fastcgi to php-fpm backend. Security allows all extensions at php Backend, but caddy not forward the other requests (Images, js).

Maybe it could be a Caddy bug, because without preset php nothing works, also If I set ext, split and index manually! Index is ignored! Also with php preset...

Any chance you could test to proxy all requests via fastcgi to see if it proxy plugin or caddy related?

**Comment by pwFoo** [comment]
Tested configs... First one should work with all requests / file types? And should also proxy images and js files, right?!
```
    labels:
      caddy: "<DOMAIN>"
      caddy.fastcgi: "/ notify:9000"
      caddy.fastcgi.index: "index.php"
      caddy.fastcgi.split: ".php"
      caddy.fastcgi.root: "/www"
      caddy.log: '/ stdout "[{host}] {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size}"'
      caddy.errors: "stdout"
```

php only... but index.php isn't auto index file
```
    labels:
      caddy: "<DOMAIN>"
      caddy.fastcgi: "/ notify:9000 php"
      caddy.fastcgi.root: "/www"
      caddy.log: '/ stdout "[{host}] {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size}"'
      caddy.errors: "stdout"
```

php and index still ignored
```
    labels:
      caddy: "<DOMAIN>"
      caddy.fastcgi: "/ notify:9000 php"
      caddy.fastcgi.index: "index.php"
      caddy.fastcgi.root: "/www"
      caddy.log: '/ stdout "[{host}] {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size}"'
      caddy.errors: "stdout"
```

tried to proxy all requests by set ext to empty
```
    labels:
      caddy: "<DOMAIN>"
      caddy.fastcgi: "/ notify:9000 php"
      caddy.fastcgi.index: "index.php"
      caddy.fastcgi.ext: ""
      caddy.fastcgi.root: "/www"
      caddy.log: '/ stdout "[{host}] {remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size}"'
      caddy.errors: "stdout"
```

I know serve static files with php-fpm isn't a good idea, but it should work for testing I think?
And index shouldn't be ignored in all tests.
