### ISSUE TITLE
HTTP -> HTTPS Redirect and proxying to HTTP

### ISSUE THREAD

**Issue by Dreamwalker666** [lucaslorentz/caddy-docker-proxy#115]
I was looking on how to would run this as a normal web server proxying several back end services.  

I can see from config this is possible, except I am unsure how to configure to do port 80 -> 443 redirect and 443 -> xxx back end reverse proxy.  Any chance of an example compose for this?  I think it will be a common ask.

(Like where this is going btw!)

**Comment by lucaslorentz** [comment]
80 -> 443 redirect is done by Caddy when automatic HTTPS is used. More info at: https://caddyserver.com/docs/automatic-https

Reverse proxy 443 -> xxx can be done using proxy instructions: https://github.com/lucaslorentz/caddy-docker-proxy#automatic-proxy-generation

So, you can achieve what you want with only 2 labels:
```yml
        caddy.address: swarmpit.example.com
        caddy.targetport: 8080
```
Or 3 if you want caddy to use DNS challenge to issue SSL certificates:
```yml
        caddy.address: swarmpit.example.com
        caddy.targetport: 8080
        caddy.tls.dns: "route53"
```
I use route53 because my dns is hosted in AWS.

Here is a full example config I use to run swarmpit:
```yml
version: '3'

services:
  app:
    image: swarmpit/swarmpit:1.7
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - caddy
    deploy:
      labels:
        caddy.address: swarmpit.example.com.br
        caddy.targetport: 8080
        caddy.tls.dns: "route53"
        caddy.proxy.transparent: ""
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  db:
    image: klaemo/couchdb:2.0.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

networks:
  net:
    driver: overlay
  caddy:
    external: true

volumes:
  db-data:
    driver: rexray/ebs
    driver_opts:
      size: "2"
      volumeType: gp2
```

**Comment by lucaslorentz** [comment]
My caddy config:
```
version: '3.7'

services:
  docker-caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3.0-alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 2015
        published: 2015
        mode: host
    networks:
      - caddy
    command: -email youremail@example.com -agree=true -log stdout -proxy-service-tasks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/root/.caddy
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 60s
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M

volumes:
  caddy:
    driver: rexray/efs

networks:
  caddy:
    external: true
```
