### ISSUE TITLE
80 port as default for caddy

### ISSUE THREAD

**Issue by assada** [lucaslorentz/caddy-docker-proxy#121]
my docker-compose.yml
```yaml
version: '3.7'
services:
  caddy:
    restart: always
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    networks:
      - caddy
    command: -email myRealEmail@gmail.com -agree=true -log stdout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./app:/var/www
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - caddy
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - caddy
    labels:
      caddy.address: 3ds.test.guru
      caddy.targetport: "80"
      caddy.tls: "off"

networks:
  caddy:
    external:
      name: assada-services
```

3ds.test.guru:2015 - ok
3ds.test.guru:80/3ds.test.guru:443 - connection refused

```bash
$ docker network list
NETWORK ID          NAME                DRIVER              SCOPE
86f78644989f        assada-services     bridge              local
228e3f7d9fe9        bridge              bridge              local
```

How can I access 3ds.test.guru through port 80 or 443 using caddy. (TLS disabled for the test). Other services i will just assada-services network

**Comment by assada** [comment]
I am try add `-port 80` option in cmd for caddy. And now in stout:
```erlang
caddy_1    | 2019/08/21 18:27:02 [INFO] Caddy ContainerID: 59a8d03b87106afb4a21a32f1e7381fa89db938e962b671474b62dfd51ff8241
caddy_1    | 2019/08/21 18:27:02 [INFO] Caddy Networks: [fb135deb8a8fb760e9fc062e2fa903a0007204edbdb856e3eb174560bc68119a]
caddy_1    | 2019/08/21 18:27:02 [INFO] Swarm is available: false
caddy_1    | 2019/08/21 18:27:02 [INFO] New CaddyFile:
caddy_1    | # Skipping default CaddyFile because no path are set
caddy_1    | # Skipping services because swarm is not available
caddy_1    | # Skipping configs because swarm is not available
caddy_1    | Activating privacy features... done.
caddy_1    |
caddy_1    | Serving HTTP on port 80
caddy_1    | http://
caddy_1    |
caddy_1    | 2019/08/21 18:27:02 [INFO] Serving http://
caddy_1    | 2019/08/21 18:27:02 [INFO][cache:0xc00009a230] Started certificate maintenance routine
caddy_1    | 2019/08/21 18:27:02 [INFO][cache:0xc00009a370] Started certificate maintenance routine
caddy_1    | 2019/08/21 18:27:02 [INFO] New CaddyFile:
caddy_1    | # Skipping default CaddyFile because no path are set
caddy_1    | # Skipping services because swarm is not available
caddy_1    | # Skipping configs because swarm is not available
caddy_1    | 3ds.test.guru {
caddy_1    |   proxy / 172.21.0.4
caddy_1    |   tls myRealEmail@gmail.com
caddy_1    | }
caddy_1    | 2019/08/21 18:27:02 [INFO][cache:0xc00009a910] Started certificate maintenance routine
caddy_1    | 2019/08/21 18:27:02 [INFO] SIGUSR1: Reloading
caddy_1    | 2019/08/21 18:27:02 [INFO] Reloading
caddy_1    | 2019/08/21 18:27:02 [WARNING] TLS disabled for http://3ds.test.guru
caddy_1    | 2019/08/21 18:27:02 [INFO][cache:0xc00009a370] Stopped certificate maintenance routine
caddy_1    | 2019/08/21 18:27:02 [INFO] Reloading complete
caddy_1    | 2019/08/21 18:27:02 [INFO][cache:0xc00009ab40] Started certificate maintenance routine
```

**Comment by lucaslorentz** [comment]
Actually you should not add `-port 80`, because that blocks https on port 443. Your production configuration should work by just removing `-port 80`.

But then it will probably fail to issue a Let's Encrypt certificate because domain 3ds.test.guru doesn't point anywhere.

The problem is that caddy behavior is a bit confusing.

Here is the doc: https://caddyserver.com/docs/tls
> Disables TLS for the site. Not recommended unless you have a good reason. With TLS off, automatic HTTPS is also disabled, so the default port (2015) will not be changed.

When you add `caddy.tls: "off"`. It will serve by default on port 2015. Then you need to specify that you want it on port http:
```
caddy.address: http://3ds.test.guru
caddy.targetport: "80"
caddy.tls: "off"
```

This will serve on port 80 and 443:
```
caddy.address: 3ds.test.guru
caddy.targetport: "80"
caddy.tls: "anything except off"
```
Or
```
caddy.address: http://3ds.test.guru https://3ds.test.guru
caddy.targetport: "80"
caddy.tls: "<anything except off>"
```

So, to avoid changing address in your test environment, you can use self signed certificates:
```
caddy.address: 3ds.test.guru
caddy.targetport: "80"
caddy.tls: "self_signed"
```

**Comment by lucaslorentz** [comment]
I hope I was able to clarify a bit. Let me know if you have other issues.

**Comment by assada** [comment]
Thanks. 3ds.test.guru - fake domain. 
Now it works! 
my final `docker-compose.yml`
```
version: '3.7'
services:
  caddy:
    restart: always
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    networks:
      - caddy
    command: -email myRealEmail@gmail.com -agree=true -log stdout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/root/.caddy
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./app:/var/www
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - caddy
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - caddy
    labels:
      caddy.address: "https://3ds.test.guru"
      caddy.tls: "myRealEmail@gmail.com"
volumes:
  caddy:
    driver: local
networks:
  caddy:
    external:
      name: assada-services
```

http -> https redirect works fine.

**Comment by assada** [comment]
But i have new trouble...

I am create new service by running this docker-compose.yml:

```
version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      - caddy
    labels:
      caddy.address: "https://mock.guru"
      caddy.tls: "myRealDomain@gmail.com"

networks:
  caddy:
    external:
      name: assada-services
```

https://mock.guru - ok

if I update 3ds.test.guru then ALWAYS get to 3ds.test.guru service as expected

but if I update mock.guru I get to 3ds.test.guru or to mock.guru randomly. Both services works fine. Caddy seems to work as a load balancer between mock.guru and 3ds.test.guru. Although it should work as a proxy for two services on the same network
