### ISSUE TITLE
tcp DOCKER_HOST issue

### ISSUE THREAD

**Issue by mxrlkn** [lucaslorentz/caddy-docker-proxy#124]
I'm trying to use https://github.com/Tecnativa/docker-socket-proxy to proxy the docker socket.

Initially it seems to work fine for days but sometimes it starts to print out `<nil>` many times a second:

```
2019/09/12 13:49:19 <nil>
2019/09/12 13:49:19 <nil>
2019/09/12 13:49:19 <nil>
2019/09/12 13:49:19 <nil>
2019/09/12 13:49:19 <nil>
2019/09/12 13:49:19 <nil>
2019/09/12 13:49:19 <nil>
2019/09/12 13:49:19 <nil>
2019/09/12 13:49:19 <nil>
```

CPU usage goes up, but caddy is still working and proxying services.

Restarting the caddy container doesn't fix it. removing the container and starting a new one does.

I have 1 cluster that's been live for a month without the issue and another that's been live for 2 weeks that started to print out `<nil>`. Same config.

```yml
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci
    command: -email=test@example.com -agree=true -disable-tls-alpn-challenge -log stdout
    networks:
      - default
      - socket
    volumes:
      - caddy:/root/.caddy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      DOCKER_API_VERSION: 1.37
      DOCKER_HOST: tcp://socket:2375
      CADDY_DOCKER_PROCESS_CADDYFILE: "true"

  socket:
    image: tecnativa/docker-socket-proxy
    networks:
      - socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      SERVICES: 1
      NETWORKS: 1
      CONFIGS: 1
      TASKS: 1
      NODES: 1
      INFO: 1
```

I'm unsure if I need to open more endpoints on tecnativa/docker-socket-proxy.
