### ISSUE TITLE
caddy docker proxy on a worker node

### ISSUE THREAD

**Issue by unixfox** [lucaslorentz/caddy-docker-proxy#126]
I'm trying to deploy caddy-docker-proxy on a worker node in my Docker Swarm setup with the help of `Tecnativa/docker-socket-proxy` given in this issue: https://github.com/lucaslorentz/caddy-docker-proxy/issues/20#issuecomment-512026901.

Here is my docker-compose.yml configuration:
````yml
version: '3.7'
services:
    caddy:
        command: '-agree=true -log stdout'
        mode: global
        deploy:
            restart_policy:
                condition: any
        image: 'lucaslorentz/caddy-docker-proxy:ci-alpine'
        environment:
            - DOCKER_API_VERSION=1.37
            - DOCKER_HOST=tcp://socket:2375
        networks:
            - global
            - socket
        ports:
            -
                mode: host
                protocol: tcp
                published: 80
                target: 80
            -
                mode: host
                protocol: tcp
                published: 8080
                target: 8080
            -
                mode: host
                protocol: tcp
                published: 443
                target: 443
        volumes:
            - '/data/caddy:/root/.caddy'
            - '/var/log/caddy:/var/log'
            - '/etc/localtime:/etc/localtime:ro'
    socket:
        image: tecnativa/docker-socket-proxy
        networks:
            - socket
        deploy:
            labels:
                - com.ouroboros.enable=true
            placement:
                constraints:
                    - 'node.role == manager'
            restart_policy:
                condition: any
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            CONTAINERS: 1
            SERVICES: 1
            NETWORKS: 1
            CONFIGS: 1
            TASKS: 1
            NODES: 1
            INFO: 1
    whoami0:
        image: jwilder/whoami
        networks:
           - global
        deploy:
           labels:
               caddy.address: whoami0.example.com
               caddy.targetport: "8000"
               caddy.tls: "off"
networks:
    socket:
        external: true
    global:
        external: true
````

When deploying the service on the worker node I get these errors at the start of caddy-docker-proxy:
````
2019/10/26 15:16:13 [INFO] Caddy ContainerID: 98e50def5a5ce5f26d9cc3a5e0658a3a5bfa39ae64c58ae6290389588eda066b
2019/10/26 15:16:13 [ERROR] Error: No such container: 98e50def5a5ce5f26d9cc3a5e0658a3a5bfa39ae64c58ae6290389588eda066b
[INFO] Skipping default CaddyFile because no path is set
[ERROR] Service 3ghymgdf4czv4sx0wq2monktc and caddy are not in same network
[ERROR] Service cbwxh44dyehjqqd2ypce8sohf and caddy are not in same network
[ERROR] Service fh910455vskkjknov7dabrp3k and caddy are not in same network
[ERROR] Service lefawk1xy44fe8bypxlz23cyq and caddy are not in same network
[ERROR] Service vke9f37r9b7hwowr03l51tyl7 and caddy are not in same network
````

Caddy is then unable to generate automatically the Caddyfile configuration from the labels defined in my docker-compose.yml.

Is there a way to bypass the errors like `are not in same network` and `No such container` to have Caddy working on a worker node?
On traefik it's working great to launch traefik on a worker node with the help of `docker-socket-proxy`: https://github.com/containous/traefik/issues/766#issuecomment-291116582 so why it wouldn't be possible on `caddy-docker-proxy` too?
