### ISSUE TITLE
[Docker Swarm] Replicas are not served with round-robin

### ISSUE THREAD

**Issue by cmizzi** [lucaslorentz/caddy-docker-proxy#129]
Hi !

I'm currently testing this plugin in place of `traefik`. But, when I replicate a service using Docker Swarm, it seems `caddy` isn't resolving each replicated containers. I expected to see a default round-robin between each replicated containers.

```yaml
version  : "3.4"
services :
    consul:
        image    : consul:latest
        command  : agent -server -bootstrap-expect=1
        networks :
            - consul
            - caddy
        volumes  :
            - "consul-data:/consul/data"
        deploy   :
            mode: replicated
            replicas: 1
        environment :
            - CONSUL_LOCAL_CONFIG={"datacenter":"us_east2","server":true}
            - CONSUL_BIND_INTERFACE=eth0
            - CONSUL_CLIENT_INTERFACE=eth0

    docker-proxy:
        image: rancher/socat-docker
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            mode: replicated
            replicas: 1

    caddy:
        image    : <redacted>
        command  : -email <redacted> -agree=true -log stdout -proxy-service-tasks=true -docker-validate-network=false
        networks :
            - routable
            - caddy
            - consul
        ports    :
            - target    : 80
              published : 80
              mode      : host
            - target    : 443
              published : 443
              mode      : host
        deploy:
            mode          : global
            update_config :
                parallelism    : 10
                delay          : 10s
            restart_policy :
                condition : on-failure
        environment :
            - DOCKER_HOST=tcp://docker-proxy:2375
            - CONSUL_HTTP_ADDR=consul:8500

    whoami:
        image    : jwilder/whoami
        networks :
            - routable
        deploy:
            labels:
                caddy.address      : http://example.test
                caddy.targetport   : "8000"
                caddy.proxy.policy : round_robin

volumes :
    consul-data:

networks:
    routable:
        driver: overlay

    consul:
        driver: overlay

    caddy:
        driver: overlay
```

```go
package main

import (
	"github.com/caddyserver/caddy/caddy/caddymain"

	// List of plugins
	_ "github.com/caddyserver/dnsproviders/ovh"
	_ "github.com/lucaslorentz/caddy-docker-proxy/plugin"
	_ "github.com/pteich/caddy-tlsconsul"
)

func main() {
	caddymain.Run()
}
```

## How to reproduce this issue ?

```
docker swarm init
docker stack --compose-file docker-compose.yml caddy
docker service update --replicas=2 caddy_whoami
```
