### ISSUE TITLE
Real IP address

### ISSUE THREAD

**Issue by Misotech** [lucaslorentz/caddy-docker-proxy#135]
Hi!

How can I see the real IP address of the user in the docker container?

Now all proxied connections have IP = locahost. I need to filter connections by IP in the container that Caddy is proxying to.

**Comment by lucaslorentz** [comment]
Hey,

I will split that into 2 parts:
- Caddy must receive the client IP address
- Your application must receive from caddy the 

Usually, client IP is lost right after it enters docker, because there is a swarm service load balancing incoming connections to all caddy instances. To fix that, we need to remove that load balancer service, and that's done by changing caddy to run as global deploying and directly bind to node ports.

Example:
```
  docker-caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3.6-alpine
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    networks:
      - your-network
    command: -email your-email -agree=true -log stdout -proxy-service-tasks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/root/.caddy
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 60s
      resources:
        reservations:
          cpus: '0.1'
          memory: 200M
```

The code above runs Caddy on every manager node, binding it to ports 80 and 443. Then you must configure manager ips in your DNS, because requests will only work if sent to manager nodes.

The second part, is that your application need to get the client ip as well. In order to do that, you need to configure Caddy proxy to be transparent, that means it will forward headers with informations about the client connection: x-real-ip, x-forwarded-for, x-forwarded-proto....
More information at: https://caddyserver.com/v1/docs/proxy

You can enable transparent with the following label in your caddy service/container:
```
caddy.proxy.transparent = ""
```

Then, your application just needs to take x-forwarded-for header into account, that header will contain the real client ip address.
