### ISSUE TITLE
Option to load a Caddyfile on the Server before it receives the initial config request

### ISSUE THREAD

**Issue by rgdev** [lucaslorentz/caddy-docker-proxy#156]
Is it possible de load a default Caddyfile when in Server mode to initialize a minimum configuration before the Controller sends its generated configuration ? 

Right now i'm trying to make docker-proxy & a [third party storage provider](https://github.com/pteich/caddy-tlsconsul) work together on Swarm to build a proper distributed reverse-proxy but no luck so far.

My guess is that since the storage configuration is pushed after Caddy has already started it gets confused and doesn't switch to the new storage provider (maybe @mholt can shed some light on this point). I end up with a bunch of Caddy (server mode) instances trying to renew Let's encrypt certificates at the same time until they hit the rate limits (no big deal it's a test env).

Tested with Caddy 2.1-beta.1, docker-proxy 2.1.0 & tlsconsul 1.2.0.

Here's the Docker Swarm stack I used to test : 

```
version: '3.7'

services:
  caddy_server:
    image: XXXXXX/caddy:2.1.0-beta.1
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy_controller
      - webgateway
      - consul
    environment:
      - CADDY_DOCKER_MODE=server
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
    deploy:
      replicas: 1
      labels:
        caddy_controlled_server:

  caddy_controller:
    image: XXXXXX/caddy:2.1.0-beta.1
    networks:
      - caddy_controller
      - webgateway
    environment:
      - CADDY_DOCKER_MODE=controller
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
      - CADDY_DOCKER_PROCESS_CADDYFILE=true
      - CADDY_DOCKER_POLLING_INTERVAL=5s
    configs:
      - source: caddyfile-default
        target: /etc/caddy/Caddyfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - caddy.email=contact@XXXXXX.com
        - caddy.storage=consul
        - caddy.storage.address=consul-server:8500
        - caddy.storage.prefix=caddytls
        - caddy.storage.aes_key=XXXXXXXXXXXXXXXXXX
        - caddy.storage.tls_enabled=false
        - caddy.storage.tls_insecure=true
      placement:
        constraints:
          - node.role == manager

configs:
  caddyfile-default:
    external: true

networks:
  webgateway:
    external: true
  consul:
    external: true
  caddy_controller:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "10.200.200.0/24"
```

And here's my minimal Caddyfile I pass to the Controller : 

```
{
	email contact@XXXXXX.com
	storage consul {
		address consul-server:8500
		aes_key XXXXXXXXXXXXXXXXXX
		prefix caddytls
		tls_enabled false
		tls_insecure true
	}
}
```

I tried both with only Caddyfile & only labels as well but the result is the same as the controller properly merges everything together anyway :)
