### ISSUE TITLE
Controller will generate empty entries for containers it doesn't share a network with

### ISSUE THREAD

**Issue by rgdev** [lucaslorentz/caddy-docker-proxy#157]
If the controller don't share a Docker Network with the upstream containers / services that needs to be exposed through Caddy it prints a warning but still generates a block with no IPs causing 502s : 

```
caddytest.xxxxxxxx.xxx {
	reverse_proxy
}
```

For the sake of network isolation I'd rather not have the controller reachable from containers that don't absolutely requires it.

A way to make this possible could be to add a label on the upstream service (let's say caddy.network=my_net) and have caddy-docker-proxy resolve the container(s) IP(s) explicitly on this network. I believe that is how Traefik handles it internally.

This would allow this kind of network topology where the Caddy Controller is completely isolated from anything but the Caddy Servers : 

(simplified stack for readability)
```
services:
  caddy_server:
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy_controller
      - caddy
    environment:
      - CADDY_DOCKER_MODE=server

  caddy_controller:
    networks:
      - caddy_controller
    environment:
      - CADDY_DOCKER_MODE=controller

  my_app:
    networks:
      - caddy
    deploy:
      labels:
      - caddy=myapp.domain.tld
      - caddy.network=caddy
      - caddy.reverse_proxy="{{upstreams 8000}}"
```

**Comment by lucaslorentz** [comment]
Can you please try setting environment CADDY_DOCKER_VALIDATE_NETWORK=false in caddy-controller?

By default we do network validation, maybe we should change that default for controllers.

**Comment by lucaslorentz** [comment]
Well, that doesn't fully solve your problem. Because if containers are in more than one network the wrong IP might be used.

I liked `caddy.network=my_net` idea, but I think we can define it only once in controller, instead of setting it on each service.

**Comment by rgdev** [comment]
@lucaslorentz Adding CADDY_DOCKER_VALIDATE_NETWORK indeed solves the empty block issues but as you mentioned it ends up adding all the IPs attached to the container no matter if they are reachable by the Caddy Servers.

Defining the network label on the controller could be good for convenience in case you have a single network to bridge your Caddy Servers and all your exposed services however it would prevent adding more layers of network isolation. It might not be ideal to have many services all seeing each other on one network. I've seen clusters where each service had its own network and the front proxy was connected to each of those networks to keep things fully isolated.

How about this : We can set the label on the controller and it acts as a global setting for all containers but if a container has its own network label it overrides the global setting for this particular container/service ? We end up with the best of both worlds : the convenience of not having to define it everywhere while keeping the flexibility of fine-grained configuration where needed.

**Comment by lucaslorentz** [comment]
I didn't fully get the use case of having a different ingress network per container.

Do you want to do something like this?

```
services:
  caddy_server:
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy_controller
      - ingress_app_1
      - ingress_app_2
    environment:
      - CADDY_DOCKER_MODE=server

  caddy_controller:
    networks:
      - caddy_controller
    environment:
      - CADDY_DOCKER_MODE=controller

  app_1:
    networks:
      - ingress_app_1
    deploy:
      labels:
      - caddy=app1.domain.tld
      - caddy.network=ingress_app_1
      - caddy.reverse_proxy="{{upstreams 8000}}"

  app_2:
    networks:
      - ingress_app_2
    deploy:
      labels:
      - caddy=app2.domain.tld
      - caddy.network=ingress_app_2
      - caddy.reverse_proxy="{{upstreams 8000}}"
```

And what's the reason? To make sure App1 cannot communicate with App2?
