### ISSUE TITLE
Problem with port number

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#16]
Modified example yml for usage with docker-compose without swarm and get the following error message.
```
ERROR: for whoami0  Cannot create container for service whoami0: json: cannot unmarshal number into Go value of type string

ERROR: for whoami1  Cannot create container for service whoami1: json: cannot unmarshal number into Go value of type string
```

yml
```
version: '2'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 2015:2015
    command: -email email@example.com -agree=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami0:
    image: jwilder/whoami
    labels:
      caddy.address: whoami0.example.com
      caddy.targetport: 8000
      caddy.tls: "off"

  whoami1:
    image: jwilder/whoami
    labels:
      caddy.address: whoami1.example.com
      caddy.targetport: 8000
      caddy.tls: "off"
```

To fix it change port number to a string `caddy.targetport: "8000"` instead of `caddy.targetport: 8000`.
Is there a way to convert / work around the issue plugin / go side?
