### ISSUE TITLE
Using django (root, except)

### ISSUE THREAD

**Issue by Adanteh** [lucaslorentz/caddy-docker-proxy#163]
Not entirely sure how to use something like this so maybe I'm going about it entirely wrong, but normally for a django caddyfile to serve static files you use something like

```
sub.example.com {
  tls {$TLS_EMAIL}
  root /var/www/django
  proxy / web:8000 {
    except /static /media
    transparent
  }
}
```
so I'm using this in my docker-compose.yml
```
            caddy: sub.example.com
            caddy.root: "/var/www/django"
            caddy.proxy: "/ {{upstreams 8000}}"
            caddy.proxy.except: "/static /media"
            caddy.proxy.transparent: 
```
but without any luck. Instead i get the follow message in the container log:
```
2020-07-09T21:26:35.626802022Z [ERROR]  Removing invalid block: Caddyfile:5: unrecognized directive: proxy
2020-07-09T21:26:35.626807512Z sub.domain.com {
2020-07-09T21:26:35.626811700Z  proxy / 192.168.160.4:8000 {
2020-07-09T21:26:35.626816229Z          except /static /media
2020-07-09T21:26:35.626820136Z          transparent
2020-07-09T21:26:35.626823853Z  }
2020-07-09T21:26:35.626827470Z  root /var/www/django
2020-07-09T21:26:35.626836667Z }
```

Is there any way i could use settings like this as labels?

**Comment by francislavoie** [comment]
The Caddyfile is for Caddy v1, the latest version of caddy-docker-proxy only supports Caddy v2.

Caddy v2 is a complete rewrite, so the syntax is different. Please look at the upgrade guide: https://caddyserver.com/docs/v2-upgrade

**Comment by Adanteh** [comment]
Thanks, that fixed it (Well.... after I made sure my caddy service actually has access to the same volume).

```
            caddy: sub@example.com
            caddy.tls: "tls@example.com"
            caddy.root: "* /var/www/django"
            caddy.@notstatic: 
            caddy.@notstatic.not: path /static/* /media/*
            caddy.reverse_proxy: "@notstatic {{upstreams 8000}}"
            caddy.file_server:
```
are the labels i got in my docker-compose for my docker service, in case anyone stumbles on something similar while googling

**Comment by francislavoie** [comment]
You meant `sub.example.com` right? Not `sub@example.com`

**Comment by Adanteh** [comment]
Yeah, also updated the original post with proper example.com example. Maybe something for a readme could also be on how to run it from separate files sharing networks. There's probably other solutions but I use:

django/docker-compose.yml
```
....
        networks:
            - caddy_net
networks: 
    caddy_net:
        external:
            name: caddy_proxy
```

caddy/docker-compose.yml
```
...
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/src/caddy:/data
            - /var/www/django:/var/www/django
        restart: always
        
networks:
    caddy:
        name: caddy_proxy
```
