### ISSUE TITLE
Questions on a standalone config

### ISSUE THREAD

**Issue by happysalada** [lucaslorentz/caddy-docker-proxy#165]
Thanks for a great repo! I have a couple of questions on a standalone installation of caddy with docker swarm.

What should the base Caddyfile contain?
- it contains config.example.com, with a respond Hello world. Is it safe to assume it can be skipped? (it seems everything can be safely generated) What is unclear to me is that all of the tls are labeled as "internal", should there be some that are not to generate the external facing ssl certificate? I tried adding a new domain name with no pre-existing ssl certificate, when trying to access, I get an ssl error. When verifying inside the caddy docker image, I have a file at the corresponding domain
/data/caddy/certificates/local/union.blackstonefutures.co.za

Let me know if this is not the right place to post this

Here is the url in question
https://union.blackstonefutures.co.za/

And here is the relevant docker label part

```
      labels:
        caddy: www.$DOMAIN_NAME union.blackstonefutures.co.za
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "internal"
```

the normal domain is `www.forunion.com/` and works fine, however the new domain does not.
