### ISSUE TITLE
multiline directives seems not to work

### ISSUE THREAD

**Issue by torwag** [lucaslorentz/caddy-docker-proxy#168]
Using caddy2 by utilizing docker 
```caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: caddy
    restart: unless-stopped
    command: docker-proxy  -caddyfile-path=/config/Caddyfile
    networks:
      proxy:
    ports:
      - "80:80"
      - "443:443"
    environment:
      - MY_DOMAIN=$MYDOMAIN
    volumes:
      - caddy_data/:/data
      - caddy_config/:/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - caddy.email=$MYMAIL
```
I tried to get most caddy configuration in the individual docker-compose files. For nextcloud I should add some header information. I tried (note the two differnt way to add escape a quote by using escape and double quotes and single escape quotes :
```
    labels:
      caddy: nc.MYDOMAIN nextcloud.MYDOMAIN
      caddy.header: "/"
      caddy.header.Strict-Transport-Security: "\"max-age=15552000;\""
      caddy.header.Referrer-Policy: "strict-origin-when-cross-origin"
      caddy.header.X-XSS-Protection: \"1; mode=block\"
      caddy.header.X-Content-Type-Options: "nosniff"
      caddy.header.X-Frame-Options: "SAMEORIGIN"
      caddy.reverse_proxy: "{{upstreams 80}}"
```
Actually I tried many forms with and without quotes, with escaped quotes, etc. But nothing seems to work correctly.
I always checked in the caddy logs, how it was parsed.
E.g. the above example was interpreted as
```
nc.MYDOMAIN nextcloud.MYDOMAIN {
       header / {
                 Referrer-Policy strict-origin-when-cross-origin
                 Strict-Transport-Security "\"max-age=15552000;\""
                 X-Content-Type-Options nosniff
                 X-Frame-Options SAMEORIGIN
                 X-XSS-Protection "\"1;" "mode=block\""
             }
}
```
As you can see, there are those funny double quotes now, were I expect that one quote should be gone, like in the single quote cases.

However, not escaping those quotes, they are removed completely:
```
header / {
     Referrer-Policy strict-origin-when-cross-origin
     Strict-Transport-Security max-age=15552000;
     X-Content-Type-Options nosniff
     X-Frame-Options SAMEORIGIN
     X-XSS-Protection 1; mode=block
}
```
Thus, I am a bit puzzled how to get a single set of quotes

**Comment by francislavoie** [comment]
Out of curiosity, where did you get that config example? It's incorrect, there should not be a `/` as a path matcher, that will only make it apply for requests to `/` and not `/foo` as Caddy v2 path mathcing is exact-match. I keep seeing people use that config but I don't know where they're getting it from.

Since Caddy v2.1, you can use backticks as well as double quotes for strings. That means you can do this (also remove the `/` matcher by setting an empty argument):

```
    labels:
      caddy: nc.MYDOMAIN nextcloud.MYDOMAIN
      caddy.header: ""
      caddy.header.Strict-Transport-Security: "`max-age=15552000;`"
      caddy.header.Referrer-Policy: "strict-origin-when-cross-origin"
      caddy.header.X-XSS-Protection: "`1; mode=block`"
      caddy.header.X-Content-Type-Options: "nosniff"
      caddy.header.X-Frame-Options: "SAMEORIGIN"
      caddy.reverse_proxy: "{{upstreams 80}}"
```
