### ISSUE TITLE
How to have HTTP only?

### ISSUE THREAD

**Issue by xy2z** [lucaslorentz/caddy-docker-proxy#172]
How do I set the "auto_https: off" but only for 1 site, while keeping others https active?

Let's say I have 2 apps
- app01 (https enabled)
- app02 (only http)

Is this possible with this? I've tried a different things, without luck.
Here's my docker-compose.yml file for app02:
```yml
version: '3'

services:
  web:
    image: caddy:2.1.1-alpine
    volumes:
      - ./index.html:/usr/share/caddy/index.html
    labels:
      caddy: "app02.domain.tld" # i have also tried with "app02.domain.tld:80"
      caddy.auto_https: "off" # doesnt help
      caddy.reverse_proxy: "{{upstreams http 80}}"
    networks:
      - caddydp

networks:
  caddydp:
    external: true
```

The error I get from the proxy is just:
```
caddy-proxy | 2020/07/29 13:04:21 http: TLS handshake error from 10.26.69.251:57481: no certificate available for 'app02.domain.tld'
```
and still redirects me from http to https (and yes i have cleared cache)

So is there a way to disable https/tls per site?

**Comment by francislavoie** [comment]
I think you should just be able to use `http://app02.domain.tld` as your server label. See https://caddyserver.com/docs/caddyfile/concepts#addresses

**Comment by xy2z** [comment]
It got it to work using:

```yaml
    labels:
      caddy: "http://app02.domain.tld" # also works with 'caddy: "app02.domain.tld:80"'
      caddy.reverse_proxy: "{{upstreams http 80}}"
```

Actually it just seems that the `auto_https` was the problem.
It doesn't work with `caddy.auto_https: "off"` even when it's the first label, like you posted. I get this error:

```
caddy-proxy | [ERROR]  Removing invalid block: Caddyfile:2: unrecognized directive: auto_https
caddy-proxy | http://app02.domain.tld {
caddy-proxy |   auto_https off
caddy-proxy |   reverse_proxy http://172.17.20.3:80
caddy-proxy | }
```

and the site doesn't work..

Nevertheless, it works now. Thanks!

**Comment by francislavoie** [comment]
Oh, I think you might need to put a suffix to clearly separate one block from the other, like this:

```
    labels:
      caddy_0.auto_https: "off"
      caddy_1: "http://app02.domain.tld"
      caddy_1.reverse_proxy: "{{upstreams http 80}}"
```

But yeah, you don't need `auto_https` at all, I'm more talking generally about the label syntax here.

**Comment by xy2z** [comment]
Juste tested it, and it does not give an error, but it makes all sites http only, so I think it's better not to use it ever - and just stick to using "http://domain.tld" or "domain.tld:80" (for http) - and "domain.tld" for https.

I'm brand new to caddy, and just realised `auto_https: off` is not required when the domain is set accordingly 👍

**Comment by francislavoie** [comment]
Yeah the purpose of `auto_https off` is for users who want to configure HTTPS manually using the `tls` directive, etc.

**Comment by xy2z** [comment]
I'm still not sure that is needed in that case, because my app01 has `tls: internal` and I haven't set `auto_https: off` anywhere.
But I might be wrong.

This is my app01 labels:
```
    labels:
      caddy: app01.domain.tld
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 80}}"
```

Notice it doesn't have `auto_https off` set anywhere, neither in the proxy or any of the other apps.
This is the proxy log:
```
caddy-proxy | 2020/07/30 07:25:32 [INFO] New Caddyfile:
caddy-proxy | app01.domain.tld {
caddy-proxy |   reverse_proxy 172.17.20.4:80
caddy-proxy |   tls internal
caddy-proxy | }
caddy-proxy | http://app02.domain.tld {
caddy-proxy |   reverse_proxy http://172.17.20.3:80
caddy-proxy | }
```
