### ISSUE TITLE
Clarifying usage outside of a docker container (upstreams and ports)

### ISSUE THREAD

**Issue by jotterbot** [lucaslorentz/caddy-docker-proxy#173]
Hi there Lucas! 

Wondering if you can clarify some usage given my use case...

**My use case:**

Suppose i wanted to run multiple containers locally to develop my codebase via `docker-compose.yml` (different projects at the same time), it seems to me I can't run **caddy-docker-proxy** in any one `docker-compose.yml` file due to port conflicts (and local trusted cert generation issues - with different cert authorities inside the containers). 

_Instead_, I was looking to run **caddy-docker-proxy** _natively_ to take advantage of local certs, and still take advantage of the `{{upstreams}}` functionality (dynamically routing to the correct containers for a given hostname). 

**The issue:**

Running caddy natively (on macOS), given a label like this in any of my `docker-compose.yml` files:

```
<snip>
    web:
        build: ./
        environment:
          - APP_ENV=dev
        ports:
            - 80
        labels:
            caddy: test.jotterbot.tld
            caddy.reverse_proxy: "{{upstreams}}"
            caddy.tls: "internal"
<snip>
```

Every time i run `~/go/bin/caddy docker-proxy`, I'll get a partial caddyfile generated with no upstream for the reverse proxy, and the following error message in the logs:

```
[WARNING] Container <id> and caddy are not in same network
```

I can get around this if I replace the `caddy.reverse_proxy: "{{upstreams}}"` line for something hardcoded like `caddy.reverse_proxy: "http://localhost:8080"` but then I'd have to manually keep track of ports across my various yaml files.

**Possible fix?:**

Is it possible to get templated _port_ assignments for a container?  Eg. accessing this info in `docker inspect` : `NetworkSettings.Ports.<theport>.HostPort` ?  So you could end up writing something like this:

`caddy.reverse_proxy: "{{http://127.0.0.1:upstream_port}}"` (or similar?)

If not, can you recommend a solution or strategy for this use case?

Appreciate your work! Thanks for reading 😄
