### ISSUE TITLE
Reverse proxy directive merge behavior

### ISSUE THREAD

**Issue by matthew-banning** [lucaslorentz/caddy-docker-proxy#193]
Currently when using the `reverse_proxy` directive from multiple services for the same site, the two directives will be merged into one even when prefixed with a number to specify their order. For example:

```yaml
version: '3.7'
services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    whoami1:
        image: containous/whoami
        networks:
            - caddy
        environment:
            WHOAMI_NAME: 1
        deploy:
            labels:
                caddy: whoami.local
                caddy.1_reverse_proxy: "{{upstreams 80}}"
                caddy.tls: internal
    
    whoami2:
        image: containous/whoami
        networks:
            - caddy
        environment:
            WHOAMI_NAME: 2
        deploy:
            labels:
                caddy: whoami.local
                caddy.2_reverse_proxy: "{{upstreams 80}}"
                caddy.tls: internal

networks:
    caddy:
        driver: overlay

volumes:
    caddy_data: {}
```
Generated output:
```
whoami.local {
    reverse_proxy 10.0.12.3:80 10.0.12.6:80
    tls internal
}
```

The desired output would be:
```
whoami.local {
    reverse_proxy 10.0.12.3:80 
    reverse_proxy 10.0.12.6:80
    tls internal
}
```
The purpose of this would be so that the `whoami1` service would be the default backend for the reverse proxy with the `whoami2` service never being hit under normal circumstances. If the `whoami1` service was stopped, the caddyfile would be regenerated to:
```
whoami.local {
    reverse_proxy 10.0.12.6:80
    tls internal
}
```
This would allow the `whoami2` service to be used as a kind of failover.

I imagine this would be able to be achieved by changing the merge behavior for the `reverse_proxy` directive to take into consideration the specified order of the directives instead of currently merging with the first `reverse_proxy` directive that is found.

It would be interesting to get some other thoughts on this. Thanks

**Comment by francislavoie** [comment]
Instead, you should use `lb_policy first` for this: https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing

I don't think it makes sense to have two `reverse_proxy` directives when one will always hide the other.

**Comment by matthew-banning** [comment]
I did consider using the `lb_policy first`, however for a replicated `whoami1` service `CADDY_DOCKER_PROXY_SERVICE_TASKS` would have to be set to false, letting the swarm handle the load balancing. This would be sufficient but limits the use of other load balancing policies offered by Caddy. I am also unclear on whether the `whoami1` service would reliably come before the `whoami2` service in the list of upstreams for `reverse_proxy`.

> I don't think it makes sense to have two reverse_proxy directives when one will always hide the other.

I agree that for a static configuration it wouldn't make sense to have two `reverse_proxy` directives, but in this dynamic configuration one directive will **not** always hide the other.

Take for example this configuration:
```yaml
version: '3.7'
services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    whoami1:
        image: containous/whoami
        networks:
            - caddy
        environment:
            WHOAMI_NAME: 1
        deploy:
            labels:
                caddy: whoami.local
                caddy.1_reverse_proxy: "{{upstreams 80}}"
                caddy.2_reverse_proxy: "{{upstreams 81}}"
                caddy.tls: internal

networks:
    caddy:
        driver: overlay

volumes:
    caddy_data: {}
```
Which produces this configuration:
```
whoami.local {
    reverse_proxy 10.0.17.6:80
    reverse_proxy 10.0.17.6:81
    tls internal
}
```

The use of the order prefix in this example isolates the two directives, which while this service is running I agree makes entirely no sense. However, for two separate services this type of caddyfile configuration would be desirable as I have shown. Why should the order prefix work for directives within the same service but not between services?

**Comment by matthew-banning** [comment]
For now, the following could be used as a workaround to achieve the desired functionality as `handle` will be processed before `reverse_proxy`:
```yaml
version: '3.7'
services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    whoami1:
        image: containous/whoami
        networks:
            - caddy
        environment:
            WHOAMI_NAME: 1
        deploy:
            labels:
                caddy: whoami.local
                caddy.handle.reverse_proxy: "{{upstreams 80}}"
                caddy.tls: internal
    
    whoami2:
        image: containous/whoami
        networks:
            - caddy
        environment:
            WHOAMI_NAME: 2
        deploy:
            labels:
                caddy: whoami.local
                caddy.reverse_proxy: "{{upstreams 80}}"
                caddy.tls: internal

networks:
    caddy:
        driver: overlay

volumes:
    caddy_data: {}
```
Generated output:
```
whoami.local {
    handle {
        reverse_proxy 10.0.18.3:80
    }
    reverse_proxy 10.0.18.6:80
    tls internal
}
```

I suppose this issue of achieving directive isolation between services would apply to the suffix and prefix functionality in general rather than for just `reverse_proxy`.
