### ISSUE TITLE
Can the image be used in a not swarm environment?

### ISSUE THREAD

**Issue by maxiride** [lucaslorentz/caddy-docker-proxy#204]
I'd like to use the automatic reverse proxy provided by this image, however, since my home setup is very small I am not running a swarm.

I've tried to `docker-compose up -d` the below compose file (a stripped version of the standalone one) but I received the error that my instance isn't a swarm. Is this a caddy-docker-proxy limitation?

compose file:
```yml
version: "3.7"

services:
  caddy2:
    image: lucaslorentz/caddy-docker-proxy:2.3-alpine
    container_name: caddy2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    driver: overlay
```

error:
```
 This node is not a swarm manager. Use "docker swarm init" or "docker swarm join"
 to connect this node to swarm and try again.
```

**Comment by lucaslorentz** [comment]
A working docker-compose example:
```yaml
version: "3.7"

services:
  caddy2:
    image: lucaslorentz/caddy-docker-proxy:2.3-alpine
    container_name: caddy2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy

  whoami0:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: whoami0.example.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.tls: "internal"

  whoami1:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: whoami1.example.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.tls: "internal"

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    driver: bridge
```
Then:
```
docker-compose
```

Test:
```
curl -k --resolve whoami0.example.com:443:127.0.0.1 https://whoami0.example.com
curl -k --resolve whoami1.example.com:443:127.0.0.1 https://whoami1.example.com
```
