### ISSUE TITLE
Proxy domain.com and domain.com/path with different reverse proxy directives from different stacks?

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#208]
Hi @lucaslorentz,

I have two stacks. The first one use the domain (for example `domain.com`) and the second one just a path of the domain `domain.com` like:
```
domain.com/.well-known/matrix/
```

I tried to use the hole domain with path to create a sub reverse proxy (`https://domain.com/.well-known/matrix/`) and also tried a @match with just a "duplicate" of `domain.com`, but that fails because of duplicate server definition...

Is it possible to leave the definition of `domain.com` unchanged and work with a second server definition only listen to domain + path and have a higher priority than domain.com?

**Comment by francislavoie** [comment]
It might work if you add `*` at the end of the URL you use as your site address - path matching is exact, so you need a wildcard character to match the rest.

Alternatively, I guess you could put the site block's labels on the Caddy container with both of those combined with `handle_path` or whatever.

**Comment by lucaslorentz** [comment]
@pwFoo 

Having different matchers already guarantees reverse proxies it will not be merged. This should work for you:
```
  whoami0:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: example.com
        caddy.reverse_proxy: "* {{upstreams 8000}}"
        caddy.tls: "internal"

  whoami1:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: example.com
        caddy.reverse_proxy: "/folder {{upstreams 8000}}"
        caddy.tls: "internal"
```

Generates caddyfile:
```
example.com {
	reverse_proxy * 10.0.3.6:8000
	reverse_proxy /folder 10.0.3.8:8000
	tls internal
}
```

If you need more complex matchers, you can do something like:
```
  whoami0:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: example.com
        caddy.@matcher1.path: "*"
        caddy.reverse_proxy: "@matcher1 {{upstreams 8000}}"
        caddy.tls: "internal"

  whoami1:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: example.com
        caddy.@matcher2.path: "/folder/*"
        caddy.reverse_proxy: "@matcher2 {{upstreams 8000}}"
        caddy.tls: "internal"
```
Generates:
```
example.com {
	@matcher1 {
		path *
	}
	@matcher2 {
		path /folder/*
	}
	reverse_proxy @matcher1 10.0.3.6:8000
	reverse_proxy @matcher2 10.0.3.8:8000
	tls internal
}
```

If the order is affecting you, you can play a bit with #_ on your directives.
```
  whoami0:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: example.com
        caddy.2_@matcher1.path: "*"
        caddy.3_reverse_proxy: "@matcher1 {{upstreams 8000}}"
        caddy.tls: "internal"

  whoami1:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: example.com
        caddy.1_@matcher2.path: "/folder/*"
        caddy.2_reverse_proxy: "@matcher2 {{upstreams 8000}}"
        caddy.tls: "internal"
```

Generates:
```
example.com {
	@matcher2 {
		path /folder/*
	}
	@matcher1 {
		path *
	}
	reverse_proxy @matcher2 10.0.3.8:8000
	reverse_proxy @matcher1 10.0.3.6:8000
	tls internal
}
```

**Comment by lucaslorentz** [comment]
Based on the unchanged requirement, I believe this is what you want:
```
  whoami0:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: example.com
        caddy.reverse_proxy: "{{upstreams 8000}}"
        caddy.tls: "internal"

  whoami1:
    image: jwilder/whoami
    networks:
      - caddy
    deploy:
      labels:
        caddy: example.com
        caddy.1_reverse_proxy: "/folder/* {{upstreams 8000}}"
        caddy.tls: "internal"
```
And it generates:
```
example.com {
	reverse_proxy /folder/* 10.0.3.8:8000
	reverse_proxy 10.0.3.6:8000
	tls internal
}
```

**Comment by pwFoo** [comment]
Maybe one of my problems was reverse proxy directive order! 
"any" reverse proxy was first, second was subpath reverse proxy... Maybe the subpath never worked because of the position after the "any else" reverse proxy?

**Comment by pwFoo** [comment]
Order in labels was correct, but generated order was wrong!
Maybe related to #209? One matcher and one for all others, but the reverse proxy directive was reverse ordered in generated caddyfile?

**Comment by lucaslorentz** [comment]
Can you share the labels you're using? The fix on that PR is not required for your use case.

**Comment by pwFoo** [comment]
Labels changed during testing, so I can't share the exact labels...
I think it was similiar to:
```
caddy_0.@match1.path: "/_matrix/* /_synapse/client/*"
caddy_0.reverse_proxy: "@match1 {{upstreams 8008}}"
caddy_1.reverse_proxy: "{{upstreams 8448}}"
```

Result in caddyfile was 
```
        @match1 {
                path /_matrix/* /_synapse/client/*
        reverse_proxy 10.0.0.130:8448
        reverse_proxy @match1 10.0.0.130:8008
```

Shouldn't the reverse_proxy lines in changed order...?

**Comment by francislavoie** [comment]
The order of the reverse_proxy lines doesn't matter because the Caddyfile adapter itself will sort them after the fact.

**Comment by pwFoo** [comment]
Ok, thanks. I solved another problem with my setup and it works now.

But I moved off topic with the matchers. 

Is it right that caddy v1 could handle servers like `domain.com` and `domain.com/path/to/file` as different virtual hosts? I Is that still possible with caddy v2? I remember about a change with such overlapping virtual hosts...?

**Comment by lucaslorentz** [comment]
@pwFoo, sorry, I'm a bit lost.
Did you get it working with any of the examples posted above?
If not, caddy internal ordering is likely to be the problem as @francislavoie  mentioned.
You can force caddy to process directives in the order you want by using a [route directive](https://caddyserver.com/docs/caddyfile/directives/route). 

Try changing your example to:
```yaml
# Defines the matcher
caddy_0.@match1.path: "/_matrix/* /_synapse/client/*"
# Add 2 ordered reverse proxies inside a route, so they will be executed in the specified order
caddy_0.route.1_reverse_proxy: "@match1 {{upstreams 8008}}"
caddy_1.route.2_reverse_proxy: "{{upstreams 8448}}"
```

It should render something like:
```
@match1 {
        path /_matrix/* /_synapse/client/*
}
route {
  reverse_proxy @match1 10.0.0.130:8008
  reverse_proxy 10.0.0.130:8448
}
```
