### ISSUE TITLE
Add loadbalancing to backends / replicas

### ISSUE THREAD

**Issue by pwFoo** [lucaslorentz/caddy-docker-proxy#21]
Hi @lucaslorentz ,

traffic won't loadbalanced between backends / replicas at the moment.
Instead of add the backend to an existing caddyfile entry it generates a second one.
```
http://192.168.199.22/httpd1 {
  proxy / 10.0.2.5:80
}
http://192.168.199.22/httpd1 {
  proxy / 10.0.2.6:80
}
```

It should be balanced to the backend containers:
```
http://192.168.199.22/httpd1 {
  proxy / 10.0.2.5:80 10.0.2.6:80
}
```

**Comment by pwFoo** [comment]
Additional question... Works the plugin with multi node / host swarm setups or just single / locale host?

**Comment by pwFoo** [comment]
Hi @lucaslorentz,
any plans to implement load balancing by container ip addresses?

**Comment by jcmeier** [comment]
Hi! 
I am also quite interested in having this. Since it would make it possible to scale up the backend containers and adding it to load balancing in caddy on the fly.

**Comment by lucaslorentz** [comment]
Hey @jcmeier 
We already supports multiple backend containers with scale up and down. You just need to add labels to a swarm service.
Caddy will then proxy to swarm service VIP, and swarm service will load balance to all containers.

This issue is to add the same capabilities without swarm services.

**Comment by jcmeier** [comment]
Thanks for clearing this up @lucaslorentz!

**Comment by jtyr** [comment]
I have put together a hacky [solution](https://github.com/jtyr/caddy-docker-proxy/tree/container_lb) for loadbalancing containers in a service. It only works if the labels are defined on the service level:

```yaml
version: "3"
services:
  frontend:
    image: mycaddy
    ports:
      - 443:443
  backend:
    image: mycaddy
    labels:
      caddy.address: https://example.com
      caddy.targetport: 80
      caddy.proxy.keepalive: 0
    deploy:
      replicas: 2
```

It would be more difficult to make it working if labels are defined under the `deploy` section. It would require to search for nodes where service tasks are running and then search for containers on those nodes which have swarm label with the service name (am I right @lucaslorentz?). Please test it and let me know whether it works for you and if yes, I will create a PR for this feature.
