### ISSUE TITLE
Question: building docker image of caddy with docker-proxy and other plugins

### ISSUE THREAD

**Issue by xNok** [lucaslorentz/caddy-docker-proxy#210]
Hi, I am trying to build a custom image with docker-proxy and auth-portal. My test works perfectly fine if I use `lucaslorentz/caddy-docker-proxy:ci-alpine` however if I build a custom image and replace caddy binary caddy seems to work by my labels are not discovered. Therefore the other container is not well configured in caddy.

I am really having a hard time figuring out what's going wrong. So I a looking for some advice.

Dockerfile
```
ARG CADDY_VERSION=2.3.0

# Builder Image
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 \
    --with github.com/greenpau/caddy-auth-portal \
    --with github.com/greenpau/caddy-auth-jwt \
    --with github.com/greenpau/caddy-trace \
    --output /usr/bin/caddy

# Final Image
FROM lucaslorentz/caddy-docker-proxy:ci-alpine

# Replace the binary
COPY --from=builder /usr/bin/caddy /bin
```

docker-compose
```
version: "3.7"

# used for specific settings you have outside of your docker config
# ex: proxies to external servers, storage configuration...
# remove this block entirely if not needed (Only used for Docker Swarm)
configs:
  caddy-basic-content:
    file: ./Caddyfile
    labels:
      caddy:

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    image: xnok/caddy-docker-auth-portal   #doen't work
    # image: lucaslorentz/caddy-docker-proxy:ci-alpine #works
    ports:
      - 80:80
      - 443:443
    networks:
      - docker_swarm_private
      - docker_swarm_public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # this volume is needed to keep the certificates
      # otherwise, new ones will be re-issued upon restart
      - caddy_data:/data
    deploy:
      labels: # Global options
        caddy.email: contact@nokwebspace.ovh
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    networks:
      - docker_swarm_private
    deploy:
      labels:
        caddy: whoami.dev.nokwebspace.ovh   #loopback domaine
        caddy.reverse_proxy: "{{upstreams 80}}"
        caddy.tls: "internal"

networks:
  docker_swarm_public:
    external: true
  docker_swarm_private:
    external: true

volumes:
  caddy_data: {}
```
