### ISSUE TITLE
Unable to work directly with PHP-FPM fastcgi (Laravel)

### ISSUE THREAD

**Issue by accesstechnology-mike** [lucaslorentz/caddy-docker-proxy#215]
These labels seems to produce the correct Caddyfile, but doesn't launch the site (error 404)

```
    labels:
      caddy: fpm.server.co.uk
      caddy.root: "* /var/www/public"
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.encode: gzip
      caddy.file_server:
```

Removing the `file_server` directive shows a black white screen, so I presume it is connecting to the fastcgi server ok

Going via Ngnix launches the site fine, but I'd rather not have the extra container if Caddy can run it directly.

**Comment by francislavoie** [comment]
What's your entire docker-compose file? What are the logs for the Caddy container?

**Comment by accesstechnology-mike** [comment]
docker-compose.yml

`#version: '3.7'
services:

  fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm
    container_name: php-fpm
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - caddy
    labels:
      caddy: fpm.serverco.uk
      caddy.root: "* /var/www/public"
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.encode: gzip
      caddy.file_server:
#Docker Networks
networks:
  caddy:
    external: true
`
Dockerfile
`
FROM php:fpm

# Copy composer.lock and composer.json
COPY composer.lock composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    libzip-dev \
    libonig-dev \
    curl

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl gd

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Add user for laravel application
RUN groupadd -g 1000 www-data
RUN useradd -u 1000 -ms /bin/bash -g www-data www-data

# Copy existing application directory contents
COPY . /var/www

# Copy existing application directory permissions
COPY --chown=www-data:www-data . /var/www

# Change current user to www
USER www-data

# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]

`

Where do I find the logs on this container please?

**Comment by francislavoie** [comment]
I don't see your caddy container in the docker-compose config you posted.

**Comment by accesstechnology-mike** [comment]
caddy docker-compose:
```

version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true
volumes:
  caddy_data: {}
```

log

```
caddy_1  | 2021/02/07 01:07:26 [INFO] Skipping default Caddyfile because no path is set
caddy_1  | [INFO] Skipping configs because swarm is not available
caddy_1  | [INFO] Skipping services because swarm is not available
caddy_1  | 2021/02/07 01:07:26 [INFO] New Caddyfile:
caddy_1  | fpm.server.co.uk {
caddy_1  |      encode gzip
caddy_1  |      file_server
caddy_1  |      php_fastcgi 192.168.64.6:9000 {
caddy_1  |              root /var/www/public
caddy_1  |      }
caddy_1  |      root * /var/www
caddy_1  | }
caddy_1  | nginx-php.server.co.uk {
caddy_1  |      reverse_proxy 192.168.64.4:80
caddy_1  | }
caddy_1  | whoami8.server.co.uk {
caddy_1  |      reverse_proxy 192.168.64.3:8000
caddy_1  | }
caddy_1  | 2021/02/07 01:07:26 [INFO] New Config JSON:
caddy_1  | {"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[{"match":[{"host":["nginx-php.server.co.uk"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"192.168.64.4:80"}]}]}]}],"terminal":true},{"match":[{"host":["whoami8.server.co.uk"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"reverse_proxy","upstreams":[{"dial":"192.168.64.3:8000"}]}]}]}],"terminal":true},{"match":[{"host":["fpm.server.co.uk"]}],"handle":[{"handler":"subroute","routes":[{"handle":[{"handler":"vars","root":"/var/www"},{"encodings":{"gzip":{}},"handler":"encode"}]},{"handle":[{"handler":"static_response","headers":{"Location":["{http.request.uri.path}/"]},"status_code":308}],"match":[{"file":{"try_files":["{http.request.uri.path}/index.php"]},"not":[{"path":["*/"]}]}]},{"handle":[{"handler":"rewrite","uri":"{http.matchers.file.relative}"}],"match":[{"file":{"split_path":[".php"],"try_files":["{http.request.uri.path}","{http.request.uri.path}/index.php","index.php"]}}]},{"handle":[{"handler":"reverse_proxy","transport":{"protocol":"fastcgi","root":"/var/www/public","split_path":[".php"]},"upstreams":[{"dial":"192.168.64.6:9000"}]}],"match":[{"path":["*.php"]}]},{"handle":[{"handler":"file_server","hide":["./Caddyfile"]}]}]}],"terminal":true}]}}}}}
caddy_1  | 2021/02/07 01:07:26 [INFO] Sending configuration to localhost
caddy_1  | {"level":"info","ts":1612660046.205698,"logger":"admin.api","msg":"received request","method":"POST","host":"localhost:2019","uri":"/load","remote_addr":"127.0.0.1:46396","headers":{"Accept-Encoding":["gzip"],"Content-Length":["1388"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}
caddy_1  | {"level":"info","ts":1612660046.206503,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
caddy_1  | {"level":"info","ts":1612660046.206947,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00084ac40"}
caddy_1  | {"level":"info","ts":1612660046.2071714,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
caddy_1  | {"level":"info","ts":1612660046.207456,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
caddy_1  | {"level":"info","ts":1612660046.2081554,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["fpm.server.co.uk","nginx-php.server.co.uk","whoami8.server.co.uk"]}
caddy_1  | {"level":"info","ts":1612660046.210735,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc0002b9f80"}
caddy_1  | {"level":"info","ts":1612660046.2114964,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
caddy_1  | {"level":"info","ts":1612660046.2116244,"logger":"admin.api","msg":"load complete"}
caddy_1  | 2021/02/07 01:07:26 [INFO] Successfully configured localhost
caddy_1  | {"level":"info","ts":1612660046.706951,"logger":"admin","msg":"stopped previous server"}

```

**Comment by francislavoie** [comment]
So your issue is that you don't have a volume mounting the files into the Caddy container. Caddy needs to be able to see the files to serve them or tell `php-fpm` about them.

**Comment by accesstechnology-mike** [comment]
> So your issue is that you don't have a volume mounting the files into the Caddy container. Caddy needs to be able to see the files to serve them or tell `php-fpm` about them.

Ok that makes sense - I'll look at sharing volumes between containers. Thanks.

Just seem this on the link I shared earlier:

```
      # php-fpm roots
      - ../volumes/nextcloud/html:/php-fpm-root/nextcloud
```

**Comment by accesstechnology-mike** [comment]
Thanks for your help with this. I managed to create a single caddy docker-compose.yml that can see all my current and future sites by including:

```
    volumes:
    ...
      - /home/user/CODE:/CODE <-- links ALL apps on HOST (~/CODE/app1/ ~/CODE/app2/ etc.) to /CODE/ on Caddy container
```

and my php-fpm app docker-compose.yml now looks like this:
```
    labels:
      caddy: fpm.server.co.uk      
      caddy.file_server:
      caddy.root: "* /CODE/app1/public" <-- references location for this app on Caddy container (linked to HOST above), so Caddy can serve static files, without the need for a separate Nginx container!
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.php_fastcgi.root: /var/www/public <-- references location on php:fpm container, so fpm can serve PHP files 
      caddy.encode: gzip
```

For reference, 'public 'is a Laravel subdirectory, other apps may not need that location.

**Comment by RikudouSage** [comment]
In case anyone's interested, if you want to use caddy as  a reverse proxy for php fpm without mounting the volume to caddy as well:

```
    labels:
      caddy: example.com
      caddy.root: '* /var/www/html/public'
      caddy.rewrite: index.php
      caddy.reverse_proxy: "{{ upstreams 9000 }}"
      caddy.reverse_proxy.transport: fastcgi
      caddy.reverse_proxy.transport.split: .php
      caddy.reverse_proxy.transport.capture_stderr:
```

**Comment by MuzafferDede** [comment]
Thanks for the info! Today, I was able to come up with this solution. If you're interested in setting up a Caddy reverse proxy for a Dockerized application (in this case, Laravel) with a shared volume, here's a simple guide to help you:

### 1. Create a Shared Docker Volume
First, create a Docker volume that will be shared between Caddy and your apps:
```bash
docker volume create apps_volume
```

### 2. Configure the App's Docker Compose
In your app's `docker-compose.yml`, mount the shared volume and add Caddy-specific labels for automatic routing, SSL configuration, and PHP-FPM:

```yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWUSER: '${WWWUSER}'
        WWWGROUP: '${WWWGROUP}'
    image: image_name
    container_name: app_name
    working_dir: /var/www/html
    labels:
      caddy: example.com
      caddy.tls: email@exmaple.com
      caddy.file_server:
      caddy.root: '* /apps/app_name/public' # <-- Note that we are targeting the apps_volume mount point inside the Caddy container
      caddy.php_fastcgi: "{{ upstreams 9000 }}"
      caddy.php_fastcgi.root: /var/www/html/public
      caddy.encode: gzip

    volumes:
      - apps_volume/app_name:/var/www/html # <-- Mount the apps_volume at /var/www/html inside the app container
    networks:
      - caddy
    expose:
      - 9000
    restart: unless-stopped 
    environment:
      WWWUSER: '${WWWUSER}'
      WWWGROUP: '${WWWGROUP}'

networks:
  caddy:
    external: true

volumes:
  apps_volume:
    external: true
```

### 3. Configure Caddy's Docker Compose
In Caddy's docker-compose.yml, mount the shared volume and use the Docker socket to auto-discover your app's containers:

```yml
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy_server
    restart: unless-stopped
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - apps_volume:/apps # <-- Mount the shared volume
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    ports:
      - "80:80"
      - "443:443"
      
    networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
  apps_volume:
    external: true # <-- Volume is external so set it to 'true'
```

### 4. Start the Containers
Run `docker compose up` in both the app and Caddy directories to start the containers.
---
 
With this setup, you can easily route traffic to your Dockerized app using Caddy, with automatic SSL and shared file access.
