### ISSUE TITLE
Best practice - reverse proxying to HOST environment

### ISSUE THREAD

**Issue by accesstechnology-mike** [lucaslorentz/caddy-docker-proxy#216]
Hello, I'm not sure how to approach this.

I have my vscode app running directly on the host @ host-ip:8080. I would like to reverse proxy `dev.example.com` to this.

I use caddy-docker-proxy to successfully proxy my containers, but I'm not sure how to connect to my host environment.

I launch caddy-docker-proxy using this docker-compose.yml. I presume I would modify this file somehow? and maybe include a Caddyfile?

Thanks, Mike 

```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - /home/mike/CODE:/home/mike/CODE
    restart: unless-stopped

networks:
  caddy:
    external: true
volumes:
  caddy_data: {}
```
