### ISSUE TITLE
Firefox can't open this page: when opening files from one container to the other

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#223]
I use FileRun, a faster/lighter alternative to NextCloud. It's exposed to the web via caddy-docker-proxy at files.mydomain.com. 
In addition I run OnlyOffice-DocumentServer, exposed to office.mydomain.com. 
Both subdomains work with https, so I am already very happy (switched from traefikv2). 

The only issue is: when I am on files.mydomain.com and open a file, Firefox gives an error: `Firefox can't open this page: To protect your security, office.obelix.cloud will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window.` 

When I click on the  "Open in new window" button, I am directed to office.mydomain.com but no file opens, its just showing the Onlyoffice loading animation forever and there is nothing in OnlyOffice logs! It seems no document file has ever reached OnlyOffice. 

I used Traefikv2, and it did work (with A LOT of extra labels for OnlyOffice. 

This is my docker-compose.yml for caddy, onlyoffice, filerun: 
```
##____________________ FileRun [CLOUD/Files]
  filerun:
    image: afian/filerun
    container_name: filerun
    restart: always
    networks: 
      - caddy
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      (lots of db vars)
    depends_on:
      - mariadb
    links:
      - mariadb
      - filerun-tika
      - filerun-elasticsearch
    ports:
      - "8008:80"
    volumes:
      (some vol mounts)
    labels:
    labels:
      caddy: files.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: $EMAIL
      caddy.file_server: ""
      caddy.encode: gzip
##____________________ OnlyOffice [CLOUD/Office]
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    depends_on:
      #- onlyoffice-postgresql
      - onlyoffice-rabbitmq
    stdin_open: true
    restart: always
    networks: 
      - caddy
    tty: true
    ports:
      - "8889:80"
    volumes:
      (lots of vol mounts)
    dns: 1.1.1.1
    environment:
      - JWT_ENABLED="true"
      - JWT_SECRET=$ONLYOFFICEJWT
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
    labels:
      caddy: office.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: $EMAIL
      caddy.file_server: ""
      caddy.encode: gzip
      caddy.header.Strict-Transport-Security: '"max-age=31536000;"'
      caddy.header.X-XSS-Protection: '"1; mode=block;"'
      caddy.header.X-Content-Type-Options: "nosniff"
      caddy.header.X-Frame-Options: "SAMEORIGIN"
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    networks: 
      - caddy
    expose:
      - '5672'
```

I noticed in Caddy Community some extra variables are sometimes used, so I tried adding these 2 labels to Onlyoffice: `caddy.tls_insecure_skip_verify: ""` and `caddy.header: /` but it fails over the first one and the 2nd one doesn't help either. I also found `transparent` but I understand that one doesn't exist anymore for Caddyv2. 

With Traefikv2, I used these labels and everything worked: I could open files from FileRun into OnlyOffice. Firefox does not interrupt.  Filerun Traefikv2 labels:  
```
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.filerun-redirect.redirectscheme.scheme=https
      - traefik.http.routers.filerun-redirect.entrypoints=web
      - traefik.http.routers.filerun-redirect.middlewares=filerun-redirect
      - traefik.http.routers.filerun-redirect.rule=Host(`files.$DOMAIN`)
      - traefik.http.routers.filerun.entrypoints=websecure
      - traefik.http.routers.filerun.rule=Host(`files.$DOMAIN`)
      - traefik.http.routers.filerun.tls.certresolver=letsencrypt
      - traefik.http.services.filerun.loadbalancer.server.port=80
```
OnlyOffice Traefikv2 labels, don't ask me what it all does, I just know it works this way: 
```
      - traefik.enable=true
      - traefik.http.middlewares.office-redirect.redirectscheme.scheme=https
      - traefik.http.routers.office-redirect.entrypoints=web
      - traefik.http.routers.office-redirect.rule=Host(`office.$DOMAIN`)
      - traefik.http.routers.office.middlewares=office-redirect
      - traefik.http.routers.office-secure.entrypoints=websecure
      - traefik.http.routers.office-secure.rule=Host(`office.$DOMAIN`)
      - traefik.http.routers.office.tls.certresolver=letsencrypt
      - traefik.http.services.office.loadbalancer.server.port=80
      ## Extra headers required for onlyoffice
      - traefik.http.routers.office-secure.tls=true
      - traefik.http.routers.office-secure.middlewares=secure-headers
      - traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowOrigin=*
      - traefik.http.routers.office.middlewares=secure-headers,cors-headers
```

Is there a way to figure out the equivalent labels for Caddyv2 to get this to work?
I really want to stop using Traefik because for the only other 2 services exposed to the web, like Syncthin and Firefox-syncserver, it just looks like this, soo much simpler than Traefik: 
```
    labels:
      caddy: sync.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 8384}}"
      caddy.tls: $EMAIL
```

**Comment by zilexa** [comment]
Somehow, I got it working! This is my docker-compose now: 

```
##_____________________ Caddy [CLOUD/web-proxy]
  caddy:
    container_name: caddy-proxy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: always
    networks: 
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # this volume is needed to keep the certificates
      # otherwise, new ones will be re-issued upon restart
      - $USERDIR/docker/caddy/caddy_data:/data
      - $USERDIR/docker/caddy/config:/config
    ports:
      - 80:80
      - 443:443
##____________________ FileRun [CLOUD/Files]
  filerun:
    image: afian/filerun
    container_name: filerun
    restart: always
    networks: 
      - caddy
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      FR_DB_HOST: mariadb
      FR_DB_PORT: 3306
      FR_DB_NAME: filerundb
      FR_DB_USER: $USER
      FR_DB_PASS: $PW_INT
      APACHE_RUN_USER: $USER
      APACHE_RUN_USER_ID: $PUID
      APACHE_RUN_GROUP: $USER
      APACHE_RUN_GROUP_ID: $PGID
    depends_on:
      - mariadb
    links:
      - mariadb
      - filerun-tika
      - filerun-elasticsearch
    volumes:
      - $USERDIR/docker/filerun/html:/var/www/html
      - /mnt/pool/Users:/user-files:rw
      - /mnt/pool/Users/Local/Asterix:/user-files/Local/$USER1/Asterix:rw
      - /mnt/pool/Users/Local/Asterix:/user-files/Local/$USER2/Asterix:rw
    labels:
      caddy: files.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: $EMAIL
      caddy.file_server: ""
      caddy.encode: gzip
      #caddy.header: /
      caddy.header.Strict-Transport-Security: '"max-age=31536000;"'
      caddy.header.X-XSS-Protection: '"1; mode=block;"'
      caddy.header.X-Content-Type-Options: "nosniff"
      caddy.header.X-Frame-Options: "SAMEORIGIN"
#
#3 more containers for FileRun: mariadb, tikaserver & elasticseach.
#
##____________________ FileRun [CLOUD/Office]
  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    stdin_open: true
    restart: always
    networks: 
      - caddy
    tty: true
    volumes:
      - $USERDIR/docker/onlyoffice/data:/var/www/onlyoffice/Data
      - $USERDIR/docker/onlyoffice/log:/var/log/onlyoffice
      - $USERDIR/docker/onlyoffice/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
      - $USERDIR/docker/onlyoffice/example:/var/www/onlyoffice/documentserver-example/public/files
      - $USERDIR/docker/onlyoffice/fonts:/usr/share/fonts
    dns: 1.1.1.1
    environment:
      - JWT_ENABLED="true"
      - JWT_SECRET=$ONLYOFFICEJWT
    labels:
      caddy: office.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: $EMAIL
      caddy.file_server: ""
      caddy.encode: gzip
      #caddy.tls_insecure_skip_verify: ""
      #caddy.header: /
```

I even removed the portforwarding of Onlyoffice and Filerun since that doesn't make sense, it's exposed via Caddy already.
