### ISSUE TITLE
Bitwarden_rs requires 3 additional proxies

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#224]
Bitwarden_rs (lightweight alternative to the Bitwarden official server edition of the password manager) provides good documentation on how to run via Docker with CaddyV2. But since it seems non-standard I am unsure how to map it to caddy-docker proxy. 

The documentation: 
https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples 
I am following the second section (443) of the CaddyV2 example, because the 1st example is if Caddy runs behind another (Synology) proxy. 

In my case: Ubuntu server behind a common router with ports 443/80 forwarded (for Caddy). 

I got this far:
```
bitwarden:
  image: bitwardenrs/server:latest
  container_name: bitwarden
  restart: always
  networks: 
    - caddy
  volumes:
    - $USERDIR/docker/bitwarden:/data
    labels:
      caddy: bitwarden.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: $EMAIL
      caddy.encode: gzip
      caddy.header.X-XSS-Protection: '"1; mode=block;"'
      caddy.header.X-Frame-Options: "DENY"
      caddy.header.X-Content-Type-Options: "none"
```
The part that I miss from the documentation because I do not understand how to convert this to docker: 
>`# Server name removing
>       -Server
>   }
>'# The negotiation endpoint is also proxied to Rocket
>  reverse_proxy /notifications/hub/negotiate <SERVER>:80
>
>'# Notifications redirected to the websockets server
>  reverse_proxy /notifications/hub <SERVER>:3012
>
>'# Proxy the Root directory to Rocket
>  reverse_proxy <SERVER>:80 {
>       '# Send the true remote IP to Rocket, so that bitwarden_rs can put this in the
>       '# log, so that fail2ban can ban the correct IP.
>       header_up X-Real-IP {remote_host}

**Comment by francislavoie** [comment]
If you use a `_#` suffix on directives, you can have more than one of the same:

```
caddy.reverse_proxy_0: "{{upstreams 80}}"
caddy.reverse_proxy_1: "/notifications/hub {{upstreams 3012}}"
```

**Comment by zilexa** [comment]
Sorry I am really a noob, I went through the readme but didn't understand most of it, I do CTRL+F search for variables, then see you actually neatly explain how the arguments work in an abstract matter, I guess otherwise you would be rewriting the entire documentation, so that makes sense, but I am a bit in over my head also with the Caddy documentation. 

I am super grateful for you help. I got it working now, just a small question left:
```
##_____________________ Bitwarden [CLOUD/Password-manager] 
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: always
    networks: 
      - caddy
    volumes:
      - $USERDIR/docker/bitwarden:/data
    labels:
      caddy: pw.$DOMAIN
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.header.up: "X-Real-IP"
      caddy.tls: $EMAIL
      caddy.encode: gzip
      caddy.header.X-XSS-Protection: '"1; mode=block;"'
      caddy.header.X-Frame-Options: "DENY"
      caddy.header.X-Content-Type-Options: "none"
      caddy.reverse_proxy_0: "/notifications/hub/negotiate {{upstreams 80}}"
      caddy.reverse_proxy_1: "/notifications/hub {{upstreams 3012}}"
```

From the bitwarden example I thought `caddy.header.up: "X-Real-IP" should apply only to `caddy.reverse_proxy: "{{upstreams 80}}"`, not the extra two reverse proxies?
From your documentation, I believe I can do this: 
```
      caddy.reverse_proxy.header.up: "X-Real-IP"
```
To apply it only to reverse_proxy, not reverse_proxy_0 and reverse_proxy_1
