### ISSUE TITLE
Not really an issue, but would like to know how to use it 

### ISSUE THREAD

**Issue by vijaykarani333** [lucaslorentz/caddy-docker-proxy#230]
edited to update the padding 
Please show how we can use it as a reverse proxy using one compose file (after so many attempt without luck.)
Originally, the docker-compose.yaml file as:

```
services:
  cal:
    image: django_cal:latest
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: cal
    restart: always
    working_dir: /app/cal
    entrypoint: /app/entrypoints/cal.sh
    ports:
      - "2021:2021"
    env_file:
       - .env
    depends_on:
      db:
        condition: service_started
    healthcheck:
      test: curl --fail http://127.0.0.1:2021/ping/ || exit 1
      interval: 10s
      timeout: 2s
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
      - type: bind
        source: ./media
        target: /app/media
  db:
    image: postgres:12.5
    restart: always
    container_name: cal_db
    environment:
      - POSTGRES_USER=***
      - POSTGRES_PASSWORD=***
      - POSTGRES_DB=***
```

Have modified it as below but it doesn't work. Please point out what more changes are needed.  

```
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - reverse_proxy_from=cal:2021
      - reverse_proxy_to=localhost
    restart: unless-stopped
    
  cal:
    image: django_cal:latest
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: cal
    restart: always
    working_dir: /app/cal
    entrypoint: /app/entrypoints/cal.sh
    labels:
        caddy: localhost
        caddy.reverse_proxy: "{{upstreams 2021}}" 
    ports:
      - "2021:2021"
    env_file:
       - .env
    depends_on:
      db:
        condition: service_started
    healthcheck:
      test: curl --fail http://127.0.0.1:2021/ping/ || exit 1
      interval: 10s
      timeout: 2s
    volumes:
      - type: bind
        source: ./logs
        target: /app/logs
      - type: bind
        source: ./media
        target: /app/media
  db:
    image: postgres:12.5
    restart: always
    container_name: cal_db
    environment:
      - POSTGRES_USER=***
      - POSTGRES_PASSWORD=***
      - POSTGRES_DB=***

networks:
  caddy:
    external: true
volumes:
  caddy_data: {}

```
