### ISSUE TITLE
Containers not at the same network even though they are

### ISSUE THREAD

**Issue by hnykda** [lucaslorentz/caddy-docker-proxy#234]
Hi. I am following https://github.com/lucaslorentz/caddy-docker-proxy#basic-usage-example-using-docker-compose, but it simply doesn't work because I get:

```
[WARNING] Container 15a8aba9d9f20f3bc03297b9e161ed1ff9480029640219fd6d9a526a86f8a300 and caddy are not in same network
```

and the generated block based on `{{upstream 8000}}` is "empty" (as if it's not being resolved to proper upstream service):
```
whoami.example.com {
  reverse_proxy
}
```

but I can clearly see that caddy and the other file _are_ at the same network by using `docker inspect`. When I hardcode the hostname, it works fine:

```
version: '3.7'
services:
  whoami:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: whoami.example.com
      caddy.reverse_proxy: "whoami:8000" # "{{upstreams 8000}}"

networks:
  caddy:
    external: true
```
but that's not a great solution. Is there a way how to fix that?

A similar issue seem to be discussed here, but I don't understand the resolution: https://github.com/lucaslorentz/caddy-docker-proxy/issues/104
