### ISSUE TITLE
TCP tunneling feature request

### ISSUE THREAD

**Issue by regbo** [lucaslorentz/caddy-docker-proxy#236]
This plugin is extremely useful when proxying tcp connections over the same ports as http:

https://github.com/mholt/caddy-l4

Currently the plugin does not support Caddyfiles, but instead requires a json config (which isn't supported here)

Right now, I use traefik for TCP tunneling on a different port, but for a lot of use cases that's overkill. It'd be great to see the caddy-l4 plugin baked in here

**Comment by francislavoie** [comment]
This plugin is entirely designed around outputting Caddyfile configs. It would essentially require a total rewrite to output JSON instead.

Best wait until caddy-l4 gains Caddyfile support.

**Comment by regbo** [comment]
Understood. One thing I would suggest, that would enable support for a lot of odd plugins, is a "merge" functionality:

As a potential implementation, your code can first "adapt" the generated Caddyfile to json (this may already happen):

```
caddy adapt --config CaddyFile.json
```

Then your code could check two environment variables:

JSON_CONFIG_MERGE - This could store a jsonvalue to be merged, or blank for no change.
DEFAULT=""
EX:{"logging":{"logs":{"default":{"level":"DEBUG"}}}}

JSON_CONFIG_MERGE_COMMAND - This could store a jq command that can be used to combine the 2 json objects.
DEFAULT=".[0] * .[1]"
EX:"add"

Then, _if_ JSON_CONFIG_MERGE is not blank, you could have a script run:

```
if [ ! -z "$JSON_CONFIG_MERGE" ]; then
  caddyConfigJson=`cat CaddyFile.json`
  jq -s $JSON_CONFIG_MERGE_COMMAND  \
	    <(echo "${caddyConfigJson}") \
            <(echo "${JSON_CONFIG_MERGE}") > CaddyFile.json
fi
```

For example, using this as an example CaddyFile.json

```
{
	"apps": {
		"http": {
			"servers": {
				"srv0": {
					"listen": [
						":443"
					],
					"routes": [{
							"match": [{
									"host": [
										"portainer.example.com"
									]
								}
							],
							"handle": [{
									"handler": "subroute",
									"routes": [{
											"handle": [{
													"handler": "reverse_proxy",
													"upstreams": [{
															"dial": "10.0.11.8:8080"
														}
													]
												}
											]
										}
									]
								}
							],
							"terminal": true
						}
					]
				}
			}
		}
	}
}

```
We could do the following:

```
JSON_CONFIG_MERGE='{"logging":{"logs":{"default":{"level":"DEBUG"}}}}'
JSON_CONFIG_MERGE_COMMAND=add

caddyConfigJson=`cat CaddyFile.json`
jq -s $JSON_CONFIG_MERGE_COMMAND  \
	  <(echo "${caddyConfigJson}") \
          <(echo "${JSON_CONFIG_MERGE}") > CaddyFile.merged.json

```
Finally here is the merged file CaddyFile.merged.json:

```
{
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":443"
          ],
          "routes": [
            {
              "match": [
                {
                  "host": [
                    "portainer.example.com"
                  ]
                }
              ],
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [
                            {
                              "dial": "10.0.11.8:8080"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ],
              "terminal": true
            }
          ]
        }
      }
    }
  },
  "logging": {
    "logs": {
      "default": {
        "level": "DEBUG"
      }
    }
  }
}
```

**Comment by regbo** [comment]
I had a closer look at your code, and it looks like it's in GO. Maybe something similar to the above could be achieved with:
https://pkg.go.dev/github.com/RaveNoX/go-jsonmerge

**Comment by lucaslorentz** [comment]
I think this is doable, and we had requests before to support json configuration.
Maybe we can use json patch syntax.

**Comment by BinaryBen** [comment]
Damn, was coming to ask for advice on how to make the L4 plugin work as well. Hoping to get SSH access over port 443 like Github provides to get around stupid work firewalls. I don't know Go. Would this be something a novice could implement if I tried or will I best to just wait? JSON support would be great.

**Comment by pwFoo** [comment]
Caddy-l4 combined with caddy-docker-proxy would be great! At the moment I use an older sshpiper with docker-gen and a custom quick and dirty script to proxy SSH / sftp.

**Comment by KiARC** [comment]
I agree with @binaryben, I've been trying to do the same thing for a while to get a VPN running such that I can do stuff like vpn.example.com to access an OpenVPN server, but of course Caddy normally only does HTTP traffic so that won't work without [mholt/caddy-l4](https://github.com/mholt/caddy-l4) support.

**Comment by Mikle-Bond** [comment]
This can be partially implemented with https://github.com/RussellLuo/caddy-ext/tree/master/layer4

Build caddy image with `github.com/RussellLuo/caddy-ext/layer4` and `github.com/lucaslorentz/caddy-docker-proxy/v2`. Then you can define rules like this:

```yaml
    layer4:
        restart: always
        init: true
        network_mode: none
        read_only: true
        image: alpine
        command: sleep infinity
        labels:
            caddy.layer4.:21101.proxy.to: 192.168.100.101:3000
            caddy.layer4.:21069.proxy.to: 192.168.100.69:3000
            # ....
```

**Comment by di-rect** [comment]
> This can be partially implemented with https://github.com/RussellLuo/caddy-ext/tree/master/layer4
> 
> Build caddy image with `github.com/RussellLuo/caddy-ext/layer4` and `github.com/lucaslorentz/caddy-docker-proxy/v2`. Then you can define rules like this:
> 
> ```yaml
>     layer4:
>         restart: always
>         init: true
>         network_mode: none
>         read_only: true
>         image: alpine
>         command: sleep infinity
>         labels:
>             caddy.layer4.:21101.proxy.to: 192.168.100.101:3000
>             caddy.layer4.:21069.proxy.to: 192.168.100.69:3000
>             # ....
> ```

This is exactly what I'm looking for a the moment as I need sticky TCP connections for IMAP where Traefik doesn't support these.

Can you clear something more out ? Can you make an example for (swarm) services for an example ?

github.com/lucaslorentz/caddy-docker-proxy/v2 doesn't work but he has something in github.com/lucaslorentz/caddy-docker-proxy tho.

Some more (working) detailed info would be great!

Thanks!

**Comment by Mikle-Bond** [comment]
Hi, @di-rect 

Sorry, I didn't get what you mean exactly. What problem do you experience? That snippet is part of my configs (with ports and IPs replaced with more generic ones). I don't use Swarm, but I guess moving labels into `deploy` section would be enough.

If you see any errors with this kind of setup in caddy's logs - that would make it easier to help.

In the snippet I provided I use a dummy container, that only runs `sleep infinity`. Its sole purpose is to provide the labels. I do that to make configuration "ad-hoc".

Anyway, here's a full `docker-compose.yml` example. 

```yaml
version: "3.9"

volumes:
    data_caddy: {}

networks:
    ingress:

x-constants:
    - &default_restart unless-stopped

x-snippets:
    environment: &env
        PUID: 
        PGID:
        TZ:
    networks: &net
        ingress:

x-templates:
    default: &default
        environment: *env
        networks: *net
        restart: *default_restart

    dummy: &dummy
        restart: *default_restart
        environment: *env
        init: true
        network_mode: none
        read_only: true
        image: alpine
        command: sleep infinity

services:
    caddy:
        <<: *default
        container_name: caddy
        build:
            context: build/caddy
            args:
                VERSION: ${CADDY_VERSION}
                GOPROXY: https://goproxy.io|https://proxy.golang.org|direct
                PLUGINS: >-
                    github.com/RussellLuo/caddy-ext/layer4
                    github.com/lucaslorentz/caddy-docker-proxy/v2
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
            - "443:443/udp"
            - "9143:9143/tcp"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /config/caddy:/config:ro
            - data_caddy:/data
        environment:
            <<: *env
            BASE_DOMAIN: # passed from .env
            CADDY_DOCKER_CADDYFILE_PATH: /config/Caddyfile.globals
            CADDY_DOCKER_PROCESS_CADDYFILE: "true"
            XDG_CONFIG_HOME: /data
        labels:
            caddy.log: default
            caddy.log.format: json

    example1:
        <<: *dummy
        labels:
            caddy.layer4.:9143.proxy.to: 192.168.100.100:143

    example2:
        <<: *default
        image: marcnuri/port-forward
        environment:
            REMOTE_HOST: 192.168.100.100
            REMOTE_PORT: 143
        ports:
            - 
                target: 80
                published: 143
                protocol: tcp
                mode: host
```

Also `.env` file has

```sh
PUID=1052
PGID=1052
TZ=Europe/Moscow
CADDY_VERSION=2.7.5
BASE_DOMAIN=my-domain.example
```

And in `build/caddy/Dockerfile` I have

```dockerfile
# syntax=docker/dockerfile-upstream:master-labs
ARG VERSION=2.6.2
FROM caddy:${VERSION}-builder as builder

ARG GOPROXY=https://proxy.golang.org|direct

# space-separated list of plugins
ARG PLUGINS=github.com/lucaslorentz/caddy-docker-proxy/v2

ENV GOMODCACHE=/modcache
RUN --mount=type=cache,target=/modcache/cache <<"EOF"
        xcaddy build ` echo "$PLUGINS" | xargs -r printf "--with %s " `
EOF

ARG VERSION=${VERSION}
FROM caddy:${VERSION}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

ENTRYPOINT ["caddy"]
CMD ["docker-proxy"]
```

This setup shows two examples of how to proxy raw TCP traffic. Assuming you have IMAP server listening at `192.168.100.100:143` (it can be referenced by hostname too).

`example1` uses layer4 plugin to forward traffic from port 9143 to the IMAP server. Notice that this approach requires you to mention this port in `caddy` service explicitly. 

`example2` is another approach I use sometimes. `marcnuri/port-forward` image is a wrapper around `socat` that forward from port 80 (by default) to whatever host:port you specify. In this case, you need to define port-forwarding for this service.

**Comment by di-rect** [comment]
@Mikle-Bond Wow thanks for the explanation!

This looks good, I needed the explanation of the forwarding in the labels!

As you might know; IMAP needs sticky connections from a host to the same backend server when doing loadbalancing. I'm trying to figure out how I could accomplish this within docker swarm as my connection goes all over the place between the IMAP containers when using Traefik.

As IMAP is TCP I first need the TCP plugin for Caddy but then; the sticky part with this/your implementation. Would that be possible for Caddy you think ?

**Comment by Mikle-Bond** [comment]
Ah. Well, I see that layer4 implements the IP-hash load balancing policy: https://github.com/mholt/caddy-l4/blob/78853879f66772f4363a3dbfcd7104e8672dbdb3/modules/l4proxy/loadbalancing.go#L268-L270

You could try adding this in labels of the IMAP service:

```yaml
caddy.layer4.:143.proxy.to: "{{ upstreams 143 }}"
caddy.layer4.:143.proxy.lb_policy: ip_hash
```

Though this might not work if your caddy server doesn't receive real client IP and only sees ingress IP. I'm not sure how Swarm handles this. You will probably have to follow [this advice](https://stackoverflow.com/a/50592485) too, and configure port 143 into host-mode forwarding on caddy service.

**Comment by smaccona** [comment]
@Mikle-Bond thank you for the explanations above which were very helpful. I'm using Swarm mode, and I'm having trouble with the labels I am using not getting translated into Caddy-compliant `layer4` Caddyfile entries. I've built a custom image with both `caddy-docker-proxy` and `caddy-ext/layer4`. Here's the `Dockerfile`:

```
FROM caddy:builder-alpine as builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/RussellLuo/caddy-ext/layer4

FROM caddy:alpine

COPY --from=builder /usr/bin/caddy /bin/caddy

ENTRYPOINT ["/bin/caddy"]

CMD ["docker-proxy"]
```

I am running Caddy via Docker Compose in `host` network mode, not in Swarm mode, because I ultimately want Caddy to map specific IP addresses to services, and Swarm doesn't allow binding to specific IP addresses (because it defeats the purpose of scalable stacks across multiple hosts, though then again Kubernetes does allow that). Here's the Docker Compose YAML for that:

```yaml
version: '3.3'

services:
  caddy:
    image: <image I built above in internal registry>
    container_name: caddy
    network_mode: host
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volumes/caddy_data:/data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
```

And here's how I am using the labels in my Swarm YAML file for my deployment:

```yaml
version: "3.8"

services:

  mc:
    ...
    deploy:
      labels:
        caddy.layer4.:6692.proxy.to: "{{upstreams 6692}}"
    networks:
      ...
      - caddy
```

With this setup, I get an error in the Caddy container:

```
{"level":"info","ts":1703087529.608864,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: parsing caddyfile tokens for 'layer4': wrong argument count or unexpected line ending after 'to', at Caddyfile:5\n{\n\tlayer4 {\n\t\t:6692 {\n\t\t\tproxy {\n\t\t\t\tto\n\t\t\t}\n\t\t}\n\t}\n}\n\n"}
```

Expanding all the `\n` and `\t`s, this is what is getting entered in the Caddyfile:

```
{
	layer4 {
		:6692 {
			proxy {
				to
			}
		}
	}
}
```

So my `"{{upstreams 6692}}"` is not getting processed into the Caddyfile. If I move the `labels` outside of the `deploy` entry, I get a different error:

```
{"level":"info","ts":1703088044.5198956,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: parsing caddyfile tokens for 'layer4': wrong argument count or unexpected line ending after 'to', at Caddyfile:5\n{\n\tlayer4 {\n\t\t:6692 {\n\t\t\tproxy {\n\t\t\t\tto\n\t\t\t\tto 192.168.144.2:6692\n\t\t\t}\n\t\t}\n\t}\n}\n\n"}
```

Again expanding:

```
{
	layer4 {
		:6692 {
			proxy {
				to
				to 192.168.144.2:6692
			}
		}
	}
}
```

So this time the `upstreams` are getting included, but there is an additional blank `to` entry. If you (or anyone else) can cast any light on what I am doing wrong here, it would be much appreciated.

**Comment by francislavoie** [comment]
You might have an old copy of a container with the old label stopped but not removed. Make sure to wipe out all stopped containers. You can run `docker system prune` I think. Then down your stack and bring it back up.

**Comment by smaccona** [comment]
@francislavoie thank for the response. In my original test, I completely removed the stack using `docker stack rm` and reprovisioned it using ` docker stack deploy -c <YAML-file>`. I just removed it again, did a `docker system prune` like you suggested, and redeployed it with the `labels` under `deploy`.  Here's the resulting config in the Caddy container:

```
{
	layer4 {
		:6692 {
			proxy {
				to
			}
		}
	}
}
```

I moved the `labels` up a level (outside of `deploy`) as a test as well - removed the stack, did another `docker system prune` and redeployed the stack. This time, I got the same config as above, which is different than what I got the previous time (when I didn't do a `docker system prune`) - the previous time, it did insert the IP address after the `to`, but there was a second blank `to` which was causing an error.

I'm not sure of next steps here - I would love to have the ability to map host TCP ports to docker services without having to manually specify container IPs. I think my next step will be to run two separate Caddy instances, one with `caddy-docker-proxy` to automatically proxy web services, and one with `layer4` which I will have to manually configure (which will be painful as I have 100s of these port mappings to manage).

If anyone has any other ideas about what I am doing wrong here, please let me know! Thanks in advance.

**Comment by lucaslorentz** [comment]
> If I move the labels outside of the deploy entry, I get a different error

@smaccona did you move it or duplicated labels in 2 levels?

Probably the container network is not being detected as an ingress network by CDP. Try configuring ingress-networks as per readme. Maybe use "host" as network name, but I'm not sure if that works for host network

**Comment by smaccona** [comment]
I was able to resolve this - my issue was that the `caddy` network was created in Swarm mode but I forgot to make it attachable. Thank you all for your help.

**Comment by lucaslorentz** [comment]
Closing as this can now be achieved using https://github.com/RussellLuo/caddy-ext/tree/master/layer4

If any feature from [mholt/caddy-l4](https://github.com/mholt/caddy-l4) cannot be represented in Caddyfile, I would suggest opening an issue or contributing to https://github.com/RussellLuo/caddy-ext/tree/master/layer4

**Comment by KiARC** [comment]
Given that [mholt/caddy-l4](https://github.com/mholt/caddy-l4) now supports Caddyfile configuration, could this get another look? The `layer4` module in [RussellLuo/caddy-ext](https://github.com/RussellLuo/caddy-ext/tree/master/layer4) doesn't have an intuitive way to multiplex SSH over TLS, so you can't have something like `ssh.example.com` and `example.com` running through the same port.

**Comment by binaryben** [comment]
Also for email protocols 🙏

**Comment by DonDebonair** [comment]
Given that caddy-docker-proxy seems to just generate a Caddyfile based on labels, wouldn't it support any Caddy plugin out of the box as long as that plugin supports Caddyfile?

**Comment by binaryben** [comment]
@DonDebonair I’m expecting so and hoping to test exactly that if I get time in the next couple of weeks. Hopefully a Dockerfile with the builder variant will be all that’s needed. If it is the case, I am wondering if this would be something worth including in the standard image though.

**Comment by DonDebonair** [comment]
@binaryben and others who are curious, I have tested caddy-l4 with caddy-docker-proxy and I can confirm that it works! 🎉 

**What I wanted to achieve:** forward SSH traffic through a Caddy container to another container running [Forgejo](https://forgejo.org/)

**How I did it:**

1. Expose port 22 on my Caddy container (next to 80 and 443)
2. Add labels in the Docker Compose file to enable a layer4 proxy for SSH traffic arriving on port 22
3. ...
4. Profit!

**What my Docker Compose file looks like**

```yml
services:
  caddy:
    # I built this image myself using the caddy-builder. See below for Dockerfile
    image: caddy-custom:2.8.4
    container_name: caddy
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      caddy-internal:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /my-data/caddy:/data
    restart: unless-stopped
    expose:
      - "80"
      - "443"
      - "22"
    labels:
      # I removed some stuff here that I use but is not relevant for this demonstration, such as acme config
      caddy.layer4.:22.@git: ssh
      caddy.layer4.:22.route: "@git"
      caddy.layer4.:22.route.proxy: "upstream forgejo:22". # I have a container called 'forgejo' running on the 'caddy' network

networks:
  # I created this network outside of this Docker Compose file because I reuse it in other compose files
  caddy-network:  
    external: true
```

**Dockerfile for custom Caddy build**

```
ARG CADDY_VERSION=2.8.4
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/mholt/caddy-l4

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

I hope this helps!\

@lucaslorentz it might be useful do add some docs around using caddy-l4 together with caddy-docker-proxy.

**Comment by binaryben** [comment]
@DonDebonair Heck yeh! That is epic. Exactly one of the use cases I have in mind (SSH access to git@gitea). Also hoping this will work on mail ports with Stalwart.

Thank you to everyone who got this working!

**Comment by Mikle-Bond** [comment]
@DonDebonair @binaryben 
I don't want to disappoint you, but this example seems to not require `layer4` plugin, as there's no difference with publishing a port `22` from gitea/forgeo. In case you can't or don't want to publish ports from the target container, you can spawn `marcnuri/port-forward` or anything with `socat` in it:

```yaml
services:
    forgejo-ssh-port-forward:
        image: marcnuri/port-forward
        environment:
            REMOTE_HOST: forgejo
            REMOTE_PORT: 22
            LOCAL_PORT: 22
        ports:
            - 
                target: 22
                published: 22
                protocol: tcp
                mode: host
        networks:
            your-private-network-between-forgejo-and-this-container: {}
```

IMO, the power of `layer4` is in using Caddy's machinery to multiplex several protocols on the same port, use automatic TLS on arbitrary protocols, or both.

I'd say the only thing that is lacking right now, is some examples on how to convert configs from the format of https://github.com/RussellLuo/caddy-ext/tree/master/layer4 into format used in https://github.com/mholt/caddy-l4. Particularly, I don't see an example of using multiple upstreams and load-balancing policies in mholt's version (I'm sure it is possible, just not obvious how to spell it in Caddyfile). But again, this is a non-issue for this repository.

@KiARC , you mentioned SSH-over-TLS, and I see how it is extremely possible with `layer4` to do on server, but how is that supposed to work on client side? I'm curious) At this point I can only theorize, but something like this should split traffic to `ssh.example.com`, terminate TLS connection, and forward SSH connections into `sshbox:22`, while allowing all other websites to be served on the same port, without changes to their configs

```yaml
services:
  caddy:
    ports:
      - 443:8443/tcp
      - 80:80/tcp
    labels:
      caddy.layer4.:8443.@sshovertls: tls sni ssh.example.com
      caddy.layer4.:8443.10_route: "@sshovertls"
      caddy.layer4.:8443.10_route.subroute.@ssh: ssh
      caddy.layer4.:8443.10_route.subroute.route: "@ssh"
      caddy.layer4.:8443.10_route.subroute.route.proxy: "upstream sshbox:22"

      caddy.layer4.:8443.@secure: tls
      caddy.layer4.:8443.20_route_10: "@secure"
      caddy.layer4.:8443.20_route_11.proxy: "upstream 127.0.0.1:443"
```

**Comment by KiARC** [comment]
@Mikle-Bond that seems like it'd work, except I'm trying to figure out a way to be able to do this without global config. Ideally, in the same way that each HTTPS reverse proxy is configured on the container it's for, the SSH-over-TLS config could be labeled on the container it's for. For the client, something like stunnel could work, I think.

**Comment by DonDebonair** [comment]
@Mikle-Bond I don't understand your point. People were asking if the Caddyfile syntax that caddy-l4 requires can be produced by caddy-docker-proxy with labels, and I have shown an example that is proven to work. Whether the use case I've demonstrated is complex or not and can be achieved by other means is inconsequential. The question was: can we use caddy-l4 with caddy-docker-proxy and the answer is yes.

Besides, going by @binaryben 's reaction that has helped at least 1 person. Why rain on that parade?

Now, as for my use case. The solutions you've shown do not solve my problem. I don't want expose port 22 on the host the Forgejo container runs on, on the container itself or on another container running port-forward. I want to expose that port on the Caddy container that also proxies HTTPS traffic to my Forgejo container. That way, in my DNS resolver I can point `git.example.com` to my Caddy container (which runs on a macvlan network btw) and use that domain/hostname for both HTTPS and SSH traffic.

**Comment by Mikle-Bond** [comment]
@DonDebonair sorry if I was harsh. That was not my intent. Your use case seems interesting in the light of additional context. I've only used macvlans once, and my reason was to make the docker host part of the docker-managed network, while letting `systemd-networkd` manage the address and DNS on that link instead of `dockerd` itself. I'm curious to hear more about your reasons behind it)

Anyway, I brought some intel.

First: the config snippets do not seem to be correct. Both your, @DonDebonair and mine, as I didn't double-check before posting. Namely:

```
route @git {
	proxy upstream forgejo:22
}
```

will treat `upstream` as a hostname, not as directive. Correct syntax is, in labels:

```yaml
caddy.layer4.:22.route.proxy: "forgejo:22"
# or
caddy.layer4.:22.route.proxy.upstream: "forgejo:22"
```

Second, I tried and succeeded with SSH-over-TLS thing. My previous example has flaws. For example, it routes traffic from port `8443` to `443`, which means it makes every packet to have `127.0.0.1` as both source and destination address. So we need to add `proxy_protocol` as a wrapper. Full config:

```yaml
services:
    caddy:
        <<: *default
        container_name: caddy
        build:
            context: build/caddy
            args:
                VERSION: ${CADDY_VERSION}
                GOPROXY: https://goproxy.io|https://proxy.golang.org|direct
                PLUGINS: >-
                    github.com/mholt/caddy-l4
                    github.com/lucaslorentz/caddy-docker-proxy/v2
        ports:
            - "80:80/tcp"
            - "443:8443/tcp"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /config/caddy:/config:ro
            - data_caddy:/data
            - priv_caddy:/secrets:ro
        environment:
            BASE_DOMAIN: # passed from .env

            CADDY_DOCKER_CADDYFILE_PATH: /config/Caddyfile.globals
            CADDY_DOCKER_PROCESS_CADDYFILE: "true"
            CADDY_DOCKER_SCAN_STOPPED_CONTAINERS: "false"

            XDG_CONFIG_HOME: /data
        labels:
            caddy.local_certs:
            caddy.log: default
            caddy.log.format: json
            caddy.servers.trusted_proxies: static 10.8.8.21/32 127.0.0.0/8
            caddy.servers.listener_wrappers.1_proxy_protocol.timeout: 2s
            caddy.servers.listener_wrappers.1_proxy_protocol.allow: 127.0.0.1/32
            caddy.servers.listener_wrappers.2_tls:

            caddy.layer4.:8443.@secure: tls
            caddy.layer4.:8443.50_route: "@secure"
            caddy.layer4.:8443.50_route.proxy.upstream: 127.0.0.1:443
            caddy.layer4.:8443.50_route.proxy.proxy_protocol: v2

    ssh:
        <<: *default
        image: praqma/alpine-sshd
        expose: [22]
        environment:
            AUTHORIZED_KEYS: |
                ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF43Ffr6ZepoFCMWd1XZLuqNFUiIej89h85a0+1bp+h1
        labels:
            caddy.layer4.:8443.@sshovertls: tls sni ssh.${BASE_DOMAIN}
            caddy.layer4.:8443.10_route: "@sshovertls"
            caddy.layer4.:8443.10_route.1_tls:
            caddy.layer4.:8443.10_route.2_subroute.@ssh: ssh
            caddy.layer4.:8443.10_route.2_subroute.route: "@ssh"
            caddy.layer4.:8443.10_route.2_subroute.route.proxy: '{{upstreams 22}}'

            caddy_1: ssh.${BASE_DOMAIN}
            caddy_1.respond: 204
```

The rest (like `*default` anchor definition) I have mentioned in one of my previous comments. Note, that `CADDY_VERSION` needs to be `2.8.4` or above.

You can see that:
- in the `layer4` section the traffic is wrapped into PROXY protocol with `proxy_protocol` parameter (`v2` means "binary format" as opposed to "human-readable" `v1`)
- we need to set `trusted_proxies` and `listener_wrappers` in the global section to unwrap PROXY protocol
- I use `50_route` as a block for regular TLS traffic, and any override can be placed "above" it with `10_route`, `20_route`, etc. or "below" it
- the SSH-over-TLS stuff is defined in the SSH container's labels, almost modular, just like @KiARC requested
- as it turns out, neither `tls` handler nor `tls sni` matcher do not enable automatic certificate management, so I had to trick it by adding `respond 204` statement with correct domain name, just for the sake of certificate; I'm not sure, but there might be better ways to do this
- the `subroute` section with `@ssh` matcher is pure aesthetics and can be simplified into `caddy.layer4.:8443.10_route.2_proxy: '{{upstreams 22}}'`
- the big flaw of this design is that both the matcher names and numbers near `XX_route` should be unique per-container (unless you know what you are doing and want them to merge)

The Caddyfile sections produced look like this:

```caddyfile
{
        layer4 {
                :8443 {
                        @secure tls
                        @sshovertls tls sni ssh.photon.internal
                        route @sshovertls {
                                tls
                                subroute {
                                        @ssh ssh
                                        route @ssh {
                                                proxy 172.20.1.41:22
                                        }
                                }
                        }
                        route @secure {
                                proxy {
                                        proxy_protocol v2
                                        upstream 127.0.0.1:443
                                }
                        }
                }
        }
        local_certs
        log default {
                format json
        }
        servers {
                listener_wrappers {
                        proxy_protocol {
                                allow 127.0.0.1/32
                                timeout 2s
                        }
                        tls
                }
                trusted_proxies static 10.8.8.21/32 127.0.0.0/8
        }
}
ssh.photon.internal {
        respond 204
}
```

Finally, on the client side, stunnel config:

```ini
client=yes
[ssh]
accept=2443
connect=ssh.photon.internal:443
```

and connect via `ssh -p 2443 root@localhost`.
