### ISSUE TITLE
file_server not working in contrast to default caddy image

### ISSUE THREAD

**Issue by redturtlepower** [lucaslorentz/caddy-docker-proxy#239]
Caddyfile:
```
cdn.mydomain.com {
  root * /var/www/cdn
  file_server browse
}
```

stack-caddy.yml
```
---
version: "3.8"

services:
  caddy:
#    image: "caddy/caddy:latest"
    image: "lucaslorentz/caddy-docker-proxy:2.3.4-alpine"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./caddylogs:/logs"
      - "./cdndata:/var/www/cdn"
      - "./Caddyfile:/etc/caddy/Caddyfile"
    networks:
      - my-network
```

Running with
```
docker network create -d overlay --attachable my-network
docker stack deploy -c stack-caddy.yml --resolve-image always --with-registry-auth my-caddy
```

The caddyfile just sets up a simple file server.
When I use the default image, it works. Using the caddy-docker-proxy image, the site never loads. 
Did this image remove features of caddy?
I feel the auto-generated Caddyfile from the docker services naively overwrites any existing Caddyfile, so both methods can never be used together. This doesn't make sense at all. Am I understanding correctly?
