### ISSUE TITLE
Using wildcard certificates through Cloudflare

### ISSUE THREAD

**Issue by anLizard** [lucaslorentz/caddy-docker-proxy#244]
Hi, I am trying to get a wildcard certificate through Cloudflare, but keep running into ERR_SSL_PROTOCOL_ERROR on Chrome and SSL_ERROR_INTERNAL_ERROR_ALERT on Firefox when opening the page.

Caddy's docker-compose.yml:
```
version: "3"

networks:
  internal:
  external:

services:

  reverse-proxy:
    image: lucaslorentz/caddy-docker-proxy:latest
    networks:
      - internal
      - external
    ports:
      - 80:8080
      - 443:4443
    restart: always
    volumes:
      - ./data:/data/caddy
      - ./www:/var/www:ro
      - /etc/localtime:/etc/localtime:ro
    user: 1000:1000
    environment:
      - CADDY_DOCKER_CADDYFILE_PATH=/data/Caddyfile
      - DOCKER_HOST=tcp://socket-proxy:2375
      - MY_DOMAIN=example.com
      - CLOUDFLARE_EMAIL=mail@example.com
      - CLOUDFLARE_API_KEY=<GLOBAL API KEY>
    labels:
      - caddy.email=mail@example.com
      - caddy.http_port=8080
      - caddy.https_port=4443
    depends_on:
      - socket-proxy
```

nginx's docker-compose.yml:
```
version: "3"

networks:
  internal:
  caddy_external:
    external: true

services:

  web-server:
    image: linuxserver/nginx
    networks:
      - internal
      - caddy_external
    expose:
      ## HTTP
      - 80
    restart: always
    volumes:
      - .:/config
      - /www:/var/www:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=CET
    labels:
      - caddy_0=$MY_DOMAIN
      - caddy_0.reverse_proxy={{upstreams 80}}
      - caddy_0.tls.dns=cloudflare
      - caddy_0.tls.wildcard=""
      - caddy_1=cdn.$MY_DOMAIN
      - caddy_1.reverse_proxy={{upstreams 80}}
      - caddy_1.tls.dns=cloudflare
      - caddy_1.tls.wildcard=""
      - caddy_2=www.$MY_DOMAIN
      - caddy_2.reverse_proxy={{upstreams 80}}
      - caddy_2.tls.dns=cloudflare
      - caddy_2.tls.wildcard=""
```

If I remove these lines the pages become accessible again, but using their own certs instead of the wildcard.
```
      - caddy_0.tls.dns=cloudflare
      - caddy_0.tls.wildcard=""
```
