### ISSUE TITLE
[question] how can i access the admin api from another container?

### ISSUE THREAD

**Issue by arulagrawal** [lucaslorentz/caddy-docker-proxy#246]
I have my caddy container and another container in the same network, however that other container cannot access the api/metrics at caddy:2019/metrics. I imagine this has to do with caddy listening on localhost:2019 by default, but I cannot figure out how to change this.

this is my docker-compose.yml
```
version: "3.7"
services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=web
    networks:
      - web
      - prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/data/caddy:/data
    restart: unless-stopped
    labels:
      caddy.admin.listen: "0.0.0.0:2019"

networks:
  web:
    external: true
  prometheus:
    external: true
```
to try and expose :2019 but I get this error:
```
[ERROR]  Removing invalid block: parsing caddyfile tokens for 'admin': Caddyfile:3 - Error during parsing: unrecognized parameter 'address'
{
	admin {
		address 0.0.0.0:2019
	}
}
```

to be clear, what I'm actually trying to do is access the caddy metrics api from grafana to create a dashboard.

I suppose I could put grafana in the same docker-compose file as caddy but i'd rather keep them separate. Thanks
