### ISSUE TITLE
Config Question - caddy-docker-proxy with a VPN

### ISSUE THREAD

**Issue by samcro1967** [lucaslorentz/caddy-docker-proxy#248]
Wondering if it is possible to use caddy-docker-proxy with a VPN.  I have one container that connects to a VPN provider.  Other containers then attach to its network using network_mode.  I have caddy running on the same network as the VPN container.  The containers that connect to the VPN container then no longer get an IP address.  Their exposed ports of the connected containers are then moved from their config to the config of the VPN container.

I tried to use the docker host IP and the IP of the VPN container, but neither is working.  This does work with the caddy, but not sure it will work with this container. I tried both the external an internal ports for bazarr also.

Any thoughts on whether this can work?

```
    labels:
     - caddy_0= "http://local.bazarr"
     - caddy_0.reverse_proxy= "192.168.1.104:8096"
     - caddy_0.tls= "internal"
     - caddy_1= "bazarr.domain.net"
     - caddy_1.reverse_proxy= "192.168.1.104:8096"
     - caddy_1.tls= "user@domain.net"
    network_mode: "vpn"
    depends_on:
      - vpn
```
