### ISSUE TITLE
Http only setting still redirects to https if TLD is a valid one?

### ISSUE THREAD

**Issue by github0013** [lucaslorentz/caddy-docker-proxy#251]
![Screen Shot 2021-05-17 at 9 08 27](https://user-images.githubusercontent.com/809378/118417563-90572000-b6ef-11eb-8608-ad95cc7ddfec.png)
![Screen Shot 2021-05-17 at 9 08 43](https://user-images.githubusercontent.com/809378/118417565-92b97a00-b6ef-11eb-901f-052fa0b2effd.png)

I also wanted to have a http only server for my private network, so I set up by following this issue.
https://github.com/lucaslorentz/caddy-docker-proxy/issues/172

It seems if the TLD is a valid one (like .dev, .com, ...), it still tries to redirect to `https` (please see the screenshots above and notice .dev gets https - I did type in `http://domain.dev`).

If this is a caddy issue, I will post this there.

### here are my settings

```yml
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.3-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy/data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true
```

```yml
version: "3.7"
services:
  whoami1:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: http://domain.tld
      caddy.reverse_proxy: "{{upstreams http 8000 }}"

  whoami2:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: http://domain.dev
      caddy.reverse_proxy: "{{upstreams http 8000 }}"

networks:
  caddy:
    external: true

```

```
~ » ping domain.tld
PING domain.tld (100.120.120.94): 56 data bytes
64 bytes from 100.120.120.94: icmp_seq=0 ttl=64 time=4.960 ms
64 bytes from 100.120.120.94: icmp_seq=1 ttl=64 time=5.288 ms
^C
--- domain.tld ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.960/5.124/5.288/0.164 ms

-----------

~ » ping domain.dev
PING domain.dev (100.120.120.94): 56 data bytes
64 bytes from 100.120.120.94: icmp_seq=0 ttl=64 time=8.616 ms
64 bytes from 100.120.120.94: icmp_seq=1 ttl=64 time=4.466 ms
^C
--- domain.dev ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.466/6.541/8.616/2.075 ms
```

cat /config/caddy/autosave.json

```json
{
  "admin": { "listen": "tcp/localhost:2019" },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "automatic_https": { "skip": ["domain.dev", "domain.tld"] },
          "listen": [":80"],
          "routes": [
            {
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [{ "dial": "172.22.0.3:8000" }]
                        }
                      ]
                    }
                  ]
                }
              ],
              "match": [{ "host": ["domain.dev"] }],
              "terminal": true
            },
            {
              "handle": [
                {
                  "handler": "subroute",
                  "routes": [
                    {
                      "handle": [
                        {
                          "handler": "reverse_proxy",
                          "upstreams": [{ "dial": "172.22.0.4:8000" }]
                        }
                      ]
                    }
                  ]
                }
              ],
              "match": [{ "host": ["domain.tld"] }],
              "terminal": true
            }
          ]
        }
      }
    }
  }
}
```
