### ISSUE TITLE
Can't make it work with multiple ports enabled

### ISSUE THREAD

**Issue by jdutheil** [lucaslorentz/caddy-docker-proxy#252]
Hi,

I am using ApiPlatform 2.6, and would like to use your caddy-docker-proxy in order to have multiple subdomaines on my server. I can't find a way to make things working "nicely", ending up with an error 502. My caddy server I want to reach with the reverse proxy is published on port 4431, so basically I need to route all requests goind to mysubdomain.domain.tld to mysubdomain.domain.tld:4431

It works with these labels :

```
labels:
      caddy: mysubdomain.domain.tld
      caddy.reverse_proxy: https://mysubdomain.domain.tld:4431
```

But I can't success with {{upstreams}} or such, tryed basically everything but always end up with 502 errors or "too many redirects". 

Here is the full container in docker-compose :

```
caddy:
    build:
      context: api/
      target: api_platform_caddy
    depends_on:
      - php
      - client
    environment:
      SERVER_NAME: mysubdomain.domain.tld
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-!ChangeMe!}
    labels:
      caddy: mysubdomain.domain.tld
      caddy.reverse_proxy: https://mysubdomain.domain.tld:4431
      #caddy.reverse_proxy: "{{upstreams https 4431}}"
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: 8081
        protocol: tcp
      # HTTPS
      - target: 443
        published: 4431
        protocol: tcp
      # HTTP/3
      - target: 443
        published: 4431
        protocol: udp 
    networks:
      - caddy
```

Thanks
