### ISSUE TITLE
Removing headers from upstream

### ISSUE THREAD

**Issue by patrick-leb** [lucaslorentz/caddy-docker-proxy#256]
Hello there,

I wanted to remove the Server header and the x-powered-by header from the response. 
I tried that: 

```
    deploy:
      labels:
        caddy: example.com
        caddy.reverse_proxy: '{{upstreams 8080}}'
        caddy.reverse_proxy.header_down: -Server
      update_config:
        delay: 10s
```
 but it won't remove the header served to the browser.

I'm not sure either how I'd remove multiple headers.

Thanks for your help !
