### ISSUE TITLE
Upstreams on port 9000 not found ?

### ISSUE THREAD

**Issue by Yamakasi** [lucaslorentz/caddy-docker-proxy#264]
It seems that when I use a port 9000 for upstreams it's not found by the logs.

I'm setting up portainer as a service where others just work on different ports.

Any idea ?

**Comment by francislavoie** [comment]
You'll need to be more specific. Can't help without actual details.

**Comment by Yamakasi** [comment]
Sure! This is what I do:

```version: '3.3'

services:
  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - agent-network
      - caddy
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.portainer.portainer-data == true
      labels:
         caddy: portainer.dogged.team
         caddy.reverse_proxy: "{{upstreams 9000}}"

networks:
  agent-network:
    attachable: true
  caddy:
    external: true

volumes:
  portainer-data:
```

Nothing special if you ask me. The certificate is generated fine. It seems that Caddy does it's job.

**Comment by Yamakasi** [comment]
Sure! This is what I do:

```
version: '3.3'

services:
  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - agent-network
      - caddy
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.labels.portainer.portainer-data == true
      labels:
         caddy: portainer.mydomain.tld
         caddy.reverse_proxy: "{{upstreams 9000}}"


networks:
  agent-network:
    attachable: true
  caddy:
    external: true

volumes:
  portainer-data:

```

Nothing special if you ask me. The certificate is generated fine so Caddy seems to do it's job.

**Comment by lucaslorentz** [comment]
@Yamakasi 
This worked well for me:

```
version: "3.3"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
  
  portainer:
    image: portainer/portainer:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - agent-network
      - caddy
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        caddy: portainer.mydomain.tld
        caddy.reverse_proxy: "{{upstreams 9000}}"
        caddy.tls: "internal"

networks:
  agent-network:
    attachable: true
  caddy:

volumes:
  portainer-data:
```

Test:
```
docker stack deploy -c test.yaml test
curl -k --resolve portainer.mydomain.tld:443:127.0.0.1 https://portainer.mydomain.tld
```

Can you please double check your container is really running? Maybe your placement constraint `node.labels.portainer.portainer-data == true` is not finding a node to run the service.

Check the status of your service tasks by running `docker service ps test_portainer`. Are they running?
