### ISSUE TITLE
Using Caddy with "network_mode: "container:<name>":?

### ISSUE THREAD

**Issue by NoLooseEnds** [lucaslorentz/caddy-docker-proxy#277]
I'm having a hard time getting "network_mode: "container:<name>" to work. It works with Traefik, so should be doable.

Example of the VPN docker:
```
version: '3.7'

services:
  vpn-client:
    container_name: vpn-client
    image: ghcr.io/bubuntux/nordvpn
    init: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - caddy
    environment:
      TZ: '${TZ}'
      USER: '${NORDUSER}'
      PASS: '${NORDPASS}'
      CONNECT: no200
      TECHNOLOGY: NordLynx
      NETWORK: '${NETWORK}'

networks:
  caddy:
    external: true
```

Example docker-compose of service:
```
version: '3.7'
services:
  firefox:
    container_name: "firefox"
    image: "jlesage/firefox"
    init: true
    restart: always
    network_mode: "container:vpn-client"
    volumes:
      - ./config:/config
    environment:
      - TZ=${TZ}
      - DISPLAY_WIDTH=1680
      - DISPLAY_HEIGHT=1050
    labels:
      caddy: firefox.a.b.domain.tld
      caddy.reverse_proxy: "{{upstreams 5800}}"
    shm_size: '2gb'
    security_opt:
      - seccomp:unconfined

networks:
  caddy:
    external: true
```

Caddy log shows:
`{"level":"info","ts":1625948659.5836797,"logger":"tls.obtain","msg":"certificate obtained successfully","identifier":"firefox.a.b.domain.tld"}`

`{"level":"error","ts":1625948675.3452964,"logger":"http.log.error","msg":"no upstreams available","request":{"remote_addr":"10.0.0.151:63590","proto":"HTTP/2.0","method":"GET","host":"firefox.a.b.domain.tld","uri":"/","headers":{"Sec-Fetch-User":["?1"],"Cache-Control":["max-age=0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"],"Accept-Language":["en-GB,en;q=0.5"],"Accept-Encoding":["gzip, deflate, br"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Site":["none"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0"],"Dnt":["1"],"Sec-Fetch-Mode":["navigate"],"Te":["trailers"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"firefox.a.b.domain.tld"}},"duration":0.000085009,"status":502,"err_id":"4xfeiyggp","err_trace":"reverseproxy.statusError (reverseproxy.go:857)"}`

Any advice?

**Comment by lucaslorentz** [comment]
I'm not familiar with network_mode container, how should you reach the firefox container in that case?
Using firefox container IP or vpn-client container IP?

**Comment by lucaslorentz** [comment]
Can you please try to move caddy labels to vpn-client container instead.
Looks like that might solve the issue: https://community.traefik.io/t/docker-compose-with-network-mode-service-service-name/3395

**Comment by NoLooseEnds** [comment]
Thanks for the reply. 

I'm not an expert at all, but afaik the advantage of `network_mode: container:<name>` is that you can have one container (i.e a vpn-client) where you can route specific docker images through, regardless if they are in the same docker-compose or not.

I tested setting the following earlier, but no go. If that would work, I could live with that solution, even if the best solution would be to set all caddy settings it in their respective docker-compose files.

I tried this:
```
version: '3.7'

services:
  vpn-client:
    container_name: vpn-client
    image: ghcr.io/bubuntux/nordvpn
    init: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - caddy
    environment:
      TZ: '${TZ}'
      USER: '${NORDUSER}'
      PASS: '${NORDPASS}'
      CONNECT: no200
      TECHNOLOGY: NordLynx
      NETWORK: '${NETWORK}'
    ports:
      - 5800:5800 #firefox (this should not be necessary, but I did it anyway)
    labels:
      caddy.firefox_0: firefox.a.b.domain.tld
      caddy.firefox_0.reverse_proxy: "{{firefox 5800}}" #trying with the docker container name. I guess {{upstream}} would not work here.

networks:
  caddy:
    external: true
```

Caddy log:
```
{"level":"error","ts":1626116264.950673,"logger":"http.log.error","msg":"no upstreams available","request":{"remote_addr":"10.0.0.151:64500","proto":"HTTP/2.0","method":"GET","host":"firefox.a.b.domain.tld","uri":"/favicon.ico","headers":{"Accept":["image/webp,*/*"],"Accept-Encoding":["gzip, deflate, br"],"Referer":["https://firefox.d.h.superion.no/"],"Sec-Fetch-Mode":["no-cors"],"Te":["trailers"],"Pragma":["no-cache"],"Cache-Control":["no-cache"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0"],"Accept-Language":["en-GB,en;q=0.5"],"Dnt":["1"],"Cookie":["_delighted_web={%22FutSOUgy5edCcTk9%22:{%22_delighted_fst%22:{%22t%22:%221626010103915%22}}}"],"Sec-Fetch-Dest":["image"],"Sec-Fetch-Site":["same-origin"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"firefox.d.h.superion.no"}},"duration":0.000181407,"status":502,"err_id":"1c5ankhqm","err_trace":"reverseproxy.statusError (reverseproxy.go:857)"}
```

I did not have to this with Traefik. The VPN docker was on the Traefik network (no other traefik settings there), and then I set all the other traefik config label on the firefox docker image and used `network_mode: container:vpn-client`.

i.e vpn-client docker-compose had:
```
networks:
  - traefik
```

Firefox docker-compose had:
```
network_mode: "container:vpn-client"
```

both had:
```
networks:
  traefik
    external: true
```

Traefik do have a flag `traefik.docker.network` that I had. Not sure if that sort of works in addition to the `network_mode` and make it all work.

```
labels:
  traefik.port=5800
  traefik.frontend.rule=Host:firefox.d.h.superion.no"
  traefik.docker.network=traefik
```

**Comment by NoLooseEnds** [comment]
Thanks for the reply. 

I'm not an expert at all, but afaik the advantage of `network_mode: container:<name>` is that you can have one container (i.e a vpn-client) where you can route specific docker images through, regardless if they are in the same docker-compose or not.

I tested setting the following earlier, but no go. If that would work, I could live with that solution, even if the best solution would be to set all caddy settings it in their respective docker-compose files.

I tried this:
```
version: '3.7'

services:
  vpn-client:
    container_name: vpn-client
    image: ghcr.io/bubuntux/nordvpn
    init: true
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      - caddy
    environment:
      TZ: '${TZ}'
      USER: '${NORDUSER}'
      PASS: '${NORDPASS}'
      CONNECT: no200
      TECHNOLOGY: NordLynx
      NETWORK: '${NETWORK}'
    ports:
      - 5800:5800 #firefox (this should not be necessary, but I did it anyway)
    labels:
      caddy.firefox_0: firefox.a.b.domain.tld
      caddy.firefox_0.reverse_proxy: "{{firefox 5800}}" #trying with the docker container name. I guess {{upstream}} would not work here.

networks:
  caddy:
    external: true
```

Caddy log:
```
{"level":"error","ts":1626116264.950673,"logger":"http.log.error","msg":"no upstreams available","request":{"remote_addr":"10.0.0.151:64500","proto":"HTTP/2.0","method":"GET","host":"firefox.a.b.domain.tld","uri":"/favicon.ico","headers":{"Accept":["image/webp,*/*"],"Accept-Encoding":["gzip, deflate, br"],"Referer":["https://firefox.d.h.superion.no/"],"Sec-Fetch-Mode":["no-cors"],"Te":["trailers"],"Pragma":["no-cache"],"Cache-Control":["no-cache"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0"],"Accept-Language":["en-GB,en;q=0.5"],"Dnt":["1"],"Cookie":["_delighted_web={%22FutSOUgy5edCcTk9%22:{%22_delighted_fst%22:{%22t%22:%221626010103915%22}}}"],"Sec-Fetch-Dest":["image"],"Sec-Fetch-Site":["same-origin"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"firefox.a.b.domain.tld"}},"duration":0.000181407,"status":502,"err_id":"1c5ankhqm","err_trace":"reverseproxy.statusError (reverseproxy.go:857)"}
```

I did not have to this with Traefik. The VPN docker was on the Traefik network (no other traefik settings there), and then I set all the other traefik config label on the firefox docker image and used `network_mode: container:vpn-client`.

i.e vpn-client docker-compose had:
```
networks:
  - traefik
```

Firefox docker-compose had:
```
network_mode: "container:vpn-client"
```

both had:
```
networks:
  traefik
    external: true
```

Traefik do have a flag `traefik.docker.network` that I had. Not sure if that sort of works in addition to the `network_mode` and make it all work.

```
labels:
  traefik.port=5800
  traefik.frontend.rule=Host:firefox.a.b.domain.tld"
  traefik.docker.network=traefik
```

**Comment by lucaslorentz** [comment]
I did some tests without VPN and it's working well:

Create docker-compose.yaml file:
```
version: '3.7'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  vpn-client:
    image: nginx
    networks:
      - caddy
    labels:
      caddy: whoami0.example.com
      caddy.reverse_proxy: "{{upstreams 8000}}"
      caddy.tls: "internal"

  whoami0:
    network_mode: "service:vpn-client"
    image: jwilder/whoami
    depends_on:
      - test

networks:
  caddy:
```

Then:
```
docker compose up
```

Test with:
```
curl -k --resolve whoami0.example.com:443:127.0.0.1 https://whoami0.example.com
```

But I couldn't get it working with docker swarm stacks, it seems that network_mode is ignored by docker swarm.
