### ISSUE TITLE
Proxy to host

### ISSUE THREAD

**Issue by thechubbypanda** [lucaslorentz/caddy-docker-proxy#278]
I have cockpit running on my host machine and I want to be able to access the web interface through the caddy-docker-proxy.
Is there a way to do this through the docker-compose file or perhaps a dummy container?

**Comment by francislavoie** [comment]
There's not really enough detail here. What's your existing docker-compose setup, what requests are you expecting to work, etc?

You can put labels on the `caddy-docker-proxy` service itself for things that aren't specifically for any other container. Ultimately, labels just generate Caddyfile config.

**Comment by thechubbypanda** [comment]
I've made some slight progress, hopefully this shines some light on what I'm trying to do:

caddy compose:
```
...
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      caddy: server.example.com
      caddy.reverse_proxy: "host.docker.internal:9090"
...
```

The above gets me close, I can even access the site but once I log into cockpit it gives me a connection failure and the log shows:
`cockpit-tls: gnutls_handshake failed: A TLS fatal alert has been received.`
