### ISSUE TITLE
Cannot create new site

### ISSUE THREAD

**Issue by Quin452** [lucaslorentz/caddy-docker-proxy#279]
Now, I may be completely stupid here, but how can I create a new site using this?

I can get the whoami working just fine, but I have no idea what to do to access any other container.

**Comment by francislavoie** [comment]
Not enough information here to help you. What are you actually trying to do? Please be specific.

**Comment by Quin452** [comment]
Okay, I'll be more specific.

I create a new directory, wordpress, which sites alongside caddy and whoami.  Inside of the wordpress directory there is a wordpress docker-compose.yml.  This has just a bog-standard wordpress image, a quick test to see how things work.
Inside this the caddy network details and labels are all in place, just like with whoami.  I've tested it out with port 8000, 8080, 4000, 80, 443, and each time  it loads a white screen and nothing else.

**Comment by francislavoie** [comment]
> I don't know why you've decided to close this straight away.

I closed it because there's nothing actionable, because it's a question. There's no harm in closed issues, they're still open for discussion. But there's nothing that the project needs to change in code, so there's no point keeping it open.

>  Inside this the caddy network details and labels are all in place, just like with whoami. I've tested it out with port 8000, 8080, 4000, 80, 443, and each time it loads a white screen and nothing else.

Please post your actual `docker-compose.yml` etc. I can't really help without actually seeing what you have and whether you made a mistake. Please provide _as much information as possible_.

**Comment by Quin452** [comment]
```
block code
```

**Comment by francislavoie** [comment]
`caddy.reverse_proxy: "{{upstreams 4000}}"` Where are you getting port `4000` from? Is that the port you configured wordpress to listen on? If you're just using the defaults, you probably wanted `{{upstreams 80}}`.

Check the logs on the Caddy container with `docker logs` to see what it's reporting.

**Comment by Quin452** [comment]
Port 4000 was just something I copied over from whoami; I tested out a lot of different numbers, 80 and 443 included, but it wouldn't work.
However, I deleted the containers and volumes, and that seems to have done the trick now.  Thanks for the input.

**Comment by Quin452** [comment]
Just an update on this, how can I expose (not sure if it's the right word here) other ports?

Sure, I can get port 80 for WordPress, but running docker container ls shows only 80.  What about 443?  And there is no label/upstream for the database, but 3306 is listed in docker container ls.

And what about for other services/containers that may also need 80/443 or even 22?

**Comment by francislavoie** [comment]
The `expose:` option tells Docker the ports on which you plan to accept connections from _other_ containers.

The `ports:` option tells Docker to make a port mapping from the container to the host machine, to accept connections from outside Docker.

You should use `ports:` for Caddy to map ports 80 and 443, and use `expose:` for everything else that you plan to have Caddy proxy to.

**Comment by Quin452** [comment]
Okay, perhaps you could point me in the right direction.

I've got 3 docker compose files (technically 4 if I was to use whoami).
These are all separate out into their own directories, like the "guide" suggests.

The issue I am having is with Enclave.  I can get this to work with socat, both on the server and in a container, but I am having issues with it working with Caddy.
Now, I need to include the ports for Enclave (as below) which come into effect with Caddy, but I am unsure how (docker ps with socat shows 80:80 and 443:443, but it seems this isn't the way with Caddy).  I tried with upstreams, but that didn't make a difference.

Caddy
```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
```

WordPress, as previous, but with upstreams 80.

Enclave (tunneling service)
```
version: '3.1'

services:
  enclave-fabric:
    container_name: fabric
    image: enclavenetworks/enclave:latest
    restart: always

    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      ENCLAVE_ENROLMENT_KEY: [copied from their portal]
    volumes:
      - enclave-config:/etc/enclave/profiles
      - enclave-logs:/var/log/enclave
    labels:
      caddy: enclave.classicniall.co.uk
      caddy.reverse_proxy: "{{upstreams}}"
    networks:
      - caddy
# only for socat
#    ports:
#      - "80:80"
#      - "443:443"

volumes:
  enclave-config:
  enclave-logs:

networks:
  caddy:
    external: true
```
