### ISSUE TITLE
Question: Does caddy controller deployment

### ISSUE THREAD

**Issue by josephlim75** [lucaslorentz/caddy-docker-proxy#285]
If I'm deploying the distributed version of caddy docker proxy in a swarm cluster comprising of 6 nodes (3 managers, 3 workers), does caddy_controller service needs to be deployed globally per node OR it just need 1 replica ?

**Comment by heapdavid** [comment]
You only need 1 replica of the controller, but as it's accessing the docker socket it would need to be deployed to manager nodes like this:

```
    deploy:
      placement:
        constraints:
          - "node.role == manager"
```
