### ISSUE TITLE
Can I use the network name instead of IP range to define controller network?

### ISSUE THREAD

**Issue by heapdavid** [lucaslorentz/caddy-docker-proxy#286]
Rather than reserve a specific network range i think it would be much more straightforward to be able to configure the caddy controller something like this:

```
      - CADDY_CONTROLLER_NETWORK_NAME=caddy-controller
...
networks:
    caddy-controller:
        internal: true
```
Is this possible? It should then be able to figure out the range automatically.

**Comment by lucaslorentz** [comment]
CADDY_CONTROLLER_NETWORK only needs to be defined when executing separate "controller" and "server".

The "controller" part connects to docker API and it could use it to find the network IP ranges for a specific docker network name. We could create a CADDY_CONTROLLER_NETWORK_NAME that works on the controller side.

But the "server" part is meant to not depend on docker API, therefore docker network name is not very useful here. It needs the IP ranges in order to allow traffic only from that range. We can't use CADDY_CONTROLLER_NETWORK_NAME here, but we could allow traffic from any IP range if that doesn't concern you.

**Comment by heapdavid** [comment]
Hi,

Thanks for getting back to me - this is for a stack with a separate controller and 3 servers.

The controller is only connected to the `caddy-controller` network, and therefore isn't using the `CADDY_CONTROLLER_NETWORK` variable.

The servers are connected to the ingress network and the `caddy-controller` network.

We have an overall /17 network which is assigned to docker, so all connections would be from that range, but when I use that on the servers like this:

```
 - CADDY_CONTROLLER_NETWORK=172.x.x.0/17
 
 ...
 networks:
    caddy-controller:
        internal: true
```
...I get `connection refused` in the logs.

Does the CIDR range in the `CADDY_CONTROLLER_NETWORK` variable need to be the same (i.e. a /24) as the network? Or is it just a whitelist that should allow anything in the /17 to connect if specified?
