### ISSUE TITLE
looking up info for HTTP challenge

### ISSUE THREAD

**Issue by 0x4139** [lucaslorentz/caddy-docker-proxy#287]
I seem to get this kind of info into the logs 

`{"level":"error","ts":1629708967.7232833,"logger":"tls.issuance.acme","msg":"looking up info for HTTP challenge","host":"subdomain.domain-staging.com","error":"no information found to solve challenge for identifier: subdomain.domain-staging.com"}`

my caddy configuration is:

```yaml  stats:
    image: myregistry.com:myimage:mytag
    container_name: stats
    restart: always
    labels:
      caddy_0: stats.domain-dev.com
      caddy_0.reverse_proxy: "{{upstreams 3000}}"
      caddy_1: stats.domain-staging.com
      caddy_1.reverse_proxy: "{{upstreams 3000}}"
```

it seems that for some domains in the same config it's generating the certificates without any issue, but it seems that i still get these errors
