### ISSUE TITLE
issues with network option, can't find container when autogenerated

### ISSUE THREAD

**Issue by masterkain** [lucaslorentz/caddy-docker-proxy#290]
hello,
I'm trying to replace my local docker-compose (caddy-gen) ssl stack with this, I've run into a problem.

```yaml

version: "3.9"

services:
  dashboard:
    restart: "always"
    labels:
      caddy: app-dev.my-domain.com
      caddy.reverse_proxy: "{{upstreams 3000}}"
      caddy.tls.dns: "cloudflare xxxxx"
    environment:
      - NODE_ENV=development
    build: ./dashboard
    volumes:
      - ./dashboard:/usr/src/app:delegated
    networks:
      - myapp    

  caddy:
    build: ./caddy
    labels:
      caddy.acme_ca: https://acme.zerossl.com/v2/DV90
      caddy.email: kain@mydomain.com
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=myapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    networks:
      - myapp

networks:
  myapp:
    # external: true
```

if I enable `external: true` and create the network before running the stack, everything seems fine.
however if I start blank, remove the `external: true` directive (so compose automatically creates the network) I get 502 errors because the destination containers cannot be found:

```
"msg":"Container is not in same network as caddy","container":"be4440e6aaae01cf25144d3b7578c2344e32ea469445129717f618f4c1cbc42f","container id":"be4440e6aaae01cf25144d3b7578c2344e32ea469445129717f618f4c1cbc42f"}
```

I'd really like it to work so I can share my work with colleagues without asking them to create the network manually before running the stack. Is that possible?
