### ISSUE TITLE
Http error 502 using replicas

### ISSUE THREAD

**Issue by kidcuauh** [lucaslorentz/caddy-docker-proxy#293]
Reverse proxy works good avoiding replicas.
It's a frontend Vuetify app docker service running under _caddy:2.4.3-alpine_
The reverse proxy is running latest stable _lucaslorentz/caddy-docker-proxy:2.3.5-alpine_

**vuetify.yaml with 2 replicas:**
```
version: '3.7'
services:
  app:
    image: vuetify:master
    networks:
      - web
    deploy:
      labels:
        - caddy_0=test.domain.com
        - caddy_0.reverse_proxy="{{upstreams 80}}"
        - caddy_0.tls=cuau@domain.com
        - caddy_0.tls.on_demand=
      replicas: 2
      restart_policy:
        condition: any
networks:
  web:
    external:
      name: web
```

**Log reverse-proxy:**
```
2021/08/31 17:45:30 [INFO] Skipping default Caddyfile because no path is set
2021/08/31 17:45:30 [INFO] New Caddyfile:
test.domain.com {
        reverse_proxy "10.0.3.15:80 10.0.3.18:80"
        tls cuau@domain.com {
                on_demand
        }
}
```

**Error log:**
```
{"level":"error","ts":1630431969.4226747,"logger":"http.log.error","msg":"dial tcp: lookup 10.0.3.15:80 10.0.3.18:80: no such host","request":{"remote_addr":"10.0.0.2:2708","proto":"HTTP/2.0","method":"GET","host":"test.domain.com","uri":"/","headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Sec-Fetch-User":["?1"],"Sec-Ch-Ua":["\"Chromium\";v=\"92\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"92\""],"Sec-Ch-Ua-Mobile":["?0"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Cache-Control":["max-age=0"],"Sec-Fetch-Site":["none"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Dest":["document"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"test.domain.com"}},"duration":0.001490715,"status":502,"err_id":"r0rwi936a","err_trace":"reverseproxy.statusError (reverseproxy.go:852)"}
```
