### ISSUE TITLE
Simpler way to redirect www to non-www?

### ISSUE THREAD

**Issue by flayks** [lucaslorentz/caddy-docker-proxy#294]
I figured that I could redirect the www. of my domain to the non-www domain with this code:

```yaml
labels:
  caddy_0: site.tld
  caddy_0.reverse_proxy: "app:3000"
  caddy_1: www.site.tld
  caddy_1.redir: "https://site.tld{uri} permanent"
```

Is it possible to make this redirection smoother and avoid repeating the domain? I'm new to Caddy but can clearly see how powerful and convenient it can be compared to Nginx (which gives me headaches haha)

I saw the [@match parameter in the readme](https://github.com/lucaslorentz/caddy-docker-proxy#sites-snippets-and-global-options) but I'm not totally sure how to use in with the host.

**Comment by francislavoie** [comment]
Nope, that's pretty much the way to do it. Caddy needs both domains explicitly listed in the config to issue certificates for both domains, so the repetition of the domain is necessary. See in the docs, the representative example of what you're doing: https://caddyserver.com/docs/caddyfile/patterns#redirect-www-subdomain

You could use an environment variable or something like `{$DOMAIN}` to avoid duplication (which could be replaced at Caddyfile-adapt time when the Caddyfile is turned into a JSON config, which Caddy actually runs with)

**Comment by flayks** [comment]
Oh well if I can use a env variable that would be good.

Is something like this possible then? Or am I making it weird? 🙈

```yaml
environment:
  DOMAIN: site.tld
labels:
  caddy_0: {$DOMAIN}
  caddy_0.reverse_proxy: "app:3000"
  caddy_1: www.{$DOMAIN}
  caddy_1.redir: "https://{$DOMAIN}{uri} permanent"
```
