### ISSUE TITLE
Question: Infinite logger info

### ISSUE THREAD

**Issue by blazekjan** [lucaslorentz/caddy-docker-proxy#298]
Hello, 
sorry to bother you this way, but is there any way how to get rid of this infinite logging info which repeats like every 5 seconds or so?
```
{"level":"info","ts":1633207102.2502303,"logger":"docker-proxy","msg":"Skipping default Caddyfile because no path is set"}
{"level":"info","ts":1633207102.2502704,"logger":"docker-proxy","msg":"Skipping swarm config caddyfiles because swarm is not available"}
{"level":"info","ts":1633207102.2517693,"logger":"docker-proxy","msg":"Skipping swarm services because swarm is not available"}
```
My docker compose:
```
version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy-docker-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    networks:
      - caddy

volumes:
  caddy_data: {}

networks:
  caddy:
    external: true
```
Found #102 and also the note:

> Note: This is for Docker Swarm only. Alternativly, use CADDY_DOCKER_CADDYFILE_PATH or -caddyfile-path

I just cant figure out what to do.. set - CADDY_DOCKER_CADDYFILE_PATH=? what path? Create some Caddyfile? I dont use Docker Swarm at all.

Edit: 
Found an issue #289, so I suppose I cant do anything with this.

According to @francislavoie suggestion - it really doesnt work:

```
caddy.log: ""
caddy.log.exclude: docker-proxy
caddy.log: docker-proxy
caddy.log.include: docker-proxy
caddy.log.level: WARN
```
Output:
```
{"level":"info","ts":1633780343.5569098,"logger":"docker-proxy","msg":"Sending configuration to","server":"localhost"}
{"level":"info","ts":1633780343.5604293,"logger":"admin.api","msg":"received request","method":"POST","host":"localhost:2019","uri":"/load","remote_addr":"127.0.0.1:58056","headers":{"Accept-Encoding":["gzip"],"Content-Length": ["736"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}                                                                                                                                                      {"level":"error","ts":1633780343.5607913,"logger":"admin.api","msg":"request error","error":"loading config: loading new config: setting up custom log 'docker-proxy': include and exclude must not intersect, but found docker-proxy in both lists","status_code":400}
{"level":"error","ts":1633780343.5608947,"logger":"docker-proxy","msg":"Error response from server","server":"localhost","status code":400,"body":"{\"error\":\"loading config: loading new config: setting up custom log 'docker-proxy': include and exclude must not intersect, but found docker-proxy in both lists\"}\n"}
```
I will just leave it emmiting these logs.
