### ISSUE TITLE
Reverse proxy and mime types ...

### ISSUE THREAD

**Issue by spock64** [lucaslorentz/caddy-docker-proxy#300]
Hi, I'm having trouble getting a reverse proxy to work. The simple test service being proxied is a combination of a backend api and a server for the front end. Everything works, except that the mime type headers are not being set correctly ... The same service being hit without the proxy works properly.

I tried to get into the caddy container (the alpine one) to diagnose the problem, but could not get a shell ...

So, here's the labels from my docker-compose ...

```
labels:
  caddy: x.local
  caddy.handle_path: /x*
  caddy.handle_path.0_reverse_proxy: "{{upstreams 5000}}"
```

Should this configuration "just work"? I understand from reading around that caddy would need to have mailcap installed to be able to sniff the mime types - but is there a way to simply pass the headers through from the internal service?
