### ISSUE TITLE
Routing 2 ports from same container to 2 different subdomains

### ISSUE THREAD

**Issue by arminus** [lucaslorentz/caddy-docker-proxy#308]
Is it possible to route 2 ports from the same container to 2 different subdomains (e.g. for Neo4J) ?

I've seen [this issue](https://github.com/lucaslorentz/caddy-docker-proxy/issues/117), so it seems to be possible, unfortunately, the [link to the docs](https://github.com/lucaslorentz/caddy-docker-proxy#multiple-caddyfile-sections-from-one-servicecontainer) doesn't work anymore...

Commenting the ports section below and just adding 2 last 2 lines doesn't work (SSL internal error).

```
neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./data/neo4j:/data
    ports:
#      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
    networks:
      - caddy
    labels:
      caddy: neo4j.mbse2dl.local
      caddy.reverse_proxy: "{{upstreams 7474}}"
#      caddy: neo4j-bolt.mbse2dl.local
#      caddy.reverse_proxy: "{{upstreams 7687}}"
```

**Comment by lucaslorentz** [comment]
Sure, try:
```
neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./data/neo4j:/data
    ports:
#      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: none
    networks:
      - caddy
    labels:
      caddy_0: neo4j.mbse2dl.local
      caddy_0.reverse_proxy: "{{upstreams 7474}}"
      caddy_1: neo4j-bolt.mbse2dl.local
      caddy_1.reverse_proxy: "{{upstreams 7687}}"
```
