### ISSUE TITLE
Proxying websocket connections

### ISSUE THREAD

**Issue by arminus** [lucaslorentz/caddy-docker-proxy#311]
How do I specify a proxy for a websocket connection? From looking at [this](https://caddy.community/t/caddy-v2-how-to-proxy-websoket-v2ray-websocket-tls/7040/13), 

```
@websockets {
	header Connection *Upgrade*
	header Upgrade websocket
}
reverse_proxy @websockets localhost:6001
````

it seems that Caddy supports this, but I have no clue how to add the required labels for caddy-docker-proxy. My usecase is a Neo4J proxy as outlined [here](https://github.com/lucaslorentz/caddy-docker-proxy/issues/308). 

```
neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - ./data/neo4j:/data
    environment:
      NEO4J_AUTH: none
    networks:
      - caddy
    labels:
      caddy_0: neo4j.mbse2dl.local
      caddy_0.reverse_proxy: {{upstreams 7474}}
      caddy_1: neo4j-bolt.mbse2dl.local
      caddy_1.reverse_proxy: {{upstreams 7687}}
```

Using that configuration, I get an error in the browser: Cannot connect to wss://neo4j-bolt.mbse2dl.local/ - so obviously something is missing.

**Comment by arminus** [comment]
Ok, after an RTFM I'm one step further with this set of labels:

```
    labels:
      caddy_0: neo4j.mbse2dl.local
      caddy_0.reverse_proxy: "{{upstreams 7474}}"
      caddy_1: neo4j-bolt.mbse2dl.local
      caddy_1.@ws.0_header: "Connection *Upgrade*"
      caddy_1.@ws.1_header: "Upgrade websocket"
      caddy_1.reverse_proxy: "@ws {{upstreams 7687}}"
```

This allows me to apparently connect to wss://neo4j-bolt.mbse2dl.local with Postman - but it's still failing when trying to connect from the Neo4J browser (where I need to append a :443 to the URL, otherwise it defaults to 7687). Either way, it doesn't connect.

Could I be missing something in the above label definition?

**Comment by francislavoie** [comment]
The request matchers won't actually do anything useful for you in this case, because the hostname is already the matcher that will disambiguate websocket requests from non-websocket ones.

Turn on the `debug` global option in Caddy, and take a look at the logs when making a request. Do you see any additional information in there?

**Comment by arminus** [comment]
Ok, thanks, that was a good hint, turns out that there is an issue with the self-signed certificate in my local environment - in a "normal" browser page, I can add an exception for these certs, but I have no idea how to add that for the websocket connection yet.

The above labels do work when I deploy this on a public host with a "real certificate".

I don't quite understand your comment "The request matchers won't actually do anything useful", though?

**Comment by francislavoie** [comment]
> I don't quite understand your comment "The request matchers won't actually do anything useful", though?

Basically, they're a no-op. They won't prevent or allow any relevant requests from making it through, anymore than just having the host matcher like you had in your first comment.

The point of request matchers is to make a conditional routing decision. In this case, that condition is useless. It's essentially like having code like this:

```
if hostname == "neo4j.mbse2dl.local" {
	reverse_proxy {{upstreams 7474}}
}

if hostname == "neo4j-bolt.mbse2dl.local" {
	if true {
		reverse_proxy {{upstreams 7687}}
	}
}
```

Because the matcher will _always_ be true for websocket connections.

**Comment by arminus** [comment]
Sorry, I still don't understand your last.

I took the example from "Proxying all websocket requests" form the README and adapted it. If the redundant matcher you mean are the "caddy_1.@ws." header lines, I can't remove them, i.e. the connection no longer woks if those lines are not present. Otherwise I don't see what else might be redundant in the labels in order to map 2 different ports to two different subdomains...

**Comment by francislavoie** [comment]
These are identical in behaviour:

```
    labels:
      caddy_0: neo4j.mbse2dl.local
      caddy_0.reverse_proxy: "{{upstreams 7474}}"
      caddy_1: neo4j-bolt.mbse2dl.local
      caddy_1.@ws.0_header: "Connection *Upgrade*"
      caddy_1.@ws.1_header: "Upgrade websocket"
      caddy_1.reverse_proxy: "@ws {{upstreams 7687}}"
```

```
    labels:
      caddy_0: neo4j.mbse2dl.local
      caddy_0.reverse_proxy: "{{upstreams 7474}}"
      caddy_1: neo4j-bolt.mbse2dl.local
      caddy_1.reverse_proxy: "{{upstreams 7687}}"
```

That request matcher does nothing to affect the connection/request. It just means "if the request is a websocket". Since the only thing ever making requests to that domain will be websockets, it's redundant, because that condition would always be true.

I'm not sure how else to make this clear :thinking: request matchers are _just_ conditions, they have no behaviour on their own (generally -- some have side effects like regexp matchers writing some state information for later use, but that's not relevant here).
