### ISSUE TITLE
Providing manual certificates -> [ERROR]  Removing invalid block: Caddyfile:2: unrecognized global option: tls

### ISSUE THREAD

**Issue by arminus** [lucaslorentz/caddy-docker-proxy#312]
So I have a couple of services with the following labels:
```
    labels:
      caddy.tls: /conf/certs/mbse2dl.local.crt /conf/certs/mbse2dl.local.key
```
(the certs are identical wildcard certs for the respective subdomains/services and I want to configure that every one of these services uses the same wildcard certificate).

The Caddy container mounts volumes: - ./conf/certs:/conf/certs and doesn't set caddy.tls. Basically everything works as expected, except that I see this error in the caddy container log:

```
{"level":"info","ts":1636384800.9147592,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: Caddyfile:2: unrecognized global option: tls\n{\n\ttls /conf/certs/mbse2dl.local.crt /conf/certs/mbse2dl.local.key\n}\n\n"}
```

So I assume I'm again configuring something in the wrong way even though Caddy seems to handle this gracefully?

**Comment by francislavoie** [comment]
See the docs: https://github.com/lucaslorentz/caddy-docker-proxy#sites-snippets-and-global-options

`tls` is a _directive_, not a global option, so it needs to go in a site block.

**Comment by arminus** [comment]
I have this in 2 matching site blocks, according to my understanding, here's the full label set:

first compose file:

```
services:
  mbse2dl-frontend:
    labels:
      caddy: www.${SERVER_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 8080}}"
```

second compose file (which optionally extends the first):

```
  mbse2dl-frontend:
    labels:
      caddy.tls /conf/certs/mbse2dl.local.crt /conf/certs/mbse2dl.local.key
````

then I start the stack with -f first compose -f second compose

caddy.tls is not set anywhere else.

Could that be the reason?

**Comment by francislavoie** [comment]
The labels from the two `docker-compose` don't get merged that way, I think. Or if it does, it probably put the labels from your included one first, which breaks it. I'm not sure what to suggest, I very rarely use multiple `docker-compose` files.

**Comment by arminus** [comment]
Well, as I said, "it nevertheless works", i.e. it seems to generate a working caddy config - I was just wondering about the error message.

**Comment by francislavoie** [comment]
The error message means it tried to generate an invalid config. If there's an invalid config, then `caddy-docker-proxy` will just continue running with the _last valid config_. So if you had one that worked before you made those changes, then it'll _still_ work.

**Comment by arminus** [comment]
If that last valid config is picked up form the directory which is mounted as /data
```
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/caddy:/data
```
then no? I just deleted that folder, restarted the stack and see the same error, but the certs are nevertheless loaded ok.

Given what you said above, I can however avoid the error message if I duplicate the caddy: labels into the 2nd compose file like so:

```
services:
  mbse2dl-frontend:
    labels:
      caddy: www.${SERVER_DOMAIN}
      caddy.tls /conf/certs/mbse2dl.local.crt /conf/certs/mbse2dl.local.key
```

**Comment by lucaslorentz** [comment]
It is indeed possible to split the same site config into multiple services and therefore multiple compose files as well.
That feature allows you to configure hosting of `yourdomain.com/folder1` in one service, and `yourdomain.com/folder2` in another service.

But the labels are converted to Caddyfile per service, and then Caddyfiles are merged.

The with your config is that your second label declaration is creating a global option because it doesn't have the site definition. Try changing the second block to:
```
services:
  mbse2dl-frontend:
    labels:
      caddy: www.${SERVER_DOMAIN}
      caddy.tls /conf/certs/mbse2dl.local.crt /conf/certs/mbse2dl.local.key
```

That generates 2 Caddyfiles:
```
www.${SERVER_DOMAIN} {
  reverse_proxy {{upstreams 8080}}
}
```
```
www.${SERVER_DOMAIN} {
  tls /conf/certs/mbse2dl.local.crt /conf/certs/mbse2dl.local.key
}
```

Which should get merged into:
```
www.${SERVER_DOMAIN} {
  reverse_proxy {{upstreams 8080}}
  tls /conf/certs/mbse2dl.local.crt /conf/certs/mbse2dl.local.key
}
```
