### ISSUE TITLE
No email label in the example for LE?

### ISSUE THREAD

**Issue by C-Fu** [lucaslorentz/caddy-docker-proxy#315]
Correct me if I'm wrong, but doesn't LE require you to provide your email to generate the https/tls/cert?

I'm referring to this example in the main page of this repo

```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}

```
shouldn't there be something like 
```
    networks:
      - caddy
    labels:
      - caddy.email: your@email.com
    volumes:
```
