### ISSUE TITLE
How do I rewrite/redirect an url while keeping the parameters?

### ISSUE THREAD

**Issue by Drillan767** [lucaslorentz/caddy-docker-proxy#322]
Hello,

I'd like to do a simple thing, to be able to redirect a user from `mydomain.net/redirect.html?demo60` to `mydomain.net/redirect/demo60`, but I'm struggling more than expected.

So far, here is how my service looks in my docker-compose.yml file:

```
services:
  front:
    labels:
      caddy: www.idupatrimoine.fr, idupatrimoine.fr
      caddy.rewrite_0: /redirect.html* /redirect/{uri}
      caddy.redir: /redirect.html /redirect/{uri} 302
      caddy.reverse_proxy: "{{upstreams 3010}}"

```

My goal is to "create" /redirect/ from /redirect.html, then redirect any visitor to it. However, with such configuration, the visitors are redirected to `mydomain.net/redirect//redirect.html?demo60`

I also tried to replace the following:

```
caddy.redir: /redirect.html /redirect/{uri} 302
```
with 
```
caddy.redir: /redirect.html /redirect/
```

but I get redirected to `mydomain.net/redirect/`, and I loose the `demo60` part in the url.

What would be the correct syntax for this?

Thank you in advance!
