### ISSUE TITLE
Cannot reverse proxy caddy container

### ISSUE THREAD

**Issue by nsetyo** [lucaslorentz/caddy-docker-proxy#326]
I want to reverse proxy caddy container with Caddy file like this

```
{$SERVER_NAME}, localhost {
    root * /var/www

    file_server
}
```
but i got error

```
{"level":"error","ts":1640751787.4029744,"logger":"http.log.error","msg":"remote error: tls: internal error","request":{"remote_addr":"172.21.0.1:42790","proto":"HTTP/2.0","method":"GET","host":"caddy.skeleton.localhost","uri":"/","headers":{"Accept-Encoding":["gzip, deflate, br"],"Dnt":["1"],"Sec-Fetch-User":["?1"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Accept-Language":["en-US,en;q=0.5"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["none"],"Cache-Control":["max-age=0"],"Te":["trailers"],"User-Agent":["Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"],"Upgrade-Insecure-Requests":["1"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"caddy.skeleton.localhost"}},"duration":0.001087076,"status":502,"err_id":"uru00brw5","err_trace":"reverseproxy.statusError (reverseproxy.go:858)"}
```

And when I change my Caddyfile to:
```
{$SERVER_NAME}, 172.21.0.7, localhost {
    root * /var/www

    file_server
}
```
It works, but `172.21.0.7` is dynamic docker container ip and i prefer to make it dynamic. How to fix this?

**Comment by francislavoie** [comment]
You can just use `:80` as the site address to accept any requests on port 80, ignoring the hostname

**Comment by nsetyo** [comment]
With
```
:80, :443 {
    root * /var/www

    file_server
}
```
I still got
```
{"level":"error","ts":1640752254.4973998,"logger":"http.log.error","msg":"remote error: tls: internal error","request":{"remote_addr":"172.21.0.1:42794","proto":"HTTP/2.0","method":"GET","host":"caddy.skeleton.localhost","uri":"/","headers":{"User-Agent":["Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Accept-Language":["en-US,en;q=0.5"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Site":["none"],"Sec-Fetch-User":["?1"],"Accept-Encoding":["gzip, deflate, br"],"Dnt":["1"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Cache-Control":["max-age=0"],"Te":["trailers"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"caddy.skeleton.localhost"}},"duration":0.002072395,"status":502,"err_id":"7zajgh95q","err_trace":"reverseproxy.statusError (reverseproxy.go:858)"}
```

My docker-compose
```
labels:
      caddy: caddy.${COMPOSE_PROJECT_NAME}.localhost
      caddy.respond: /_info "{{upstreams https}}"
      caddy.reverse_proxy: "{{upstreams https}}"
      caddy.reverse_proxy.header_up: Host {upstream_hostport}
      caddy.reverse_proxy.header_up: X-Forwarded-Host {host}
      caddy.reverse_proxy.transport: http
      caddy.reverse_proxy.transport.tls_insecure_skip_verify:
```
