### ISSUE TITLE
Caddy redirects traffic to gateway

### ISSUE THREAD

**Issue by hyenabyte** [lucaslorentz/caddy-docker-proxy#336]
Hi

I'm having a weird problem, all traffic seems to be redirected to my network gateway.
I.e. if I create a service with a domain, let's say test.com, if I then go to test.com it resolves to my router admin interface, and if I create a service and assign it a subdomain, the page won't load and in Firefox it tells me 'The page isn't redirecting properly', and if I use curl it gives following error:
```
curl: (47) Maximum (50) redirects followed
```

I first encountered this problem on a new server I set up, which had me debugging all sorts of problems with port forwarding and my new router. However I just changed the config on a server already running in another location (with another router and ISP) which now has the same problem, which leads me to believe the problem is coming from the reverse proxy.

I have tested with the `jwilder/whoami` image, and exposing port `8000` as `80` and then going to the domain pointing to my server, resolves the service, albeit without https, which eliminates pretty much everything other than the caddy reverse proxy. 
I then tested with a brand new docker-compose setup with the example provided in the readme, to see if it was because I build my own caddy image with cloudlfare ssl support, but even the default image with internal tls seems to do this.

Here is my compose file (with domain swapped for an example one)
```
version: '3.7'

networks:
    caddy:
        external: true

volumes:
    caddy_data: {}

services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        networks:
            - caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - caddy_data:/data
        restart: unless-stopped

    whoami:
        container_name: whoami
        image: jwilder/whoami
        networks:
            - caddy
        # ports:
        #     - 80:8000
        labels:
            caddy: mydomain.xyz
            caddy.reverse_proxy: '{{ upstreams 8000 }}'
            caddy.tls: 'internal'
```

So my best bet now is that there could be some kind of bug in the reverse proxy, or that using cloudlfare as dns provider causes some kind of emergent behavior, but then again it has been working flawlessly up until recently. I Have yet to test with other dns providers, so I will update when I do.

Thank you for reading
