### ISSUE TITLE
[Q] Redir path + External IP support?

### ISSUE THREAD

**Issue by soakes** [lucaslorentz/caddy-docker-proxy#34]
Hi Guys,

I am having a bit of a problem trying to convert the following:

```
  # Backend (ghost)
  proxy /blog example_blog:2368 {
    transparent
    websocket
  }

  redir 302 {
    if {path} is /
    / /blog
  }
```

I have tried multiple variations of below but I still seem to be failing on cracking it.  Does anyone know what I am doing wrong?

```
    deploy:
      labels:
        caddy.address: example.me.uk/blog
        caddy.targetport: 2368
        caddy.proxy.websocket:
        caddy.proxy.transparent:
        caddy.redir: 302
        caddy.redir: if {path} is /
        caddy.redir: / /blog
```

The other one I am still struggling with is when you have an external (non docker) reverse proxy config like:

```
  # Backend (vmware)
  proxy / https://172.19.255.110 {
    insecure_skip_verify
    transparent
    websocket
  }
```

How can this also be converted? what am I missing from the examples?

Kind Regards
