### ISSUE TITLE
Question: How to add CORS headers to response

### ISSUE THREAD

**Issue by StoryHack** [lucaslorentz/caddy-docker-proxy#341]
I'm looking at running a website traffic stats package in a docker container and using the caddy-docker-proxy as a reverse proxy in front of it. 

I can get the container to run, and access it from the browser. The pertinent part of the docker-compose.yml:

```
labels:
  caddy: analytics.local
  caddy.reverse_proxy.to:  "{{upstreams 3000}}"
```

When the container is running, everything is hooked up right. I can go to analytics.local and use the software. However, I need to allow other websites to do the cross-site thing. For example, if I roll a testing website nd insert the javascript code that the analytics software provides, then the console gives me an error like this:

`Access to XMLHttpRequest at 'https://analytics.local/api' from origin 'https://test.local' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

So I assume I need to add in a header or two in the response given by the server. I have attempted to do so by adding header_down entries to my labels like this:

```
    labels:
      caddy: ackee.local
      caddy.reverse_proxy.to:  "{{upstreams 3000}}" 
      caddy.reverse_proxy.header_down: +Access-Control-Allow-Origin "*" 
      caddy.reverse_proxy.header_down: +Access-Control-Allow-Methods "GET, POST, PATCH, OPTIONS" 
      caddy.reverse_proxy.header_down: +Access-Control-Allow-Headers "Content-Type, Authorization, Time-Zone" 
      caddy.reverse_proxy.header_down: +Access-Control-Allow-Credentials "true" 
```
And restart / rebuild the analytics.local container, but I get the same error.

This leads me to believe that I have those new lines in my yml incorrect. 

I also tried wrapping the headers in quotes like this:
```
      caddy.reverse_proxy.header_down: "+Access-Control-Allow-Origin \"*\"" 
      caddy.reverse_proxy.header_down: "+Access-Control-Allow-Methods \"GET, POST, PATCH, OPTIONS\"" 
      caddy.reverse_proxy.header_down: "+Access-Control-Allow-Headers \"Content-Type, Authorization, Time-Zone\"" 
      caddy.reverse_proxy.header_down: "+Access-Control-Allow-Credentials \"true\"" 
```
With no joy.

Can you tell what I am doing wrong?

*Edited for formatting*

**Comment by IndeedNotJames** [comment]
Hi :)

Docker labels need to be unique. And what you are trying is essentially specifying `caddy.reverse_proxy.header_down` once and overwriting it 3 times.

This is a limitation of Docker and but this plugin has a simple solution for that:
https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/README.md#ordering-and-isolation ([permalink](https://github.com/lucaslorentz/caddy-docker-proxy/blob/4905e9cee02673b6ba7b4a12fc8f53758d8810a5/README.md#ordering-and-isolation))

So what you need to do is to suffix your labels:

```yaml
labels:
  caddy: ackee.local
  caddy.reverse_proxy.to:  "{{upstreams 3000}}" 
  caddy.reverse_proxy.header_down_1: +Access-Control-Allow-Origin "*" 
  caddy.reverse_proxy.header_down_2: +Access-Control-Allow-Methods "GET, POST, PATCH, OPTIONS" 
  caddy.reverse_proxy.header_down_3: +Access-Control-Allow-Headers "Content-Type, Authorization, Time-Zone" 
  caddy.reverse_proxy.header_down_4: +Access-Control-Allow-Credentials "true" 
 ```

A quick curl:
```bash
❯ # before
❯ curl -I https://issue341.localhost/
HTTP/2 200 
access-control-allow-credentials: true
content-type: text/plain; charset=utf-8
date: Tue, 22 Feb 2022 22:41:38 GMT
server: Caddy
content-length: 17

❯ # after
❯ curl -I https://issue341.localhost/
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-headers: Content-Type, Authorization, Time-Zone
access-control-allow-methods: GET, POST, PATCH, OPTIONS
access-control-allow-origin: *
content-type: text/plain; charset=utf-8
date: Tue, 22 Feb 2022 22:44:32 GMT
server: Caddy
content-length: 17
```
