### ISSUE TITLE
Proxy Error (apache + php-fpm)

### ISSUE THREAD

**Issue by patdavid** [lucaslorentz/caddy-docker-proxy#350]
Hi!

I'm having a small problem I'm not sure how to address.  I'm running a pair of bitnami images for apache + php-fpm that work fine on a test machine locally with this docker-compose.yml:

```docker-compose.yml
version: "3"
  
services:
  php: 
    image: bitnami/php-fpm:latest
    container_name: "bitnami-php-fpm"
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./app:/app
      - ./app/slim:/app/slim
        #- ./php-fpm.conf:/opt/bitnami/php/etc/php-fpm.conf
      - ./custom-php.ini:/opt/bitnami/php/etc/conf.d/custom.ini
  apache:
    image: bitnami/apache:latest
    user: root
    container_name: "bitnami-apache"
    ports: 
      - 88:8080
    volumes: 
      - ./apache-vhost/myapp.conf:/vhosts/myapp.conf:ro
      - ./app:/app
      - ./app/slim:/app/slim
    networks:
      - caddy
    labels:
      caddy: mysite.com
      caddy.reverse_proxy: "{{upstreams}}"
    depends_on:
      - php 
    
networks:
  caddy:
    external: true

```

And a myapp.conf that looks like this:

```apache
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

Listen 80
Listen 443

<VirtualHost *:80>
  ServerName mysite.com
  DocumentRoot "/app/slim"
  ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://php:9000/app/slim/$1
  <Directory "/app/slim">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
    DirectoryIndex index.php
  </Directory>
  FileEtag None
  Header unset ETag
  Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
  Header set Pragma "no-cache"
  Header set Expires "Wed, 11 Jan 1984 00:00:00 GMT"
</VirtualHost>
```

This runs fine on the test machine internally.
Now I'd like to run them on a server behind caddy using this docker-compose.yml:

```yml
version: "3"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}

```

Everything works fine if I access an index.html file, but trying to access index.php fails with this error:

```
bitnami-apache | [Wed Apr 13 22:16:19.913937 2022] [proxy:error] [pid 55] [client 172.18.0.3:57162] AH00898: DNS lookup failure for: php returned by /index.php, referer: https://mysite.com/
```
![image](https://user-images.githubusercontent.com/2778928/163279330-7c40f564-8a65-479f-a036-a681301a8160.png)

I'm positive it's something dumb I'm missing but I'm not quite sure what the solution would be.  Any ideas (pretty please)?
