### ISSUE TITLE
Connection to Docker Host not working as documented

### ISSUE THREAD

**Issue by am97** [lucaslorentz/caddy-docker-proxy#351]
I'm trying to run `lucaslorentz/caddy-docker-proxy` with a proxy for Docker API requests (`tecnativa/docker-socket-proxy`). If I use `DOCKER_HOST`, as documented in [the README](https://github.com/lucaslorentz/caddy-docker-proxy/blob/7bdd39f818fe06254424504156bc32211036382c/README.md#connecting-to-docker-host), the plugin ignores the env var and tries to connect to `unix:///var/run/docker.sock`.

To reproduce:

* Create a `caddy` network: `docker network create --driver overlay --attachable caddy`
* Deploy the following stack (on a single node swarm)
  ```yml
  version: '3.7'

  networks:
    caddy:
      external: true

  services:
    caddy:
      image: lucaslorentz/caddy-docker-proxy:ci-alpine@sha256:e0b329d0a5e45cdea1e8049780eebfc4aa36142a4c2503f9a3e1e9dab531e8e4
      ports:
        - 80:80
        - 443:443
      networks:
        - caddy
        - default
      environment:
        CADDY_INGRESS_NETWORKS: caddy
        DOCKER_HOST: tcp://docker-proxy:2375
    docker-proxy:
      image: tecnativa/docker-socket-proxy@sha256:6c22b9545adc95258af9deffdde6c0ce0a0a70716771e5a4e02d24d1b6e0dda1
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        CONFIGS: 1
        CONTAINERS: 1
        INFO: 1
        NETWORKS: 1
        NODES: 1
        SERVICES: 1
        SWARM: 1
        SYSTEM: 1
        TASKS: 1
    echo-headers:
      image: brndnmtthws/nginx-echo-headers@sha256:edb0c60573e658ea4c1b34efd6ba490fc0fdeab635a607a9f23ce27b1dda7df5
      networks:
        - caddy
      deploy:
        labels:
          caddy: nginx.local
          caddy.tls: internal
          caddy.reverse_proxy: "{{upstreams 8080}}"
  ```

The caddy container will keep restarting with the following logs:
```
{"level":"info","ts":1650107912.8525286,"logger":"docker-proxy","msg":"Running caddy proxy server"}
{"level":"info","ts":1650107912.8535273,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["[::1]:2019","127.0.0.1:2019","localhost:2019"]}
{"level":"info","ts":1650107912.8537607,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1650107912.8537724,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
{"level":"error","ts":1650107912.8542244,"logger":"docker-proxy","msg":"Docker ping failed on specify socket","error":"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?","DockerSocket":""}
docker-proxy: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Workaround: use `CADDY_DOCKER_SOCKETS` instead of `DOCKER_HOST`

I think it would be great to keep supporting `DOCKER_HOST`, I will submit a PR with a fix shortly
