### ISSUE TITLE
Proxy and rewrite

### ISSUE THREAD

**Issue by nzpopa** [lucaslorentz/caddy-docker-proxy#357]
Problem: while exposing an internal service to a /path, the internal service tries to load its assets from /

Consider this config:

```
labels:
      caddy: example.com
      caddy.handle_path: /internal*
      caddy.handle_path.0_rewrite: "* /internal{uri}"
      caddy.handle_path.1_reverse_proxy: "{{ upstreams 80 }}"
```

Expected result:

Accessing https://example.com/internal will load an asset from https://example.com/internal/main.js

Current result:

Accessing https://example.com/internal loads an asset from https://example.com/main.js
