### ISSUE TITLE
Turn off ssl redirect (use proxy with custom dns) for single containers

### ISSUE THREAD

**Issue by S0PEX** [lucaslorentz/caddy-docker-proxy#358]
Hey,

I was using traefik to serve my docker services in my local home network on custom domains `docker.home.intern` etc. and now want to move to caddy.
As `caddy-docker-proxy` automatically redirects all traffic from `https` to `https` I can't get my local domains working ( set in my router dns ) and was wondering if it would be possible to easily turn off the https redirect for certain containers.
It seems that setting the upstream only changes the protocol that caddy uses to connect to the container but not what the "outer world" would use.

```
ui:
    image: joxit/docker-registry-ui:latest
    labels:
      caddy: registry.home.intern
      caddy.reverse_proxy: "{{upstreams http 80}}"
    environment:
      - REGISTRY_TITLE=My local docker registry
      - NGINX_PROXY_PASS_URL=http://docker-registry:5000
      - SINGLE_REGISTRY=true
    networks:
      - caddy
      - registry-ui-net
    depends_on:
      - docker-registry
```
`registry.home.intern``is only a locally accessible.
Is there any easy was to disable https redirect for the container or would I need to create my own caddy config?

Thanks.

Regards Artur
