### ISSUE TITLE
Interest in enabling `enforce_origin` and `origins`?

### ISSUE THREAD

**Issue by gc-ss** [lucaslorentz/caddy-docker-proxy#359]
There's some interest over at the caddy forum about enabling `enforce_origin`: https://caddy.community/t/2-5-0-enforce-origin-bug/15764

However, a set of annotations for caddy-docker-proxy like:

```
    labels:
      caddy.admin: "unix//tmp/http.sock"
      # origins configures the list of remotes/origins that are allowed to connect to the endpoint.
      caddy.admin.origins: "unixsocket"  # https://github.com/caddyserver/caddy/commit/c2327161f725c820826587381f37d651a2b9736d#diff-308a4ab4e9e209d390d0cb79a9301a0f7e9768564a3b3489055bf1f0a3f8a775L655
      # enforce_origin enables enforcement of the Origin header. (This is different from enforcing origins generally, which is always done)
      caddy.admin.enforce_origin: ""
```

generates the expected JSON on load:
```
       "admin":{
          "listen":"unix//tmp/http.sock",
          "enforce_origin":true,
          "origins":[
             "unixsocket"
          ]
       },

```

but very quickly updated by `caddy-docker-proxy` to:
```
        "admin":{
          "listen":"tcp/localhost:2019"
        },
```
While it would be awesome to support unix sockets in `caddy-docker-proxy` (how do you feel about it?), my immediate interest is in having the `enforce_origin` and `origins` be respected.

let me know what you think about this :eyes:
