### ISSUE TITLE
Question: http proxy to container in host network

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#363]
I can successfully reverse proxy services via https using my domain. 
I can also successfully proxy containers that I do not want to expose online, through http (after configuring local domains in my DNS server, which is AdGuard Home). For example, Portainer is now accessible via http://docker.o/ within my LAN. All fine. 

My only issue is with containers that use `network_mode: host`. 

I expected this to work, by adding:

```
    extra_hosts:
      - host.docker.internal:host-gateway
```
and adding the labels for Adguard to the caddy container: 

```
version: "2.4"
services:
  caddy:
    container_name: web-proxy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: always
    networks: 
      - web-proxy
    environment:
      - CADDY_INGRESS_NETWORKS=web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/caddy/caddy_data:/data
      - $DOCKERDIR/caddy/config:/config
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      caddy.email: $EMAIL
      caddy: http://adguard.o
      caddy.reverse_proxy: localhost:3000
    ports:
      - 443:443
      - 80:80
  adguard:
    container_name: adguard
    image: adguard/adguardhome
    restart: always
    network_mode: host
    volumes:
       - $DOCKERDIR/adguardhome/work:/opt/adguardhome/work
       - $DOCKERDIR/adguardhome//conf:/opt/adguardhome/conf

networks:
  web-proxy:
    external: true
```

However log shows me: 

````
{"level":"info","ts":1652709060.1193893,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1652709060.119408,"logger":"admin.api","msg":"load complete"}
{"level":"info","ts":1652709060.1197352,"logger":"docker-proxy","msg":"Successfully configured","server":"localhost"}
{"level":"info","ts":1652709060.1229608,"logger":"admin","msg":"stopped previous server","address":"tcp/localhost:2019"}
{"level":"info","ts":1652709090.0942655,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: Caddyfile:18: unrecognized directive: email\nhttp://adguard.o {\n\temail obelix@obelix.cloud\n\treverse_proxy localhost:3000 host.docker.internal:3000\n}\n\n"}
````

Same issue when I change `caddy.reverse_proxy: localhost:3000` to `caddy.reverse_proxy: host.docker.internal:3000`. 

Do you have any tips?

**Comment by francislavoie** [comment]
I think you'll need to use a numbered suffix to define your site block, since you're also tryign to set a global option at the same time:

```
    labels:
      caddy.email: $EMAIL
      caddy_0: http://adguard.o
      caddy_0.reverse_proxy: localhost:3000
```
