### ISSUE TITLE
Cant use same domain in different docker services

### ISSUE THREAD

**Issue by masterbater** [lucaslorentz/caddy-docker-proxy#364]
How to setup the label so that I could reuse uitest.com to second container that I want to query if the url has api it will resolve to 3002
I keep encountering this error   Removing invalid block: duplicate site address not allowed. 
```
testingapp:
    .....
    networks:
      - caddy
    labels:
      caddy.tls: "internal"
      caddy: first.test second.test uitest.com
      caddy.reverse_proxy: "{{upstreams 8080}}"
  
   node-api:
    container_name: node-api
    .....
    networks:
      - caddy
    labels:
      caddy.tls: "internal"
      caddy: uitest.com
      caddy.1_reverse_proxy: "/api/* {{upstreams 3002}}"
```
My caddyfile works without using caddy-docker-proxy but I want to make use caddy-docker-proxy how could I set it up so it will have the Caddyfile format below
```
first.test second.test  {
		reverse_proxy testingapp:8080 {
			header_up Host {host} # redundant
			header_up X-Real-IP {remote}
			header_up X-Forwarded-For {remote}  # redundant
			header_up X-Forwarded-Port {server_port} # redundant
			header_up X-Forwarded-Proto {scheme}
		}
		 tls internal
		 
}


uitest.com {
	handle /api/* {
		reverse_proxy node-api:3002
	}
	reverse_proxy testingapp:8080 {
			header_up Host {host} # redundant
			header_up X-Real-IP {remote}
			header_up X-Forwarded-For {remote}  # redundant
			header_up X-Forwarded-Port {server_port} # redundant
			header_up X-Forwarded-Proto {scheme}
		}

	 tls internal
	
}

```

**Comment by lucaslorentz** [comment]
CaddyDockerProxy merges 2 caddy configurations if they are both for the exact same hosts. It is not smart enough to split testingapp caddy config into 2, so it can combine the uitest.com with node-api.

You can try splitting the configs yourself. Maybe this will work:

```
  testingapp:
    .....
    networks:
      - caddy
    labels:
      caddy_0.tls: "internal"
      caddy_0: first.test second.test uitest.com
      caddy_0.reverse_proxy: "{{upstreams 8080}}"
      caddy_1.tls: "internal"
      caddy_1: uitest.com
      caddy_1.reverse_proxy: "{{upstreams 8080}}"
  
   node-api:
    container_name: node-api
    .....
    networks:
      - caddy
    labels:
      caddy.tls: "internal"
      caddy: uitest.com
      caddy.1_reverse_proxy: "/api/* {{upstreams 3002}}"
```
