### ISSUE TITLE
Defining caddy config blocks w/i caddy-docker-proxy itself?

### ISSUE THREAD

**Issue by sdsys-ch** [lucaslorentz/caddy-docker-proxy#370]
Hi,

Is it possible to define Caddy configuration blocks at the caddy-docker-proxy level?

docker-compose.yml:
```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine

    ...

    labels:
      caddy.email: "ssl-admin@zzz.xy"
      caddy_0: aaa.yz bbb.yz ccc.abc
      caddy_0.respond: "pong" 200
```
This fails however:

> "did not find expected key while parsing a block mapping"

Is there a way to achieve this?

**Comment by sdsys-ch** [comment]
I forgot the path in the respond directive and the yaml error message sent me on a goose chase. Sorry, my bad!

This works as expected:
```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine

    ...

    labels:
      caddy.email: "ssl-admin@zzz.xy"
      caddy_0: aaa.yz bbb.yz ccc.abc
      caddy_0.respond: / "pong" 200
```
Thank you for this amazing plugin!
