### ISSUE TITLE
Simple setup with different port

### ISSUE THREAD

**Issue by disl-pdavid** [lucaslorentz/caddy-docker-proxy#371]
Hello!

I'm trying to get a very simple setup working where I want to reverse proxy traffic on port 3000 on the host to a container (grafana).

My caddy `docker-compose.yml` file:
```yml
version: "3"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 3000:3000
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
    restart: unless-stopped
 
networks:
  caddy:
    external: true
 
volumes:
  caddy_data: {}
```

And my simple grafana container `docker-compose.yml`:
```yml


version: "3"
 
services:
  grafana: 
    image: grafana/grafana
    container_name: "grafana"
    restart: unless-stopped
    volumes:
      - ./grafana-storage:/var/lib/grafana
    labels:
      caddy: myhost.org
      caddy.reverse_proxy: "{{upstreams 3000}}"
    networks:
      - caddy
    
networks:
  caddy:
    external: true
```

This works as expected _if I connect to `myhost.org` on port 80_.
I would like to be able to connect to the grafana container on port 3000 (on `myhost.org:3000` for example).

I feel like I must be missing something simple/fundamental but I'm not sure what.
