### ISSUE TITLE
Add root directive without sharing volumes

### ISSUE THREAD

**Issue by LeoColman** [lucaslorentz/caddy-docker-proxy#375]
Hello!

In issue https://github.com/lucaslorentz/caddy-docker-proxy/issues/215

It was established that one need to add the volumes so caddy can see them and thus serve them.
> So your issue is that you don't have a volume mounting the files into the Caddy container. Caddy needs to be able to see the files to serve them or tell php-fpm about them.

I have the following docker-compose file:

```
version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
      - /MYFIRSTPATH/:/var/www/html
      - /MYSECONDPATH/:/var/www/my_other_html

networks:
  caddy:
    external: true
```

And some services in the same machine, let's give them compose A and B

Compose A
```
  app:
    build: nextcloud
    networks:
      - caddy
      - default
    volumes:
      - ./data/nextcloud:/var/www/html
    labels:
      caddy: "first.domain.com"
      caddy.file_server: ""
      caddy.root: "* /var/www/html"
```

Compose B
```
  app:
    build: nextcloud
    networks:
      - caddy
      - default
    volumes:
      - ./data/nextcloud:/var/www/html
    labels:
      caddy: "second.domain.com"
      caddy.file_server: ""
      caddy.root: "* /var/www/my_other_html"
```

What I wanted to do was to say "Hey, Caddy! For Compose A, look at Compose A's /var/www/html" and the same thing for Compose B.

Today, this seems impossible as we need to share/centralize the volumes in the caddy container.
Is there something I can do to decouple the services from the caddy service?
