### ISSUE TITLE
Can this be used with wildcard DNS providers?

### ISSUE THREAD

**Issue by a10kiloham** [lucaslorentz/caddy-docker-proxy#381]
It wasn't clear whether adding the cloud flare plugin would work here and how to configure w the api keys.
This looks great though regardless thanks for this project!

**Comment by lucaslorentz** [comment]
Yes, caddy supports wildcard addresses: https://caddyserver.com/docs/caddyfile/concepts#addresses

It even supports generating SSL certificates for those, either on-demand or using a wildcard certificates: https://caddyserver.com/docs/automatic-https

I don't think you really need the cloud flare plugin. You just need to point your wildcard DNS to your docker IPs.

Caddy will use HTTP Challenge to prove that you own the domain. Basically, it serves the challenge-response using HTTP, and the SSL issuer will be able to each your caddy server to check it because your DNS is already pointing to it.

If you want to change the ACME challenge to be DNS based, then you need to add the cloud-flare plugin and configure it. That way caddy will be able to modify your DNS records with challenge responses to prove that you own the domain.

**Comment by hycday** [comment]
@lucaslorentz does that mean that caddy also supports SSL for IP addresses ? i.e. if my server IP is 201.5.5.10 for example, and my domain names point to this IP, but if a user types directly the IP, will they see something or get an "ERR_SSL_PROTOCOL_ERROR" error (or something else). Asking because doing so didnt work out :

```
    labels:
      caddy_0: domain.com
      caddy_0.root: "* /www"
      caddy_0.encode: gzip
      caddy_0.file_server:
      caddy_1: www.domain.com, 201.5.5.10
      caddy_1.redir: "https://domain.com{uri} permanent"
```

asking in this thread to follow up on your question , but if you think it's not the right place let me know and i will post it separately

**Comment by hycday** [comment]
thanks for the correction, bad habit (being a novice also didnt help) but now I know.


Doing the following didnt work (i.e. if I go to the IP I get that error : )

```
   labels:
      caddy_0: domain.com
      caddy_0.root: "* /www"
      caddy_0.encode: gzip
      caddy_0.file_server:
      caddy_1: www.domain.com
      caddy_1.redir: "https://domain.com{uri} permanent"
      caddy_2: 201.5.5.10
      caddy_2.root: "* /www"
      caddy_2.encode: gzip
      caddy_2.file_server:
      caddy_2.tls: internal
```
