### ISSUE TITLE
Adapt labels to environments, volumes and other 

### ISSUE THREAD

**Issue by hycday** [lucaslorentz/caddy-docker-proxy#382]
Hi,

I am trying to integrate the following docker https://github.com/searxng/searxng-docker with lucaslorentz/caddy-docker-proxy (i.e. use the searxng with this one).
So I will remove the caddy from searxng docker-composer and add the necessary labels to make it work with lucaslorentz/caddy-docker-proxy.

For now I started with the easy ones : 

>    labels:
      caddy: mydomain.com
      caddy.reverse_proxy: "{{upstreams 8088}}"
      caddy.network_mode: host

but I am struggling to understand the documentation to adapt that part of their docker-compose

>
     volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

If we take the example of cap_drop, should I add a label that would be : 

>    caddy.cap_drop: "ALL" 

then for environment : 

> caddy.environment.SEARXNG_HOSTNAME: "${SEARXNG_HOSTNAME:-http://localhost:80}"
caddy.environment.SEARXNG_TLS: "${LETSENCRYPT_EMAIL:-internal}"

is this the right way to adapt the labels?

**Comment by francislavoie** [comment]
Those aren't Caddyfile directives/config, those are actual docker-compose config. You can't move those into labels, that doesn't make sense. `network_mode` isn't Caddyfile either, it's a docker-compose option.

**Comment by hycday** [comment]
ahhh... silly me... indeed 🤦‍♂️ 

so in this case, i will need to have another caddy instance on the other docker ? no way to "mix" them ?

**Comment by francislavoie** [comment]
I'm not really sure what you're trying to do. But the labels for this plugin are meant to replace a `Caddyfile`, by loading them from containers that are started. Look at the Caddyfile for searxng: https://github.com/searxng/searxng-docker/blob/master/Caddyfile, you'd need to convert that config to labels.

You could just run it as its own stack with its own instance of Docker, and proxy to it; make sure you configure it to listen on `http://` (i.e. `SEARXNG_HOSTNAME` env) so it accepts any connection on port 80.

**Comment by hycday** [comment]
> You could just run it as its own stack with its own instance of Docker, and proxy to it; make sure you configure it to listen on http:// (i.e. SEARXNG_HOSTNAME env) so it accepts any connection on port 80.

I am not sure what you mean by that and how would that translate into code, neither where would it go :(

**Comment by francislavoie** [comment]
Yeah, basically.

You also need to make sure they share docker network so that CDP can pick up that docker stack being started.

**Comment by hycday** [comment]
I either get "ERR_TOO_MANY_REDIRECTS" or "502 error" depending on if I do the following : 

```
version: '3.7'
services:
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
      - caddy
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
      - caddy
    ports:
     - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      caddy: mydomain.com
      caddy.reverse_proxy: "{{upstreams 80}}"
networks:
  caddy:
    external: true
  searxng:
    ipam:
      driver: default
volumes:
  caddy-data:
  caddy-config:
```


or that one (difference is that i added the stuff under the caddy service instead of the searxng service): 

```

version: '3.7'

services:

  caddy:
    container_name: caddy
    image: caddy:2-alpine
#    network_mode: host
    networks:
      - caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
    labels:
      caddy: mydomain.com
      caddy.reverse_proxy: "{{upstreams 80}}"
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
      - caddy
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  caddy:
    external: true
  searxng:
    ipam:
      driver: default
volumes:
  caddy-data:
  caddy-config:
```


I didnt change the caddy file in the other project (https://github.com/searxng/searxng-docker/blob/master/Caddyfile) and my docker compose in CDP is like in the doc (so normally the networks name etc should connect now....)

```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
```


i'm sorry to insist on that :/
