### ISSUE TITLE
caddy container can't discover labels for containers on other nodes in an overlay network

### ISSUE THREAD

**Issue by rmmanseau** [lucaslorentz/caddy-docker-proxy#383]
After a bunch of time spent googling its still unclear to me if this is supposed to work or if its a known limitation:

I have two nodes, A & B, in my home network. I enabled swarm mode and then connected both nodes to an overlay network with the --attachable flag, as described [here](https://docs.docker.com/network/network-tutorial-overlay/#use-an-overlay-network-for-standalone-containers). I'm not interested in swarm services, I dont have enough nodes for redundancy & I prefer to have my containers pinned to a specific node so I can use bind mounts. I only use the overlay network as a way to communicate between standalone containers on each of the nodes. 

I have caddy-docker-proxy running on node A, and a service that I want to reverse proxy to on node B. I am able to do this by placing labels onto the caddy container that explicitly names the container on node b:
```
services:
  caddy:
    ...
    labels:
      caddy_1: node-b-container.example.com
      caddy_1.reverse_proxy: "node-b-container:80"
```
but If i place the labels on the container on node B, the caddy container on node A doesn't discover them.
```
services:
  node-b-container:
    ...
    labels:
      caddy: node-b-container.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
```

from the googling i've done this seems to be because the overlay network doesn't provide access to the docker sockets of other nodes in the network, it just allows you to discover them via dns & route http traffic. that brings me to my question. is there any way to allow caddy to discover the labels of containers on node B? can I give the container access to node B's docker socket somehow? if so, how would I go about that? 

Thanks!!!

**Comment by rmmanseau** [comment]
these are the two relevant docker compose files & a `docker network inspect` of the overlay network from each node (with irrelevant containers filtered out) 

`caddy/docker-compose.yaml` on node A
```
version: "3.7"

networks:
  caddy-ol:
    driver: overlay
    external: true

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-ol
    ports:
      - 80:80
      - 443:443
    networks:
      - caddy-ol
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    labels:
      caddy.email: me@example.com

      # snippet to block external ips
      caddy_0: (block_external)
      caddy_0.@external_ip.not.remote_ip: 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
      caddy_0.respond: "@external_ip 403"

      # caddy_1: adguard.int.example.com
      # caddy_1.reverse_proxy: "adguard:80"
      # caddy_1.import: block_external
      # caddy_1.tls: internal
      # caddy_1.tls.on_demand:
```

`adguard-unbound/docker-compose.yaml` on node B
```
version: "2.1"

networks:
  dns:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/24
        gateway: 172.19.0.1
  caddy-ol:
    driver: overlay
    external: true

services:
  unbound: # DNS root resolver
    image: mvance/unbound-rpi:latest
    container_name: unbound
    hostname: unbound
    volumes:
      - type: bind
        source: ./unbound.conf
        target: /opt/unbound/etc/unbound/unbound.conf
    restart: unless-stopped
    networks:
      dns:
        ipv4_address: 172.19.0.101

  adguard: # DNS server & ad blocker
    image: adguard/adguardhome
    container_name: adguard
    depends_on:
      - unbound
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 53:53/tcp
      - 53:53/udp
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      caddy-ol:
      dns:
        ipv4_address: 172.19.0.100
    labels:
      caddy: adguard.int.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.import: block_external
      caddy.tls: internal
      caddy.tls.on_demand:
```

`docker network inspect caddy-ol` on Node A
```
[
    {
        "Name": "caddy-ol",
        "Id": "zmyxmskoh7f6q3hbvm8jn0886",
        "Created": "2022-07-05T00:06:35.278290738Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "59ead67e4845f792c604d7adee4876060b8d1dd30b19cbbd4025e1689b397464": {
                "Name": "caddy",
                "EndpointID": "7bd8e7d3f373165d17f4eff1f11ecafe52911e8b43ea4740fc3fa6eec77e77c1",
                "MacAddress": "02:42:0a:00:01:20",
                "IPv4Address": "10.0.1.32/24",
                "IPv6Address": ""
            },
           < all the other containers on node A>,
           "lb-caddy-ol": {
               "Name": "caddy-ol-endpoint",
               "EndpointID": "b93dff1a21114c2c1ebae457351349b7f28164baa751ca2db496f94dfabc4c36",
               "MacAddress": "02:42:0a:00:01:41",
               "IPv4Address": "10.0.1.65/24",
               "IPv6Address": ""
           }
       },
       "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "082ced63d47c",
                "IP": "192.168.4.100"
            },
            {
                "Name": "52255b6cd4c2",
                "IP": "192.168.4.101"
            }
        ]
    }
]

```

`docker network inspect caddy-ol` on Node B
```
[
    {
        "Name": "caddy-ol",
        "Id": "zmyxmskoh7f6q3hbvm8jn0886",
        "Created": "2022-07-05T09:49:08.275984763-07:00",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "10.0.1.0/24",
                    "Gateway": "10.0.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "57243d4e604bc51d10fd0607dbc6ec7775ab0a8c5d2a48b0523a7684d7100514": {
                "Name": "adguard",
                "EndpointID": "06a0c55e71b0246ebf4fd456ac338aacabac2b9152bb793963e6230db03c4a20",
                "MacAddress": "02:42:0a:00:01:21",
                "IPv4Address": "10.0.1.33/24",
                "IPv6Address": ""
            },
            "lb-caddy-ol": {
                "Name": "caddy-ol-endpoint",
                "EndpointID": "54a5cdb7df850242c54e4e8266145aec3419c3ccedca1abd2d8791d9f56e04f0",
                "MacAddress": "02:42:0a:00:01:22",
                "IPv4Address": "10.0.1.34/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": {},
        "Peers": [
            {
                "Name": "52255b6cd4c2",
                "IP": "192.168.4.101"
            },
            {
                "Name": "082ced63d47c",
                "IP": "192.168.4.100"
            }
        ]
    }
]
```
