### ISSUE TITLE
Blank Page in nextcloud stack

### ISSUE THREAD

**Issue by ramolec** [lucaslorentz/caddy-docker-proxy#387]
Hello, 

I'm newbie in docker and caddy. I'm racking my brain to figure out how I can debug this problem. I have a service using a nextcloud-fpm container in a local environment just for development and then putting it into production. I'm guessing that the problem is reading the caddy server on the nextcloud-fpm container volume.

**Problem**
When I access localhost in Firefox it just shows a completely blank page.

**Question**
I'm not sure how to get into debug mode, and what could be causing this problem?

 _request with curl -v localhost_
```
 Trying 127.0.0.1:80...
 TCP_NODELAY set
 Connected to localhost (127.0.0.1) port 80 (#0)
 GET / HTTP/1.1
 Host: localhost
 User-Agent: curl/7.68.0
 Accept: */*

 Mark bundle as not supporting multiuse
 HTTP/1.1 308 Permanent Redirect
 Connection: close
 Location: https://localhost/
 Server: Caddy
 Date: Wed, 20 Jul 2022 00:58:57 GMT
 Content-Length: 0
 Closing connection 0 
```

_**docker-compose.yml**_

```
version: "3"
services:
  caddy:
    container_name: caddy-proxy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: always
    networks: 
      - web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/caddy/caddy_data:/data
      - $DOCKERDIR/caddy/config:/config
    volumes_from: 
      - nextcloud 
    ports:
      - 80:80
      - 443:443
      - 
  nextcloud:
    image: nextcloud:fpm-alpine
    container_name: nextcloud
    restart: always
    mem_limit: 2048m
    mem_reservation: 512m
    networks:
      - web-proxy
      - nextcloud
    depends_on:
      - nextcloud-db
      - nextcloud-cache
    environment:
      NEXTCLOUD_DATA_DIR: /var/nextdata
      NEXTCLOUD_TRUSTED_DOMAINS: localhost
      NEXTCLOUD_ADMIN_USER: $ADMIN
      NEXTCLOUD_ADMIN_PASSWORD: $ADMINPW
      POSTGRES_HOST: nextcloud-db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: $USER_INT
      POSTGRES_PASSWORD: $PW_INT
      REDIS_HOST: nextcloud-cache
      REDIS_HOST_PASSWORD: $PW_INT
    volumes:
      - $DOCKERDIR/nextcloud/var/nextdata:/var/nextdata
      - $DOCKERDIR/nextcloud/var/www/html:/var/www/html
      - $DOCKERDIR/nextcloud/var/www/html/config:/var/www/html/config
    labels:
      caddy: localhost
      caddy.file_server: "" 
      caddy.root: "* /nextcloud/var/www/html"
      caddy.php_fastcgi: "{{upstreams 9000}}"
      caddy.php_fastcgi.root: "/var/www/html"
      caddy.php_fastcgi.env: "front_controller_active true"
      caddy.encode: gzip
      caddy.redir_0: "/.well-known/carddav /remote.php/dav 301"
      caddy.redir_1: "/.well-known/caldav /remote.php/dav 301"
      caddy.header.Strict-Transport-Security: '"max-age=15768000;includeSubDomains;preload"' # Required for Nextcloud
  nextcloud-db:
    container_name: nextcloud-db
    image: postgres:12-alpine
    restart: always
    networks:
      - nextcloud
    environment:
      POSTGRES_USER: $USER_INT
      POSTGRES_PASSWORD: $PW_INT
    volumes:
      - $DOCKERDIR/nextcloud/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  nextcloud-cache:
    container_name: nextcloud-cache
    image: redis:alpine
    restart: always
    mem_limit: 2048m
    mem_reservation: 512m
    networks:
      - nextcloud
    command: redis-server --requirepass $PW_INT

networks:
  web-proxy:
    driver: bridge
  nextcloud:
    driver: bridge
```
