### ISSUE TITLE
Upstreams in swarm not detecting container IP changes

### ISSUE THREAD

**Issue by sjdaws** [lucaslorentz/caddy-docker-proxy#393]
Hi,

I've had a look through the docs and issues and can't find an answer for what I'm experiencing, https://github.com/lucaslorentz/caddy-docker-proxy/issues/355 is close, but not the same.

I am running a swarm on 6 servers (3 manager, 3 workers), with this config for caddy:

**Caddy compose**
```yaml
networks:
  containers:
    external: true
services:
  caddy:
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    environment:
      - CADDY_INGRESS_NETWORKS=containers
    healthcheck:
      test: killall -0 caddy || exit 1
    image: sjdaws/caddy
    networks:
      - containers
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
      - /var/run/docker.sock:/var/run/docker.sock
version: "3.9"
volumes:
  caddy:
    external: true
```

This caddy compose uses the image `sjdaws/caddy` however the only change is the addition of cloudflare:

**Caddy Dockerfile**
```
ARG CADDY_VERSION=2
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/caddy-dns/cloudflare

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

It results in this caddyfile entry:

```
...

tautulli.mydomain {
	reverse_proxy 192.168.7.82:8181
	tls {
		dns cloudflare XXX
	}
}

...
```

The logs output this message: 

```json
...

                   {
                     "match":[
                        {
                           "host":[
                              "tautulli.mydomain"
                           ]
                        }
                     ],
                     "handle":[
                        {
                           "handler":"subroute",
                           "routes":[
                              {
                                 "handle":[
                                    {
                                       "handler":"reverse_proxy",
                                       "upstreams":[
                                          {
                                             "dial":"192.168.7.82:8181"
                                          }
                                       ]
                                    }
                                 ]
                              }
                           ]
                        }
                     ],
                     "terminal":true
                  },

...
```

**Service compose**
```yaml
networks:
  containers:
    external: true
services:
  tautulli:
    deploy:
      labels:
        caddy: tautulli.mydomain
        caddy.reverse_proxy: "{{upstreams 8181}}"
        caddy.tls.dns: cloudflare XXX
      placement:
        constraints:
          - node.labels.storage==persistent
      replicas: 1
    environment:
      - PGID=65534
      - PUID=65534
      - TZ=Australia/Melbourne
    healthcheck:
      test: curl -fsS http://localhost:8181 || exit 1
    image: linuxserver/tautulli
    networks:
      - containers
    volumes:
      - /lardlad/containers/data/tautulli:/config
      - "/lardlad/containers/data/plex/Library/Application Support/Plex Media Server/Logs:/logs"
version: "3.9"
```

After running the container for a few hours, and being able to connect fine on `tautulli.mydomain` I get a 502 error:

```json
{
   "level":"error",
   "ts":1660888063.3831966,
   "logger":"http.log.error",
   "msg":"dial tcp 192.168.4.92:8181: i/o timeout",
   "request":{
      "remote_ip":"10.10.10.202",
      "remote_port":"32888",
      "proto":"HTTP/1.1",
      "method":"GET",
      "host":"tautulli.mydomain",
      "uri":"/",
      "headers":{
         "Accept":[
            "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
         ],
         "User-Agent":[
            "Uptime-Kuma/1.17.1"
         ],
         "Connection":[
            "close"
         ]
      },
      "tls":{
         "resumed":false,
         "version":772,
         "cipher_suite":4865,
         "proto":"",
         "server_name":"tautulli.mydomain"
      }
   },
   "duration":3.001528552,
   "status":502,
   "err_id":"eqwfyx7ym",
   "err_trace":"reverseproxy.statusError (reverseproxy.go:1184)"
}
```

This is because the container has exited due to a healthcheck and a new one has been created. If I inspect or ping the container, the IP has changed:

```
sudo docker run --rm --network containers nginx:alpine ping tautulli
PING tautulli (192.168.4.71): 56 data bytes
64 bytes from 192.168.4.71: seq=0 ttl=64 time=0.184 ms
64 bytes from 192.168.4.71: seq=1 ttl=64 time=0.353 ms
^C
--- tautulli ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.184/0.268/0.353 ms
```

I can somewhat prevent this by running more replicas, but eventually they all are replaced and I lose the domain until I restart caddy or the service.

Should caddy reload when an IP changes? Am I missing something in my setup that should allow caddy to handle the ip change? Should I be runner a server with a controller on each instance?

**Comment by sjdaws** [comment]
On further investigation, it seems like the network is split across all nodes, the ones I'm having issues with are isolated to not being on the same node. I'm going to try server/controller, so please disregard this issue.

**Comment by sjdaws** [comment]
If anyone else is experiencing this issue, it seems resolved with a split controller/server, with a server on each node. I initially thought I might need a controller on each node and a single server, however controllers don't work on workers.

**Controller**
```yaml
networks:
  caddy:
    external: true
  containers:
    external: true
services:
  caddy-controller:
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    environment:
      - CADDY_CONTROLLER_NETWORK=192.168.100.0/24
      - CADDY_DOCKER_MODE=controller
      - CADDY_INGRESS_NETWORKS=containers
    healthcheck:
      test: killall -0 caddy || exit 1
    image: sjdaws/caddy
    networks:
      - caddy
      - containers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
version: "3.9"
```

**Server**
```yaml
networks:
  caddy:
    external: true
  containers:
    external: true
services:
  caddy-server:
    deploy:
      labels:
        caddy_controlled_server:
      mode: global
    environment:
      - CADDY_CONTROLLER_NETWORK=192.168.100.0/24
      - CADDY_DOCKER_MODE=server
      - CADDY_INGRESS_NETWORKS=containers
    healthcheck:
      test: killall -0 caddy || exit 1
    image: sjdaws/caddy
    networks:
      - caddy
      - containers
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
version: "3.9"
volumes:
  caddy:
    external: true
```

**Comment by eazylaykzy** [comment]
> If anyone else is experiencing this issue, it seems resolved with a split controller/server, with a server on each node. I initially thought I might need a controller on each node and a single server, however controllers don't work on workers.
> 
> **Controller**
> 
> ```yaml
>     environment:
>       - CADDY_CONTROLLER_NETWORK=192.168.100.0/24
> ```
> 
> **Server**
> 
> ```yaml
>     environment:
>       - CADDY_CONTROLLER_NETWORK=192.168.100.0/24
> ```

@sjdaws I was wondering how do one know how to map the correct network to `CADDY_CONTROLLER_NETWORK` and  `subnet` from the network configuration of the controller, I'm not big on networking, I've been trying to figure this out with no luck.

```
  caddy_controller:
    driver: overlay
    ipam:
      driver: default
        config:
          - subnet: "10.200.200.0/24"
```
