### ISSUE TITLE
DNS Challenge Wildcards?

### ISSUE THREAD

**Issue by borland502** [lucaslorentz/caddy-docker-proxy#395]
My home servers are bound to cloudflare, so I can't easily make use of the tls challenge and I default to wildcards just for easy breezy config.  I am using docker swarm and this is just a home intranet.  My pre-docker-proxy config looks something like this

```json
*.local.foo.com, local.foo.com {
   
   @unraid host unraid.foo.com:5000 
   handle @unraid {
       reverse_proxy http://unraid.local.foo.com:5000 {
         import proxy_http_transport_opts
       }
   }
   
   ... more subdomain relays follow
}
```

I've tried various ways to use the label syntax for wildcards, but I wanted to see if I was barking up the wrong tree given that the documentation doesn't cover either dns verification or wildcards.

I had hoped that I could get the wildcards in the stub Caddyfile below and the individual hosts could be labels.  Fine work you've done regardless as I can't complain if this doesn't suit my use case.  I just want to know if I'm fitting a square peg into a round hole or just being dense.

```yaml
configs:
  caddy-basic-content:
    file: ./Caddyfile
    labels:
      caddy:
```

**Comment by borland502** [comment]
Nm, I got a way thought if you know of a better way I'm all ears.  Thank you for making this project.

```yaml
labels:
        caddy: heimdall.local.foo.com
        caddy.reverse_proxy: "{{upstreams}}"
        caddy.tls: "bar@gmail.com"
        caddy.tls.dns: "cloudflare 123456789"
```
