### ISSUE TITLE
Caddyfile not being created

### ISSUE THREAD

**Issue by fleadope** [lucaslorentz/caddy-docker-proxy#411]
Had a running instance, which seems to have broken on an upgrade to the latest version. 

Logs here: 

```compose-caddy-1  | {"level":"info","ts":1665598247.0845218,"logger":"docker-proxy","msg":"Running caddy proxy server"}
compose-caddy-1  | {"level":"info","ts":1665598247.0866542,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
compose-caddy-1  | {"level":"info","ts":1665598247.0868587,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
compose-caddy-1  | {"level":"info","ts":1665598247.0868714,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
compose-caddy-1  | {"level":"info","ts":1665598247.0889301,"logger":"docker-proxy","msg":"Start","CaddyfilePath":"","LabelPrefix":"caddy","PollingInterval":30,"ProcessCaddyfile":true,"ProxyServiceTasks":true,"IngressNetworks":"[caddy]","DockerSockets":[""],"DockerCertsPath":[""],"DockerAPIsVersion":[""]}
compose-caddy-1  | {"level":"info","ts":1665598247.0912821,"logger":"docker-proxy","msg":"IngressNetworksMap","ingres":"map[62ae5b1a927a5646f5bc38cb6bc5ef4f4e66787da1e073deb1569c5071081e43:true]"}
compose-caddy-1  | {"level":"info","ts":1665598247.0925243,"logger":"docker-proxy","msg":"Connecting to docker events","DockerSocket":""}
compose-caddy-1  | {"level":"info","ts":1665598247.1034951,"logger":"docker-proxy","msg":"Swarm is available","new":false}
compose-caddy-1  | {"level":"info","ts":1665598247.1056907,"logger":"docker-proxy","msg":"New Caddyfile","caddyfile":"{\n\temail me@gmail.com\n\tlog {\n\t\tformat console\n\t\tlevel debug\n\t}\n}\n"}
compose-caddy-1  | {"level":"info","ts":1665598247.1066682,"logger":"docker-proxy","msg":"New Config JSON","json":"{\"logging\":{\"logs\":{\"default\":{\"encoder\":{\"format\":\"console\"},\"level\":\"debug\"}}}}"}
compose-caddy-1  | {"level":"info","ts":1665598247.1072097,"logger":"docker-proxy","msg":"Sending configuration to","server":"localhost"}
compose-caddy-1  | {"level":"info","ts":1665598247.1085966,"logger":"admin.api","msg":"received request","method":"POST","host":"localhost:2019","uri":"/load","remote_ip":"127.0.0.1","remote_port":"42728","headers":{"Accept-Encoding":["gzip"],"Content-Length":["121"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}
compose-caddy-1  | 1.6655982471095014e+09       info    admin   admin endpoint started  {"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
compose-caddy-1  | 1.6655982471100938e+09       info    autosaved config (load with --resume flag)      {"file": "/config/caddy/autosave.json"}
compose-caddy-1  | 1.6655982471105454e+09       info    admin.api       load complete
compose-caddy-1  | {"level":"info","ts":1665598247.1110005,"logger":"docker-proxy","msg":"Successfully configured","server":"localhost"}
compose-caddy-1  | 1.665598247112366e+09        info    admin   stopped previous server {"address": "localhost:2019"}
```

The Caddyfile doesn't seem to be created, as it is  is not being created; here is a sample (unchanged) of what worked before: 

```
version: "3.7"

x-default-networks: &default-networks
  networks:
    - caddy
    - db

x-default-depends: &default-depends
  depends_on:
    - caddy
    - db
    
services:
  caddy: 
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports: 
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/config/Caddyfile
    networks: 
      - caddy
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/caddy:/data
      - ${CONF_DIR}/caddy:/config  
     miniflux:
    image: miniflux/miniflux:latest
    <<: *default-networks
    <<: *default-depends
    env_file:
      - ${ENV_DIR}/miniflux.env
    labels:
      caddy: news.me.cc
      caddy.reverse_proxy: "{{upstreams 8080}}"
```

I am using rootless docker, as in [devhero's issue here:](https://github.com/lucaslorentz/caddy-docker-proxy/issues/409), but the issue seems to be different, as the network issue he had is not present here, AFAICT. 

Also, when i replace the docker-compose.yml with one created directly from the README, and have checked that the /config dir is mounting. 

Can anyone point me in the right direction?
