### ISSUE TITLE
caddy-docker-proxy forward auth with authentik

### ISSUE THREAD

**Issue by Janik-Haag** [lucaslorentz/caddy-docker-proxy#424]
Hi i just started using caddy-docker-proxy a few day's ago and its great.
I tried to get the forward-auth working with Authentik. but can\t seem to do so.
The application i want to get it working with is paperless-ngx.
Docks:
[caddy](https://caddyserver.com/docs/caddyfile/directives/forward_auth#forward-auth)
[authentik-forward-auth](https://goauthentik.io/docs/providers/proxy/forward_auth#caddy)
[authentik-application-example](https://goauthentik.io/integrations/services/paperless-ng/)
I also have the feeling that the suggested way won't work because the label name is used twice and my feeling is that docker will overwrite one. Anyways here is the relevant docker-compose snippet:

```
labels:
      caddy: paperless.mydomain.com      
      caddy.reverse_proxy: /outpost.goauthentik.io/* https://sso.mydomain.com
      caddy.forward_auth: https://paperless.mydomain.com
      caddy.forward_auth.uri: /outpost.goauthentik.io/auth/caddy
      caddy.forward_auth.copy_headers: X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version
      caddy.forward_auth.trusted_proxies: private_ranges
      caddy.reverse_proxy: "{{upstreams 8000}}"
```

The error im encountering is that the config above redirects me to `sso.mydomain.com/outpost.goauthentik.io/auth/caddy` instead off `paperless.mydomain.com/outpost.goauthentik.io/auth/caddy`

And because of an redirect instead of proxying the request the host header changes and authentik dos'nt know how to process the request.
![image](https://user-images.githubusercontent.com/80165193/202843700-6b425971-c045-4d10-aeca-c6246e3991b2.png)

I added all the mentions of my actual domain, for obvious reasons and usually with the default caddy and caddy.reverse_proxy labels it's just working great.
If anymore info is needed just ask, i will gladly provide more.

**Comment by lucaslorentz** [comment]
Looks like the app running behind https://sso.mydomain.com is what triggers the authentication by returning an HTTP redirect response.
It doesn't know that you're using the domain paperless.mydomain.com, so it cannot generate a proper redirect.

Usually, applications allow you to configure what's their url, and they use that for redirects and so on, you can try to find out how to configure that. Some applications also support inferring what should be the url based on X-Forwarded headers, but that doesn't seem to be your case because Caddy automatically sends X-Forwarded headers for reverse_proxy.

After fixing that, you might want to add a number suffix to your reverse_proxy labels to avoid overwrites:
```
      caddy.reverse_proxy_0: /outpost.goauthentik.io/* https://sso.mydomain.com
      ...
      caddy.reverse_proxy_1: "{{upstreams 8000}}"
```

**Comment by igniscyan** [comment]
@Janik-Haag Did you ever get this working? Trying to set up the same for myself right now, seems as though you got a bit further than I did.

**Comment by Janik-Haag** [comment]
I don't think so, at some point I switched to Traefik for various reasons.

**Comment by igniscyan** [comment]
> I don't think so, at some point I switched to Traefik for various reasons.

Is there something similar to CDRP in Traefick land? Did you find the setup there to be easier?

**Comment by Janik-Haag** [comment]
Not quite easier but definitively better documented, and the nice thing is that traefik supports proxying docker containers with labels by default.

**Comment by joshoram80** [comment]
I did it this way using an (auth) snippet in the Caddyfile and using the import function in the label to bring it in. This way if there is a service I don't want behind Authentik, I can just leave out the `caddy.handle.import: auth` label.

Just replace "whoami" with whatever you need for that service. It's a bit hacky but it works.

docker-compose.yml
```
labels:
      caddy: "*.$DOMAIN, $DOMAIN"
      caddy.@whoami: "host whoami.$DOMAIN"
      caddy.handle: "@whoami"
      caddy.handle.import: auth
      caddy.handle.reverse_proxy: "{{upstreams}}"
```

Caddyfile
```
(auth) {
    # always forward outpost path to actual outpost
    reverse_proxy /outpost.goauthentik.io/* http://authentik_server:9000 {
        header_up Host {http.reverse_proxy.upstream.hostport}
    }
    # forward authentication to outpost
    forward_auth http://authentik_server:9000 {
        uri /outpost.goauthentik.io/auth/caddy

        # capitalization of the headers is important, otherwise they will be empty
        copy_headers copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version

        # optional, in this config trust all private ranges, should probably be set to the outposts IP
        trusted_proxies private_ranges
    }
}

*.$DOMAIN, $DOMAIN {
    tls {
        dns cloudflare $CF_API_KEY
    }
    @home host $DOMAIN
    handle @home {
        reverse_proxy homepage:3000
    }
}
```

**Comment by grimsi** [comment]
The answer of @joshoram80 can even be further simplified (since you dont need the `handle` directive here):

docker-compose.yml
```
labels:
    caddy: whoami.$DOMAIN
    caddy.reverse_proxy: "{{upstreams}}"
    caddy.import: auth
```

Caddyfile
```
(auth) {
    forward_auth http://authentik-server:9000 {
        uri /outpost.goauthentik.io/auth/caddy
        copy_headers copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version
        trusted_proxies private_ranges
    }
}
```

**Comment by francislavoie** [comment]
@grimsi the difference is whether you want only a single wildcard cert for all your subdomains, or if you're okay with having many certificates for each subdomain. @joshoram80 was implementing the pattern from https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates

**Comment by Moe1369** [comment]
@grimsi  Hey any way to make this into a normal label. I know it's not pretty but for my use case easier since importing Caddyfile is not possible atm.

**Comment by christophdb** [comment]
Just for reference, that somebody tries to use caddy-docker-proxy with authentik "Proxy Provider". Here are my labels, that I used:
(replace ${AUTHENTIK_URL} with your authentik url and ${DOMAIN} with the domain you would like to protect.

```
labels:
      caddy: "${DOMAIN}"
      caddy.reverse_proxy_0: /outpost.goauthentik.io/* https://${AUTHENTIK_URL}
      caddy.reverse_proxy_0.header_up: Host {http.reverse_proxy.upstream.hostport}
      caddy.reverse_proxy_1: "{{upstreams 8080}}"
      caddy.forward_auth_1: https://${AUTHENTIK_URL}
      caddy.forward_auth_1.uri: /outpost.goauthentik.io/auth/caddy
      caddy.forward_auth_1.copy_headers: X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version
      caddy.forward_auth_1.trusted_proxies: private_ranges
```

This generates me this caddyfile:
```
${DOMAIN} {
	forward_auth ${AUTHENTIK_URL} {
		copy_headers X-Authentik-Username X-Authentik-Groups X-Authentik-Email X-Authentik-Name X-Authentik-Uid X-Authentik-Jwt X-Authentik-Meta-Jwks X-Authentik-Meta-Outpost X-Authentik-Meta-Provider X-Authentik-Meta-App X-Authentik-Meta-Version
		trusted_proxies private_ranges
		uri /outpost.goauthentik.io/auth/caddy
	}
	reverse_proxy /outpost.goauthentik.io/* https://${AUTHENTIK_URL} {
		header_up Host {http.reverse_proxy.upstream.hostport}
	}
	reverse_proxy 172.21.0.4:8080
}
```

I hope this helps.
