### ISSUE TITLE
podman: "Container is not in same network as caddy"

### ISSUE THREAD

**Issue by jck** [lucaslorentz/caddy-docker-proxy#426]
I tried running caddy-docker-proxy in podman(rootless) with the changes from #415

```yaml
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_NO_SCOPE=true
    networks:
      - caddy
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  whoami:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      caddy: localhost
      caddy.reverse_proxy: "{{upstreams 8000}}"

networks:
  caddy:
    external: true
```

logs:

```
{"level":"info","ts":1669218206.1535568,"logger":"docker-proxy","msg":"Running caddy proxy server"}
{"level":"info","ts":1669218206.154488,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1669218206.154981,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1669218206.1549895,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
{"level":"info","ts":1669218206.2833998,"logger":"docker-proxy","msg":"Start","CaddyfilePath":"","LabelPrefix":"caddy","PollingInterval":30,"ProcessCaddyfile":true,"ProxyServiceTasks":true,"IngressNetworks":"[caddy]","DockerSockets":[""],"DockerCertsPath":[""],"DockerAPIsVersion":[""]}
{"level":"info","ts":1669218206.2848902,"logger":"docker-proxy","msg":"Connecting to docker events","DockerSocket":""}
{"level":"info","ts":1669218206.3169343,"logger":"docker-proxy","msg":"IngressNetworksMap","ingres":"map[bcc7ef4bef8b09b6e23ff8691dd3680026251b8411743b36c6b9a5e4965e1f45:true]"}
{"level":"info","ts":1669218206.6025436,"logger":"docker-proxy","msg":"Swarm is available","new":false}
{"level":"info","ts":1669218206.607327,"logger":"docker-proxy","msg":"New Caddyfile","caddyfile":"# Empty caddyfile"}
{"level":"warn","ts":1669218206.6076214,"logger":"docker-proxy","msg":"Caddyfile to json warning","warn":"[Caddyfile:1: Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies]"}
{"level":"info","ts":1669218206.6076322,"logger":"docker-proxy","msg":"New Config JSON","json":"{}"}
{"level":"info","ts":1669218206.6076598,"logger":"docker-proxy","msg":"Sending configuration to","server":"localhost"}
{"level":"info","ts":1669218206.608379,"logger":"admin.api","msg":"received request","method":"POST","host":"localhost:2019","uri":"/load","remote_ip":"127.0.0.1","remote_port":"41132","headers":{"Accept-Encoding":["gzip"],"Content-Length":["41"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}
{"level":"info","ts":1669218206.608439,"msg":"config is unchanged"}
{"level":"info","ts":1669218206.6084473,"logger":"admin.api","msg":"load complete"}
{"level":"info","ts":1669218206.6085486,"logger":"docker-proxy","msg":"Successfully configured","server":"localhost"}
podman start -a caddy_whoami_1
Listening on :8000
{"level":"warn","ts":1669218207.2242162,"logger":"docker-proxy","msg":"Container is not in same network as caddy","container":"4c53f635c6349b05d207faebc392ad1bee53ba8e9990c27078c98ff9f464312b","container id":"4c53f635c6349b05d207faebc392ad1bee53ba8e9990c27078c98ff9f464312b"}
{"level":"info","ts":1669218207.2252214,"logger":"docker-proxy","msg":"New Caddyfile","caddyfile":"localhost {\n\treverse_proxy\n}\n"}
{"level":"info","ts":1669218207.225539,"logger":"docker-proxy","msg":"New Config JSON","json":"{\"apps\":{\"http\":{\"servers\":{\"srv0\":{\"listen\":[\":443\"],\"routes\":[{\"match\":[{\"host\":[\"localhost\"]}],\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"reverse_proxy\"}]}]}],\"terminal\":true}]}}}}}"}
```

caddy-docker-proxy thinks that the Container is not in same network as caddy but they are:

`podman-compose exec caddy curl --silent -XGET --unix-socket /var/run/docker.sock http://localhost/networks`

```json
[
  {
    "Name": "caddy",
    "Id": "bcc7ef4bef8b09b6e23ff8691dd3680026251b8411743b36c6b9a5e4965e1f45",
    "Created": "2022-11-23T15:27:15.599265753Z",
    "Scope": "local",
    "Driver": "bridge",
    "EnableIPv6": false,
    "IPAM": {
      "Driver": "default",
      "Options": {
        "driver": "host-local"
      },
      "Config": [
        {
          "Subnet": "10.89.0.0/24",
          "Gateway": "10.89.0.1"
        }
      ]
    },
    "Internal": false,
    "Attachable": false,
    "Ingress": false,
    "ConfigFrom": {
      "Network": ""
    },
    "ConfigOnly": false,
    "Containers": {
      "4c53f635c6349b05d207faebc392ad1bee53ba8e9990c27078c98ff9f464312b": {
        "Name": "caddy_whoami_1",
        "EndpointID": "",
        "MacAddress": "26:02:59:30:8b:62",
        "IPv4Address": "10.89.0.36/24",
        "IPv6Address": ""
      },
      "5b8f9575b1bdef566b0a3c77cdee55be16778058b77789da6c7b49d40cbf1893": {
        "Name": "caddy_caddy_1",
        "EndpointID": "",
        "MacAddress": "02:41:d2:3a:11:77",
        "IPv4Address": "10.89.0.35/24",
        "IPv6Address": ""
      }
    },
    "Options": {},
    "Labels": {}
  },
  {
    "Name": "bridge",
    "Id": "2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9",
    "Created": "2022-11-23T15:43:26.284867232Z",
    "Scope": "local",
    "Driver": "bridge",
    "EnableIPv6": false,
    "IPAM": {
      "Driver": "default",
      "Options": {
        "driver": "host-local"
      },
      "Config": [
        {
          "Subnet": "10.88.0.0/16",
          "Gateway": "10.88.0.1"
        }
      ]
    },
    "Internal": false,
    "Attachable": false,
    "Ingress": false,
    "ConfigFrom": {
      "Network": ""
    },
    "ConfigOnly": false,
    "Containers": {},
    "Options": {},
    "Labels": {}
  }
]
```

**Comment by lucaslorentz** [comment]
Yeah, the network looks correct.
Can you please "docker inspect" your container and share the json as well?
CDP [tries to find the network from the container config](https://github.com/lucaslorentz/caddy-docker-proxy/blob/338fd6b3be74d205b2eb77d76ba76ff741c6ce81/generator/containers.go#L20
), maybe podman doesn't return the networks as we expect.

**Comment by lucaslorentz** [comment]
Yeah, there is a mismatch, the network ID field should contain the id but podman returns the name.
Maybe we can change our matching logic to compare against networkID or Name.

**Comment by jck** [comment]
Yeah, that makes sense. It might be a podman bug or api incompatibility. Are there any downsides to change our matching logic to use the name instead of ID?

**Comment by lucaslorentz** [comment]
No, I don't think so.
Change is very small as well. I've done it in https://github.com/lucaslorentz/caddy-docker-proxy/pull/427
Wonder if you would like to test it before it's merged.

Btw, I never tried podman, so this might not be the only issue blocking it.

**Comment by jck** [comment]
I just tested it and it works for me!

For the future people who get here through google, the docker-compose.yaml in the first comment works. Note that both the env vars are needed.

**Comment by MatYRicS** [comment]
@lucaslorentz I still get the error `Container is not in same network as caddy` even tho I used the same docker-compose file but instead build a custom image of caddy with caddy-docker-proxy and cloudflare included.

My `Dockerfile` looks like this:
```
ARG CADDY_VERSION=2.6.2
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2@v2.8.1 \
    --with github.com/caddy-dns/cloudflare

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```
And my docker-compose.yaml look like this:
```
version: "3.7"

services:
  caddy:
    image: localhost/caddy:cloudflare
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_NO_SCOPE=true
    networks:
      - caddy
    labels:
      - caddy.email=<email>
      - caddy.acme_dns=cloudflare <key>
      - caddy.acme_ca=https://acme-staging-v02.api.letsencrypt.org/directory
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - ~/caddy/caddy_data:/data
    restart: unless-stopped

  whoami:
    image: jwilder/whoami
    networks:
      - caddy
    labels:
      - caddy=<domain>
      - caddy.1_@whoami=host <subdomain>
      - caddy.1_handle=@whoami
      - caddy.1_handle.reverse_proxy="{{upstreams 8000}}"

networks:
  caddy:
    external: true
```

Also I'm seeing this error in my `caddy-docker-proxy` container:
```
{"level":"info","ts":1674747555.824215,"logger":"docker-proxy","msg":"Connecting to docker events","DockerSocket":""}
{"level":"error","ts":1674747555.8250782,"logger":"docker-proxy","msg":"Docker events error","error":"EOF"}
```
Seems to be related to this #415

In my `Dockerfile` I added `@v2.8.1 ` but I don't think it is pulling the newest release and use that since I get these errors. If I try to use `lucaslorentz/caddy-docker-proxy:ci-alpine` everything is working fine.
