### ISSUE TITLE
Shorthand for transparent proxy

### ISSUE THREAD

**Issue by blazeu** [lucaslorentz/caddy-docker-proxy#43]
Currently, to do transparent proxy, I have to do this (based on [test file](https://github.com/lucaslorentz/caddy-docker-proxy/blob/70cf05797b20757158e3128d87d57f8eba3784e5/plugin/generator_test.go#L149))

```yml
caddy: host.com
caddy.proxy: "/ service_name:80"
caddy.proxy.transparent: ""
```

I had to type the service name again and use 3 labels, instead of 2 or even a single label if https://github.com/lucaslorentz/caddy-docker-proxy/issues/12 was solved somehow.
