### ISSUE TITLE
Running Caddy Docker Proxy on host networking

### ISSUE THREAD

**Issue by PixelHir** [lucaslorentz/caddy-docker-proxy#432]
Hi, is it possible to run caddy-docker-proxy on host networking so I don't need to assign it to same networks as the containers? I used to do that with traefik and wanted to replicate this on cdp but I'm encountering problems as below:

![image](https://user-images.githubusercontent.com/7670940/204660847-e20c4780-6647-48a3-b120-5e64edc535ac.png)
I've setup a basic whoami container for testing purposes, but I am unable to access it

I'm able to access the said container from the host network
![image](https://user-images.githubusercontent.com/7670940/204660953-ce6f85e4-3d70-4ba0-bf27-80d5dfa64242.png)

My docker compose:
![image](https://user-images.githubusercontent.com/7670940/204661154-0823f43d-f6d5-4f13-a6ce-6ffc40c22065.png)

**Comment by OnigamiSama** [comment]
Hello,

I run mine in network mode host for a few weeks and everything seems to work fine with this docker-compose.yml

```
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    network_mode: host
#    ports:
#      - 80:80
#      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
#    networks:
#      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

#networks:
#  caddy:
#    external: true

volumes:
  caddy_data: {}
```

**Comment by psyciknz** [comment]
The container I’m trying to proxy has to be in host network (homebridge), what are the labels to get this to work, as mine in complaining they are not in the same network

**Comment by OnigamiSama** [comment]
Here is an exemple, my docker-compose for plexmediaserver in host mode networking with caddy-docker-proxy

```
services:
  plex:
    image: lscr.io/linuxserver/plex
    runtime: nvidia
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ~/docker/containers/plex/config:/config
      - /zdata/mediaserver/library:/mnt/mediaserver/library:ro
      - ~/docker/containers/plex/transcode:/tmp
    labels:
      caddy: sub.domain.tld
      caddy.reverse_proxy: host.docker.internal:32400
    restart: unless-stopped
```
