### ISSUE TITLE
Curious issue with variables.

### ISSUE THREAD

**Issue by psyciknz** [lucaslorentz/caddy-docker-proxy#435]
So I have a caddy file with 
```
*.{$CADDYHOST}-internal2.andc.nz {
        tls letsencrypt@andc.nz {
                dns cloudflare {$CLOUDFLARE_API_KEY}
        }
        log
}

*.drogo-internal.andc.nz {
        tls letsencrypt@andc.nz {
                dns cloudflare {$CLOUDFLARE_API_KEY}
        }
        log
}
```
Where CADDYFILE - populated from .env = drogo - again lower case.   As far as I can tell no lf/cr is being picked up.   To make it take effect I was swapping the -internal for internal2.

With the hard coded *.drogo.internal.andc.nz - all is fine.
But with the one with the variable name, I'd start getting errors with duplicate blocks, and none of my containers with labels. Would create a match.   For the containers, they were still generally hard coded - but I did try one also with a variable name, and it acted the same as the hard coded ones.

But something in the use of the variable in the Caddyfile was causing it to complain.
```
{"level":"info","ts":1670561213.845744,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: duplicate site address not allowed: '*.drogo-internal.andc.nz' in [*.drogo-internal.andc.nz] (site block 2, key 0)\n*.drogo-internal.andc.nz {\n\t@books host books.drogo-internal.andc.nz\n\t@lidarr host lidarr.drogo-internal.andc.nz\n\t@nextcloud host nextcloud.drogo-internal.andc.nz\n\t@photos host photos.drogo-internal.andc.nz\n\t@radarr host radarr.drogo-internal.andc.nz\n\t@sonarr host sonarr.drogo-internal.andc.nz\n\t@traccar host traccar.drogo-internal.andc.nz\n\troute {\n\t\treverse_proxy @books 172.26.0.3:8083\n\t\treverse_proxy @lidarr 172.26.0.10:8686\n\t\treverse_proxy @nextcloud 172.26.0.2:80\n\t\treverse_proxy @photos 172.26.0.8:2342\n\t\treverse_proxy @radarr 172.26.0.4:7878\n\t\treverse_proxy @sonarr 172.26.0.9:8989\n\t\treverse_proxy @traccar 172.26.0.5:8082\n\t\trespond 403\n\t}\n}\n\n"}
```

**Comment by psyciknz** [comment]
hmm I took out the {} on the variable name:
```
*.$HOSTNAME-internal.andc.nz {
        tls letsencrypt@andc.nz {
                dns cloudflare {$CLOUDFLARE_API_KEY}
        }
        log
}
```
And now the sites have started responding.....but I might have lost logging....have I got an encoding error?

**Comment by francislavoie** [comment]
There's some information missing here. What's in your Docker labels?

I think the error message is pretty clear. You have duplicate site addresses.

> hmm I took out the {} on the variable name:

That's not right; the braces are necessary for env var syntax. Without it, you're literally using `$HOSTNAME` as part of the domain name, which doesn't make sense.

**Comment by psyciknz** [comment]
Case has changed. As I've altered things since posting the issue in the home that hope it was that. 

Here are the caddy labels
```

environment:
      - ACME_AGREE=true
      - LETSENCRYPT_EMAIL=letsencrypt@andc.nz
      - CLOUDFLARE_EMAIL=cloudflare@andc.nz
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CADDY_INGRESS_NETWORKS=caddy-proxy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
      - hostname=${hostname}
```

With the .env file
```
hostname=drogo
```

And obviously the keys mentioned in the other labels for setting cloudflare 

Do you want the labels for the sites?

**Comment by psyciknz** [comment]
Message about duplicates might be obvious, yes, but how the duplicates are being created less so.  And this is where I can't see how to resolve it.

**Comment by francislavoie** [comment]
You defined the environment variable as `hostname=${hostname}`, but used it as `{$CADDYHOST}`. That's not the same. Also, environment variables are case-sensitive. Make sure they match.

As an aside, you don't need `ACME_AGREE=true` anymore. That was a Caddy v1 thing only.

**Comment by psyciknz** [comment]
I had tried CADDYHOST in all locations after trying HOSTNAME at some point and then later hostname.

These where all attempts to make sure that I was not clashing with any system variables as I know $hostname is a bit of a system variable.

Regardless of what I set the variable to the logs seemed to say that the correct wildcard existed, the containers didn't seem to get a match to create their entries

**Comment by francislavoie** [comment]
You haven't answered this question:

> There's some information missing here. What's in your Docker labels?

We need to see what your whole Docker stack looks like, to understand what labels you're putting on containers, to see how it all plays together.

**Comment by psyciknz** [comment]
Yep, ok I'll reset it to CADDYHOST and post.

Docker compose for caddy.
```
environment:
      - LETSENCRYPT_EMAIL=letsencrypt@andc.nz
      - CLOUDFLARE_EMAIL=cloudflare@andc.nz
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CADDY_INGRESS_NETWORKS=caddy-proxy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
      - CADDYHOST=${CADDYHOST}
```

.env file
```
CADDYHOST=drogo
```

Caddyfile
```
*.${CADDYHOST}-internal.andc.nz {
        tls letsencrypt@andc.nz {
                dns cloudflare {$CLOUDFLARE_API_KEY}
        }
        log
}
```

Here's two containers from my media stack that use it - I started updating those with CADDYHOST as well.  Unsure if I do or don't need the CADDYHOST=${CADDYHOST} in the environment section to pull it from .env file.
```
################################################################################
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    mem_limit: 400m
    environment:
      - TZ=Pacific/Auckland
      - PUID=1000
      - PGID=1000
      - BASEPATH=/hdd/docker-data
      - SERVERFOLDERS=/media/serverfolders
      - HDDBASEPATH=/hdd
      - CADDYHOST=${CADDYHOST}
    healthcheck:
      # I tried adding '&& exit 1',  '|| exit `' it doesn't work.
      test: bash -c "[ -f /movies/movie.nfo ]"
      interval: 5m
      timeout: 30s
      retries: 20
    labels:
      - "autoheal=true"
      - com.centurylinklabs.watchtower.enable=true
      - caddy=*.${CADDYHOST}-internal.andc.nz
      - caddy.@radarr=host radarr.${CADDYHOST}-internal.andc.nz
      - caddy.route.1_reverse_proxy=@radarr "{{ upstreams 7878 }}"
    dns:
      - 192.168.10.1
      - 192.168.10.253
    networks:
      - media
      - caddy-proxy
    ports:
      - 8093:7878
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${BASEPATH}/media/radarr:/config
      - ${SERVERFOLDERS}/Videos:/movies
      - ${HDDBASEPATH}/sabnzbd/downloads:/downloads
    restart: always
################################################################################
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    mem_limit: 400m
    environment:
      - TZ=Pacific/Auckland
      - PUID=1000
      - PGID=1000
      - BASEPATH=/hdd/docker-data
      - SERVERFOLDERS=/media/serverfolders
      - HDDBASEPATH=/hdd
    healthcheck:
      # I tried adding '&& exit 1',  '|| exit `' it doesn't work.
      test: bash -c "[ -f /tv/movie.nfo ]"
      interval: 5m
      timeout: 30s
      retries: 20
    labels:
      - "autoheal=true"
      - com.centurylinklabs.watchtower.enable=true
      - caddy=*.${CADDYHOST}-internal.andc.nz
      - caddy.@sonarr=host sonarr.${CADDYHOST}-internal.andc.nz
      - caddy.route.1_reverse_proxy=@sonarr "{{ upstreams 8989 }}"
    dns:
      - 192.168.10.1
      - 192.168.10.253
    networks:
      - media
      - caddy-proxy
    ports:
      - 8097:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${BASEPATH}/media/sonarr:/config
      - "${SERVERFOLDERS}/Recorded\ TV:/tv"
      - ${HDDBASEPATH}/sabnzbd/downloads:/downloads
    restart: always
################################################################################
```

here are teh log entries after caddy was up and running, and same with teh two media containers - then I forced a restart of the radarr container - and it regenerated the config.
```
{"level":"info","ts":1670569143.3122137,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0003804d0"}
{"level":"info","ts":1670569143.85287,"logger":"docker-proxy","msg":"New Caddyfile","caddyfile":"*.${CADDYHOST}-internal.andc.nz {\n\ttls letsencrypt@andc.nz {\n\t\tdns cloudflare {$CLOUDFLARE_API_KEY}\n\t}\n\tlog\n}\n*.drogo-internal2.andc.nz {\n\ttls letsencrypt@andc.nz {\n\t\tdns cloudflare {$CLOUDFLARE_API_KEY}\n\t}\n\tlog\n}\n*.drogo-internal.andc.nz {\n\t@books host books.drogo-internal.andc.nz\n\t@lidarr host lidarr.drogo-internal.andc.nz\n\t@nextcloud host nextcloud.drogo-internal.andc.nz\n\t@photos host photos.drogo-internal.andc.nz\n\t@radarr host radarr.drogo-internal.andc.nz\n\t@sonarr host sonarr.drogo-internal.andc.nz\n\t@traccar host traccar.drogo-internal.andc.nz\n\troute {\n\t\treverse_proxy @books 172.26.0.3:8083\n\t\treverse_proxy @lidarr 172.26.0.10:8686\n\t\treverse_proxy @nextcloud 172.26.0.2:80\n\t\treverse_proxy @photos 172.26.0.8:2342\n\t\treverse_proxy @radarr 172.26.0.4:7878\n\t\treverse_proxy @sonarr 172.26.0.9:8989\n\t\treverse_proxy @traccar 172.26.0.5:8082\n\t\trespond 403\n\t}\n}\n*.internal.andc.nz {\n\t@reader host reader.internal.andc.nz\n\t@reader2 host reader.drogo-internal.andc.nz\n\treverse_proxy @reader 172.26.0.6:80\n}\n"}
{"level":"info","ts":1670569143.8537285,"logger":"docker-proxy","msg":"New Config JSON","json":"{\"apps\":{\"http\":{\"servers\":{\"srv0\":{\"listen\":[\":443\"],\"routes\":[{\"match\":[{\"host\":[\"*.drogo-internal2.andc.nz\"]}],\"terminal\":true},{\"match\":[{\"host\":[\"*.drogo-internal.andc.nz\"]}],\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.3:8083\"}]}],\"match\":[{\"host\":[\"books.drogo-internal.andc.nz\"]}]},{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.10:8686\"}]}],\"match\":[{\"host\":[\"lidarr.drogo-internal.andc.nz\"]}]},{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.2:80\"}]}],\"match\":[{\"host\":[\"nextcloud.drogo-internal.andc.nz\"]}]},{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.8:2342\"}]}],\"match\":[{\"host\":[\"photos.drogo-internal.andc.nz\"]}]},{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.4:7878\"}]}],\"match\":[{\"host\":[\"radarr.drogo-internal.andc.nz\"]}]},{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.9:8989\"}]}],\"match\":[{\"host\":[\"sonarr.drogo-internal.andc.nz\"]}]},{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.5:8082\"}]}],\"match\":[{\"host\":[\"traccar.drogo-internal.andc.nz\"]}]},{\"handle\":[{\"handler\":\"static_response\",\"status_code\":403}]}]}]}]}],\"terminal\":true},{\"match\":[{\"host\":[\"*.${CADDYHOST}-internal.andc.nz\"]}],\"terminal\":true},{\"match\":[{\"host\":[\"*.internal.andc.nz\"]}],\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.26.0.6:80\"}]}],\"match\":[{\"host\":[\"reader.internal.andc.nz\"]}]}]}],\"terminal\":true}],\"logs\":{\"skip_hosts\":[\"*.drogo-internal.andc.nz\",\"*.internal.andc.nz\"]}}}},\"tls\":{\"automation\":{\"policies\":[{\"subjects\":[\"*.drogo-internal2.andc.nz\",\"*.${CADDYHOST}-internal.andc.nz\"],\"issuers\":[{\"challenges\":{\"dns\":{\"provider\":{\"api_token\":\"REDACTED\",\"name\":\"cloudflare\"}}},\"email\":\"letsencrypt@andc.nz\",\"module\":\"acme\"},{\"challenges\":{\"dns\":{\"provider\":{\"api_token\":\"REDACTED\",\"name\":\"cloudflare\"}}},\"email\":\"letsencrypt@andc.nz\",\"module\":\"zerossl\"}]},{\"subjects\":[\"*.drogo-internal.andc.nz\",\"*.internal.andc.nz\"]}]}}}}"}
{"level":"error","ts":1670569153.312518,"logger":"admin","msg":"stopping current admin endpoint","error":"shutting down admin server: context deadline exceeded"}
```

I can't tell looking at these log lines if the variables are being resolved properly.  But at the moment its in that state where it actually works (or is cached somehow), I'm just not getting any logging from caddy.

**Comment by Mikle-Bond** [comment]
Hey, @psyciknz 

It's almost anniversary of this issue ticket of yours. I wanted to hear if you solved it in any way.  If yes, would you mind sharing the config you've built? I kinda want to host sonarr/radarr myself, and having a working template would help.

Anyway, back to the issue.
The logs you've posted say that the final config looks like this

```caddy
*.-internal.andc.nz {
	tls letsencrypt@andc.nz {
		dns cloudflare {}
	}
	log
}
*.drogo-internal2.andc.nz {
	tls letsencrypt@andc.nz {
		dns cloudflare {}
	}
	log
}
*.drogo-internal.andc.nz {
	@books host books.drogo-internal.andc.nz
	@lidarr host lidarr.drogo-internal.andc.nz
	@nextcloud host nextcloud.drogo-internal.andc.nz
	@photos host photos.drogo-internal.andc.nz
	@radarr host radarr.drogo-internal.andc.nz
	@sonarr host sonarr.drogo-internal.andc.nz
	@traccar host traccar.drogo-internal.andc.nz
	route {
		reverse_proxy @books 172.26.0.3:8083
		reverse_proxy @lidarr 172.26.0.10:8686
		reverse_proxy @nextcloud 172.26.0.2:80
		reverse_proxy @photos 172.26.0.8:2342
		reverse_proxy @radarr 172.26.0.4:7878
		reverse_proxy @sonarr 172.26.0.9:8989
		reverse_proxy @traccar 172.26.0.5:8082
		respond 403
	}
}
*.internal.andc.nz {
	@reader host reader.internal.andc.nz
	@reader2 host reader.drogo-internal.andc.nz
	reverse_proxy @reader 172.26.0.6:80
}
```
The very first block shows that it didn't expand the variable (right so, as `*.${CADDYHOST}-internal.andc.nz` is not a correct syntax). Maybe try using the `{env.CADDYHOST}` syntax instead?

---

And as a reminder, for anyone who happens to find this issue in the future. There's one peculiar mistake that is often made.

When working with `docker compose`, it will expand variables itself for most of the values. Example:

`docker-compose.yaml`:
```yaml
name: weird
services:
  test:
    image: alpine
    command: 'echo ${MY_VAR}'
    environment:
      MY_VAR: set in docker-compose.yml
```

`.env`:
```yaml
MY_VAR="set in .env file"
```

Running this will output to the logs `set in .env file`, as that string will be hardcoded into the command.

Not that it affects you in particular, but I like to remind about it more often on the Internet, for anyone who struggles.

**Comment by psyciknz** [comment]
I don’t think I did actually.  In the mean time I’d implanted pihole.  And use cname records to point at the correct host. 

Or I would have used a host specific caddy file by using file mapping in the docker volume commands.

**Comment by pcfreak30** [comment]
Posting this for documentation. oddly the `{env.}` caddy var syntax didn't work. This did:

```
        labels:
            caddy_0: "DOMAIN"
            caddy_0.reverse_proxy: "UPSTREAM 8080"
            caddy_0.tls.dns: "cloudflare ${CLOUDFLARE_API_TOKEN}"
```

`CLOUDFLARE_API_TOKEN` is defined  in a `.env` file and loaded via 

```       
 env_file:
            - .env          
```

Not as good to generate the secret direct IN the caddy config but its a starting point.

Hope this helps someone!

Kudos.
