### ISSUE TITLE
reverse_proxy and buffer_requests

### ISSUE THREAD

**Issue by woss** [lucaslorentz/caddy-docker-proxy#438]
Hi,  I'm trying to get this portion of my caddyfile transfer to the CDP. so far this doesn't work:

Caddyfile:
```
ipfs.anagolay.network {
        # ipfs api
        reverse_proxy /api/* {
                to 127.0.0.1:3000

                # this part i cannot figure out that it works

                flush_interval -1
                buffer_requests
                header_down Access-Control-Allow-Origin *
                header_down Access-Control-Allow-Methods "POST"
                header_down Access-Control-Allow-Headers *

               # this part i cannot figure out that it works
        }
        # ipfs gateway
        reverse_proxy /ipfs/* {
                to 127.0.0.1:8080
        }
}
```

docker-compose file
```yaml
  macula_ipfs_api:
    image: kelpdigital/macula:83b8ec4
    restart: unless-stopped
    environment:
      - IPFS_API_URL=http://ipfs:5001
    labels:
      caddy: 'api.ipfs.my.link'
      caddy.rewrite: '* /ipfs{uri}'   << works
      caddy.reverse_proxy.to: '{{upstreams 3000}}' << works
      caddy.reverse_proxy.flush_interval: -1 
      caddy.reverse_proxy.buffer_requests: 1
      caddy.reverse_proxy.header_down.0:  Access-Control-Allow-Origin *
      caddy.reverse_proxy.header_down.1:  Access-Control-Allow-Methods "POST"
      caddy.reverse_proxy.header_down.2:  Access-Control-Allow-Headers *
```

IPFS API needs to buffer requests since they are multipart and streams.
Any help would be appreciated.  
thanks
