### ISSUE TITLE
No upstreams available when using a caddy reverse proxy

### ISSUE THREAD

**Issue by naft-a** [lucaslorentz/caddy-docker-proxy#448]
Hello, I'm trying to use this pluging for my local project but I'm struggling to make it all work with my current configuration. I have a docker compose file with some services inside (one of which is caddy) and I simply want to reverse proxy the app service through caddy so that I can access it by fetching `tags.localhost` hostname from the host os on port `443`

I followed the docs but I'm getting this error when I point things at this hostname:

```
tags-service-caddy-1  | {"level":"error","ts":1673175056.6896346,"logger":"http.log.error","msg":"no upstreams available","request":{"remote_ip":"192.168.80.1","remote_port":"60426","proto":"HTTP/2.0","method":"GET","host":"tags.localhost","uri":"/","headers":{"Accept-Encoding":["gzip, deflate, br"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Accept-Language":["en-GB,en;q=0.5"],"Upgrade-Insecure-Requests":["1"],"Sec-Fetch-Site":["cross-site"],"Te":["trailers"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"tags.localhost"}},"duration":0.000410916,"status":503,"err_id":"kczc8y3j7","err_trace":"reverseproxy.(*Handler).proxyLoopIteration (reverseproxy.go:524)"}
tags-service-caddy-1  | {"level":"warn","ts":1673175082.0862164,"logger":"docker-proxy","msg":"Container is not in same network as caddy","container":"b58813afb9520c52a84614dba07265e7423fe7cde9128d129e3f09b1e053ccd1","container id":"b58813afb9520c52a84614dba07265e7423fe7cde9128d129e3f09b1e053ccd1"}

```

I'm also a bit confused why it raises a warning there for my container `app` not being found inside the same network as `caddy`. 

Essentially I just want to apply this config to caddy:
```
tags.localhost {
  reverse_proxy app:5002
  tls internal
}
```

This is my `docker-compose.yml` file:
```
version: "3.9"

services:

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - tags_service_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    networks:
      - tags_service_network
    volumes:
      - db:/data/db

  app:
    image: basics/tags-service
    depends_on:
      - mongo
    build:
      context: .
    networks:
      - tags_service_network
    labels:
      caddy: tags.localhost
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 5002}}"
    environment:
      RACK_ENV: production
      MONGODB_HOST: mongo:27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: secret
      MONGODB_DATABASE: tags-service-dev

volumes:
  caddy_data: {}
  db:
    driver: local

networks:
  tags_service_network:
    external: true
```

Any help appreciated!
