### ISSUE TITLE
[Help] Is there a way to configure using staging environment of Let's Encrypt?

### ISSUE THREAD

**Issue by momocow** [lucaslorentz/caddy-docker-proxy#46]
I'm using the docker image of this project as the entrance of my services.
However, I forgot to expose 80 port (exposed 443 port only) so the HTTP challenges failed, and due to the restart policy, the container restarted again and again and thus the rate limit of Let's Encrypt was hit.

I am wondering if there is a way to configure Caddy-docker-proxy using [staging environment of Let's Encrypt](https://letsencrypt.org/docs/staging-environment/) until I make all my services work.

Thank you!

**Comment by momocow** [comment]
Good news for me, at least I only need to wait for an hour to test if I correct the problem.

> There is a Failed Validation limit of 5 failures per account, per hostname, per hour. This limit is higher on our staging environment, so you can use that environment to debug connectivity problems.
From [Rate Limits- Let's Encrypt](https://letsencrypt.org/docs/rate-limits/)

**Comment by lucaslorentz** [comment]
Hey @momocow 
Can you try the CLI mentioned in: https://caddy.community/t/caddy-support-letsencrypt-staging-ssl-certs/420 ?

**Comment by momocow** [comment]
Thanks, that is what I need.

**Comment by shoutmarble** [comment]
Sorry for asking, but I didn't quite follow the above solution...

Was there a solution to use the ACME Staging Directory in CDP in the Docker Compose file?

```YAML
version: "3.7"

networks:
    caddy:
        external: true

volumes:
    caddy_data: {}

services:    Is there a global directive to to use the ACME Staging TLS in the CDP YAML FILE  -----------+
    caddy:                                                                                               |
        image: lucaslorentz/caddy-docker-proxy:ci-alpine                                                 |
          command: ['docker-proxy', '-ca', 'https://acme-staging-v02.api.letsencrypt.org/directory']  <--+
          command: ['-ca', 'https://acme-staging.api.letsencrypt.org/directory']  <----------------------+
        ports:                                                                                           |
            - 80:80                                                                                      |
            - 443:443                                                                                    |
        environment:                                                                                     |
            - CADDY_INGRESS_NETWORKS=caddy                                                               |
        networks:                                                                                        |
            - caddy                                                                                      |
        volumes:                                                                                         |
            - /var/run/docker.sock:/var/run/docker.sock                                                  |
            - caddy_data:/data                                                                           |
        labels:                                                                                          | 
            - caddy.tls.ca="https://acme-staging-v02.api.letsencrypt.org/directory"  <-------------------+
        restart: unless-stopped
```
