### ISSUE TITLE
[question] caddy for https and reverse proxy with jellyfin local access only

### ISSUE THREAD

**Issue by ww2283** [lucaslorentz/caddy-docker-proxy#462]
I would like to use caddy to handle the https and reserve proxy with my jellyfin. I don't need outside connection but only internal local access. I read from some online tutorials that this is doable. I configured my compose yml like below, and didn't notice anything wrong from docker logs caddy or docker logs jellyfin. However, I cannot connect to https://jellyfin.local from browser. Would someone please take a look and give me some instructions? Thanks.
Compose yml:

```
 jellyfin:
    container_name: jellyfin
    image: cr.hotio.dev/hotio/jellyfin
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - JELLYFIN_CACHE_DIR=/cache
    networks:
      - caddy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /config:/config
      - /media:/media
    labels:
      caddy: https://jellyfin.local
      caddy.@local.remote_ip: 192.168.0.0/16 172.16.0.0/12
      caddy.reverse_proxy: "@local {{upstreams 80}}"


  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:2.8.3
    restart: 'unless-stopped'
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
      - default
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - caddy_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  caddy:
    external: true
```

**Comment by francislavoie** [comment]
Do you have a DNS server locally that resolves `jellyfin.local` to that machine? If not, that won't work. But also, `.local` domains are not ideal to use because they usually require an mDNS resolver for it to work. See https://en.wikipedia.org/wiki/.local

**Comment by ww2283** [comment]
thank you for pointing out the way! I'm very new to docker and networking settings. Would you mind suggesting some DNS server utilities? I will try and report back. Much appreciated!

**Comment by francislavoie** [comment]
If you're using something like pihole/adguard for DNS ad blocking, that supports custom domains. If not, then something like CoreDNS might do.

**Comment by ww2283** [comment]
I adjusted the yml for a simple case for caddy with adguardhome after consulting some closed issues here. I don't see any warning or error in docker logs and by looking at logs both containers are running. However I cannot access the webui of either one, e.g 192.168.xx.xx:2019 shows ERR_CONNECTION_TIMED_OUT. Greatly appreciate any advice!

```
version: "3.7"

services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:2.8.3
    restart: 'unless-stopped'
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /caddy/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      caddy_0: http://adguard.o
      caddy_0.reverse_proxy: host.docker.internal:3000

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /opt/adguardhome/conf:/opt/adguardhome/conf

networks:
  caddy:
    external: true
```
