### ISSUE TITLE
[question] caddy auto generate tls for adguard home

### ISSUE THREAD

**Issue by ww2283** [lucaslorentz/caddy-docker-proxy#464]
I thought the caddy would automatically generate certificate using internal method and help adguard home to use tls. I don't need domain register etc, but just want internal certificate and https on localhost. However, currently I'm not see it happen at adguard home webui under "Encryption Settings". I can only connect to http://server-ip to access the webui of adguard home. How may I automate the tls chain between caddy and adguard home, and potentially any other containers that are in the same network? 

My docker-compose.yaml after consulting many posts here:
```
version: "3.7"

services:
  caddy:
    container_name: caddy
    image: lucaslorentz/caddy-docker-proxy:2.8.3-alpine
    restart: 'unless-stopped'
    ports:
      - "81:80"
      - "444:443"
      - "2019:2019"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      caddy.log.format: console
      caddy.http_port: 81
      caddy.https_port: 444
      caddy_0.tls: internal
      caddy_0: local.adguardhome
      caddy_0.reverse_proxy: host.docker.internal:3000

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./adguardhome/opt/adguardhome/work:/opt/adguardhome/work
      - ./adguardhome/opt/adguardhome/conf:/opt/adguardhome/conf


networks:
  caddy:
    external: true
```
