### ISSUE TITLE
Oddball question about using `abort` directive

### ISSUE THREAD

**Issue by disl-pdavid** [lucaslorentz/caddy-docker-proxy#468]
I'm sorry if this is the wrong place for this, but I wasn't quite sure how to frame the question.

I'd like to abort any connections to my sites that have a URL of the form (from nginx logs):

```
nginx  | 172.18.0.2 - - [01/Mar/2023:20:43:02 +0000] "GET /?URL=http%3A%2F%2Fremmont.com%2F%3Fs%3Dcredit%2Bcards%2Bwith%2Bzero%2Binterest%2Bfor%2B
%2Bmonths HTTP/1.1" 200 6692 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)" "185.191.171.18"
```

(Don't ask - old legacy site had a problem by allowing itself to be used as an open proxy.  This has since been closed).

I was thinking the `abort` directive made the most sense as I don't even want to respond to the request, just drop it and move on.
The `docker-compose.yml` for my nginx container looks like this:

```yaml
version: "3"

services:
  web:
    image: nginx:latest
    container_name: "nginx"
    restart: unless-stopped
    volumes:
      - ./sites:/usr/share/nginx/html
      - ./conf:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    labels:
      caddy_1: www.mywebsite.com
      caddy_1.reverse_proxy: "{{upstreams 80}}"
      caddy_1.abort: /?URL*
    networks:
      - caddy

networks:
  caddy:
    external: true
```

I'm not quite sure how to do the translation to labels for this. Am I on the right path or barking up the wrong tree?
