### ISSUE TITLE
Mailu Support

### ISSUE THREAD

**Issue by kaaax0815** [lucaslorentz/caddy-docker-proxy#470]
I want to setup Mailu
<details><summary>mailu docker-compose.yml</summary>
<p>

```yml
version: '2.2'

services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/docker/mailu/data/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    logging:
      driver: json-file
    ports:
      - "8080:80"
      - "127.0.0.1:25:25"
      - "127.0.0.1:465:465"
      - "127.0.0.1:587:587"
      - "127.0.0.1:110:110"
      - "127.0.0.1:995:995"
      - "127.0.0.1:143:143"
      - "127.0.0.1:993:993"
    volumes:
      - "/docker/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.kaaaxcreators.de:/certs:ro"
      - "/docker/mailu/data/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker/mailu/data/mailu:/data"
      - "/docker/mailu/data/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker/mailu/data/mail:/mail"
      - "/docker/mailu/data/overrides/dovecot:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker/mailu/data/mailqueue:/queue"
      - "/docker/mailu/data/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  antispam:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
    hostname: antispam
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker/mailu/data/filter:/var/lib/rspamd"
      - "/docker/mailu/data/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  # Optional services
  # Webmail
  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rainloop:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/docker/mailu/data/webmail:/data"
      - "/docker/mailu/data/overrides/rainloop:/overrides:ro"
    depends_on:
      - imap
      - resolver
    dns:
      - 192.168.203.254

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
```
</p>
</details>

<details><summary>caddy docker-compose-yml</summary>
<p>

```yml
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/data/Caddyfile
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/caddy/data:/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  caddy:
    external: true
```
</p>
</details>

I tried adding mailu-front to the network with labels and everything, but then mailu breaks because of the dns configuration

I tried using a Caddyfile and setting `reverse_proxy host.docker.internal:8080` but I get `dial tcp 172.17.0.1:8080: i/o timeout`

Disabling ufw fixes the issue
