### ISSUE TITLE
invalid registration

### ISSUE THREAD

**Issue by cblomart** [lucaslorentz/caddy-docker-proxy#48]
When i try to create my docker swarm service:
2018/07/21 08:57:41 registration error: acme: Error 400 - urn:ietf:params:acme:error:invalidEmail - Error creating new account :: not a valid e-mail address

Here is the composer file:
```yaml
version: '3.3'
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    command: -agree -email c*@*.com
    ports:
     - 80:80
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/volumes/caddy:/root/.caddy
    networks:
     - caddy
    logging:
      driver: json-file
networks:
  caddy:
    external: true
```
