### ISSUE TITLE
[Question] How to identify network variables for CDP in Distributed mode

### ISSUE THREAD

**Issue by eazylaykzy** [lucaslorentz/caddy-docker-proxy#483]
I've been trying to figure this out for days, I was wondering how do one know how to map the correct network to `CADDY_CONTROLLER_NETWORK` environment variable and  `subnet` from the network configuration of the controller, I'm not big on networking, I've been trying to figure this out with no luck.
> 
> **Controller**
> 
> ```yaml
>     environment:
>       - CADDY_CONTROLLER_NETWORK=192.168.100.0/24
> ```
> 
> **Server**
> 
> ```yaml
>     environment:
>       - CADDY_CONTROLLER_NETWORK=192.168.100.0/24
> ```

```
  caddy_controller:
    driver: overlay
    ipam:
      driver: default
        config:
          - subnet: "10.200.200.0/24"
```

**Comment by eazylaykzy** [comment]
I was able to get through with this with the default values, problem I was having initially was due to Docker not being able to properly create a network with the `ipam` driver, this may be due to the fact I'm using Ansible, I had to do it properly with ansible this way;

```
- name: Create Caddy Controller Network
  docker_network:
    name: caddy_controller
    driver: overlay
    ipam_config:
      - subnet: 10.200.200.0/24
        gateway: 10.200.200.2
        iprange: 10.200.200.0/26
```
