### ISSUE TITLE
Usage with wildcard DNS?

### ISSUE THREAD

**Issue by BluDood** [lucaslorentz/caddy-docker-proxy#485]
Is it possible to assign and generate HTTPS certificates for a wildcard subdomain with this plugin? As an example, *.bar.example.com does not seem to correctly generate certificate for included subdomains like foo.bar.example.com and baz.bar.example.com. Is there another syntax for this?

This is what my configuration looks like:
```yml
labels:
      caddy: '*.bar.example.com'
      caddy.reverse_proxy: '{{upstreams 1337}}'
```

**Comment by BluDood** [comment]
For reference, manually specifying subdomains like this works fine:
```yml
labels:
      caddy: foo.bar.example.com, baz.bar.example.com
      caddy.reverse_proxy: '{{upstreams 1337}}'
```
