### ISSUE TITLE
Empty Caddyfile with labels in deploy section

### ISSUE THREAD

**Issue by mebeingken** [lucaslorentz/caddy-docker-proxy#488]
When running with a single node app container, everything works perfectly:

```
labels:
  caddy: caddytest.mealproapp.io
  caddy.reverse_proxy: "{{upstreams 3000}}"
```

I'm now trying to add replicas to the node app, so have updated the web section as follows:

```
deploy:
  labels:
    caddy: caddytest.mealproapp.io
    caddy.reverse_proxy: "{{upstreams 3000}}"
  replicas: 4
```

After re-deploying, the replicas are created, however I receive a connection refused on all requests.

I believe the Caddy logs are showing an empty Caddyfile:

```
{"level":"info","ts":1684278190.4112873,"logger":"docker-proxy","msg":"Running caddy proxy server"}
{"level":"info","ts":1684278190.4290354,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1684278190.430785,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1684278190.4308624,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
{"level":"info","ts":1684278190.4340458,"logger":"docker-proxy","msg":"Start","CaddyfilePath":"","LabelPrefix":"caddy","PollingInterval":30,"ProcessCaddyfile":true,"ProxyServiceTasks":true,"IngressNetworks":"[caddy]","DockerSockets":[""],"DockerCertsPath":[""],"DockerAPIsVersion":[""]}
{"level":"info","ts":1684278190.4393961,"logger":"docker-proxy","msg":"IngressNetworksMap","ingres":"map[bba610de82fbb46bafa6dc50e552941eb0db4b8f469e8dd38fb685adda7bbd29:true caddy:true]"}
{"level":"info","ts":1684278190.439599,"logger":"docker-proxy","msg":"Connecting to docker events","DockerSocket":""}
{"level":"info","ts":1684278190.464701,"logger":"docker-proxy","msg":"Swarm is available","new":false}
{"level":"info","ts":1684278190.4683917,"logger":"docker-proxy","msg":"New Caddyfile","caddyfile":"# Empty caddyfile"}
{"level":"warn","ts":1684278190.4690962,"logger":"docker-proxy","msg":"Caddyfile to json warning","warn":"[Caddyfile:1: Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies]"}
{"level":"info","ts":1684278190.4691372,"logger":"docker-proxy","msg":"New Config JSON","json":"{}"}
{"level":"info","ts":1684278190.469212,"logger":"docker-proxy","msg":"Sending configuration to","server":"localhost"}
{"level":"info","ts":1684278190.4705334,"logger":"admin.api","msg":"received request","method":"POST","host":"localhost:2019","uri":"/load","remote_ip":"127.0.0.1","remote_port":"38348","headers":{"Accept-Encoding":["gzip"],"Content-Length":["41"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}
{"level":"info","ts":1684278190.4706233,"msg":"config is unchanged"}
{"level":"info","ts":1684278190.4706576,"logger":"admin.api","msg":"load complete"}
{"level":"info","ts":1684278190.47086,"logger":"docker-proxy","msg":"Successfully configured","server":"localhost"}
```

Here is the entire docker-compose file:
```
version: '3'
services:
  caddy:
    build:
      context: ./caddy-build
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: 'unless-stopped'
  web:
    ports:
     - '3000'
    restart: 'always'
    stdin_open: true
    tty: true
    logging:
      options:
        max-file: '20'
        max-size: '100m'
    build:
      context: '../../../'
      dockerfile: '.wappler/targets/Staging/web/Dockerfile'
    networks:
      - caddy
      - internal
    dns:
      - 8.8.8.8
      - 8.8.4.4
    deploy:
      labels:
        caddy: caddytest.mealproapp.io
        caddy.reverse_proxy: "{{upstreams 3000}}"
      replicas: 4
    volumes:
      - 'tmp:/opt/node_app/tmp:rw'
      - 'tmp_logos_icons:/opt/node_app/tmp_logos_icons:rw'
      - 'tmp_post_media:/opt/node_app/tmp_post_media:rw'
      - 'tmp_recipe_media:/opt/node_app/tmp_recipe_media:rw'
  redis:
    image: 'redis:alpine'
    restart: 'always'
    hostname: 'redis'
    volumes:
      - 'redis-volume:/data'
    networks:
      - caddy
      - internal
volumes:
 redis-volume: ~
 tmp: ~
 tmp_logos_icons: ~
 tmp_post_media: ~
 tmp_recipe_media: ~
 caddy_data: {}
networks:
 caddy:
   external: true
 internal: ~
```

Have I misunderstood how to make this work?  

Thanks for any guidance!
