### ISSUE TITLE
return 404 on non existant domains

### ISSUE THREAD

**Issue by easy-easy** [lucaslorentz/caddy-docker-proxy#495]
Hello,

I'm coming form traefik and migrated to caddy. Everything works really well, except one thing.

I use a self signed cert/ca structure with wildcard subdomains (*.my.domain) and have a dns wildcard entry to route every traffic matching the wildcard to caddy. My setup specifies the domain names (service1.my.domain, service2.my.domain, ...).

How can I setup this plugin to return a 404 on non existing domain requests (not-existing.my.domain)?

Currently caddy just returns a empty page with a 200 status. 

Regards,
  easy.

**Comment by francislavoie** [comment]
Please show what your current config looks like. It's unclear what's going on without seeing specifics.

**Comment by easy-easy** [comment]
Hello,

my default caddyfile looks like this:

```
{
	log {
		output file /var/log/caddy/caddy.log {
			roll_size 1gb
			roll_local_time
			roll_keep 3
			roll_keep_for 14d
		}
		format console
		exclude http.log.access
	}
	servers {
		protocols h1 h2 h2c
	}
}

(accesslog) {
	log {
		output file /var/log/caddy/access.log {
			roll_size: 1gb
			roll_local_time
			roll_keep: 3
			roll_keep_for: 120d
		}
		format json
	}
}


(common) {
	import accesslog
	tls /etc/caddy/wild.crt /etc/caddy/wild.key
}

(common-le) {
	import accesslog
	tls letsencryptmail@example.com
}
```

And my labels for the container looks like this (docker-compose.yml):

```
    labels:
      caddy: service.my.domain
      caddy.reverse_proxy: "{{ upstreams 80 }}"
      caddy.import: common
```

Of course every container has its own subomain.. But as I said, if I now access eg https://nonono.my.domain/ I get an empty result with status 200.. 

```
[easy@workstation ~$] wget -S -o - -O - -v 'https://nonono.my.domain/'
--2023-05-31 07:44:46--  https://nonono.my.domain/
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving nonono.my.domain (nonono.my.domain)... 192.168.1.5
Connecting to nonono.dev.mb (nonono.my.domain)|192.168.1.5|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Server: Caddy
  Date: Wed, 31 May 2023 05:46:20 GMT
  Content-Length: 0
Length: 0
Saving to: ‘STDOUT’

     0K                                                        0.00 =0s

2023-05-31 07:44:46 (0.00 B/s) - written to stdout [0/0]

```

Traefik gives me a 404 for non existing domains.

Regards,
  easy

**Comment by francislavoie** [comment]
I don't understand. You're making an HTTPS request and the handshake completes, so Caddy must have a certificate for that domain. So it's not a "non-existing" domain. There's details missing from what you're saying.

**Comment by easy-easy** [comment]
Yes, but I request a domain, that I don't configured via the docker labels. So there should be return a 404 not found instead a 200.

**Comment by rsp2k** [comment]
have you tried putting "*.mydomain. com" in front of the first curly brace of the main config?

**Comment by eazylaykzy** [comment]
@howyay mind sharing the configuration and you compose file on how you handle the 404, thanks.

**Comment by diblaze** [comment]
How would one accomplish this with a wildcard domain?
I am some of my subdomains are open to the public, but caddy still responds to non-declared subdomains. Which is because of the wildcard I assume.

```
{
  crowdsec {
    api_url xxx
    api_key xxx
    ticker_interval 15s
  }
}

(deny-external) {
  @denied not remote_ip private_ranges
  handle @denied {
    respond 404
  }
}

*.domain.tld {
  @denied not remote_ip private_ranges
  tls {
    dns cloudflare {env.CLOUDFLARE_API}
  }
  
  log {
    output file /var/log/caddy/access.log
  }
}

:443 {
  respond 404
}

:80 {
  respond 404
}
```

**Comment by eazylaykzy** [comment]
I've got a somewhat different setup with `Docker Swarm`, therefore my configuration is quite different because a single base url is required to connect to different environments on our server (development, staging, sandbox, and production), there's a necessary header out application set for every request, the `x-my-site-trace-id` header, I got it to work locally by checking if this header does not exist with the below, 

```text
example.com {
	reverse_proxy :443 :80 {
		@headerNotExist header !x-my-site-trace-id
		handle_response @headerNotExist {
				respond `{"success":false,"message":"check for missing header(s)","meta":{},"errors":[]}` 400
		}
	}
	tls internal
}
```

Another way around this is to deploy a service (in this case - `containous/whoami`) that handles this like below;

```yaml
version: '3.9'

configs:
  caddy_file:
    file: ./Caddyfile
    labels:
      caddy:

services:
  caddy_server:
    image: lucaslorentz/caddy-docker-proxy:2.9.1
    ports:
      - "80:80"
      - "443:443"
    networks: [caddy_net, caddy_controller]
    environment:
      - TZ=Africa/Lagos
      - CADDY_DOCKER_MODE=server
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
    volumes:
      - caddy_data:/data
    deploy:
      update_config:
        parallelism: 2
        failure_action: rollback
        order: stop-first
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      resources:
        reservations:
          cpus: "0.1"
          memory: 128M
      labels:
        caddy.debug:
        caddy_controlled_server:
        caddy.log.output: stdout
    labels:
      logging: "promtail"
      logging_jobname: "caddy_server_logs"

  caddy_controller:
    image: lucaslorentz/caddy-docker-proxy:2.9.1
    networks: [caddy_net, caddy_controller]
    environment:
      - DOMAIN=$domain
      - TZ=Africa/Lagos
      - CADDY_DOCKER_MODE=controller
      - CADDY_DOCKER_POLLING_INTERVAL=5s
      - CADDY_CONTROLLER_NETWORK=10.200.200.0/24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      update_config:
        failure_action: rollback
        delay: 10s
      resources:
        reservations:
          cpus: "0.1"
          memory: 128M
      restart_policy:
        condition: any
      placement:
        constraints: [ node.role == manager ]
    labels:
      logging: "promtail"
      logging_jobname: "caddy_controller_logs"

  missing_header:
    image: containous/whoami
    networks: [caddy_net, caddy_controller]
    deploy:
      mode: global
      labels:
        caddy: $domain
        caddy.reverse_proxy: "{{upstreams}}"
        caddy.reverse_proxy.0_@headerNotExist: header !x-my-site-trace-id
        caddy.reverse_proxy.1_handle_response: "@headerNotExist"
        caddy.reverse_proxy.1_handle_response.respond: "`{\"success\":false,\"message\":\"check for missing header(s)\",\"meta\":{},\"errors\":[]}` 400"
        caddy.tls: "internal"

volumes:
  caddy_data: { }

networks:
  caddy_controller:
    external: true
  caddy_net:
    external: true
```
