### ISSUE TITLE
Setting TLS directive globally?

### ISSUE THREAD

**Issue by Zottelchen** [lucaslorentz/caddy-docker-proxy#500]
Hi, I've got a question. I want to set the TLS directive globally, is there a way to do this?
Basically I want this block to apply to everything:
```
tls {
	dns cloudflare <...>
	resolvers 1.1.1.1
}
```
The closest I've come is:
```
tls
{
	email mail@mail.mail
	tls {
		dns cloudflare <...>
		resolvers 1.1.1.1
	}
}
```
by having the labels:
```yaml
caddy.email: mail@mail.mail
caddy.tls.dns: "cloudflare <...>"
caddy.tls.resolvers: 1.1.1.1
```
