### ISSUE TITLE
help: Caddy inside docker, reverse_proxy outside docker ?

### ISSUE THREAD

**Issue by mykiwi** [lucaslorentz/caddy-docker-proxy#506]
Hi,

I have a question about caddy when it is running inside a Docker container.
Most of my apps are docker containers, but I want to run something else on my linux directly.
I can't do a `reverse_proxy` on `localhost:1234` (or `127.0.0.1:1234`) since the container will not be able to contact it :thinking: 

Any idea on how I should do it?

Here is my `compose.yml` if this can help:
```yml
networks:
  caddy:
    external: true

volumes:
  caddy_data:

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels:
      caddy.servers: 'metrics'
```

**Comment by francislavoie** [comment]
Google instructions for "connect to Docker host". Look for setting up "host.docker.internal".

**Comment by lucaslorentz** [comment]
You need to run docker container with host network. I think that way it will have access to 127.0.0.1:1234

**Comment by francislavoie** [comment]
It's _not_ necessary to use `--net=host`, you can connect to the host with `host.docker.internal`, but there are setup steps before that works. See the Docker docs.

**Comment by pthieu** [comment]
@mykiwi facing this as well, did you figure this out?

Wondering if I can do it in the docker-compose.yaml or if i have to use a Caddyfile?
I can't get it to work from outside the container but inside the container, I can curl `host.docker.internal:port` and get a response from my service on the host machine

**Comment by pthieu** [comment]
Nevermind, reading #363, I was able to get this working:
```
version: '3.7'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 4600:4600
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels:
      caddy_0: localhost:4600
      caddy_0.reverse_proxy: host.docker.internal:4600

networks:
  caddy:

volumes:
  caddy_data: {}
```

and then from the host machine: 
```
>curl localhost:4600/ping
{"success":true,"data":"pong"}%
```
