### ISSUE TITLE
no upstreams available, caddy reverse proxy to another docker container on the same network

### ISSUE THREAD

**Issue by pthieu** [lucaslorentz/caddy-docker-proxy#508]
I have a container listening on `PORT 80`, I have confirmed it is running. I have set up my routes on Cloudflare and confirm it hits Caddy.

Here is my Caddyfile:
```
version: '3.7'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels:
      caddy_0: link-reminder.labfortysix.com
      caddy_0.reverse_proxy: 172.17.0.1:4600
      caddy_1: api.wsbtrending.com
      caddy_1.reverse_proxy: 172.17.0.1:5000
  p-stack-fs:
    image: 956073034077.dkr.ecr.us-west-2.amazonaws.com/p-stack-fs
    container_name: p-stack-fs
    restart: unless-stopped
    environment:
      - PORT=80
      - NODE_ENV=production
      - SSM_BASE_PATH=/p-stack-fs/env/production
    networks:
      - caddy
    labels:
      caddy: pstackfs.phongt.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: "internal"

networks:
  caddy:

volumes:
  caddy_data: {}
  helper: 
    external: true
```

I see this error log in the caddy container:
```
{
  "level": "error",
  "ts": 1689486288.082017,
  "logger": "http.log.error",
  "msg": "no upstreams available",
  "request": {
    "remote_ip": "108.162.241.238",
    "remote_port": "57528",
    "proto": "HTTP/2.0",
    "method": "GET",
    "host": "pstackfs.phongt.com",
    "uri": "/",
    "headers": {
      "X-Forwarded-Proto": [
        "https"
      ],
      "Cf-Visitor": [
        "{\"scheme\":\"https\"}"
      ],
      "Upgrade-Insecure-Requests": [
        "1"
      ],
      "Accept": [
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
      ],
      "Sec-Fetch-Site": [
        "none"
      ],
      "Priority": [
        "u=0, i"
      ],
      "Accept-Encoding": [
        "gzip"
      ],
      "X-Forwarded-For": [
        "99.229.105.28"
      ],
      "Sec-Ch-Ua-Mobile": [
        "?0"
      ],
      "Cf-Ipcountry": [
        "CA"
      ],
      "Cf-Ray": [
        "7e77ef736d41543d-YYZ"
      ],
      "Accept-Language": [
        "en-US,en;q=0.9"
      ],
      "Cf-Connecting-Ip": [
        "99.229.105.28"
      ],
      "Sec-Ch-Ua": [
        "\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\""
      ],
      "Sec-Ch-Ua-Platform": [
        "\"macOS\""
      ],
      "User-Agent": [
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
      ],
      "Sec-Fetch-Mode": [
        "navigate"
      ],
      "Sec-Fetch-User": [
        "?1"
      ],
      "Sec-Fetch-Dest": [
        "document"
      ],
      "Cdn-Loop": [
        "cloudflare"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "server_name": "pstackfs.phongt.com"
    }
  },
  "duration": 0.000055031,
  "status": 503,
  "err_id": "2hkq6mw0a",
  "err_trace": "reverseproxy.(*Handler).proxyLoopIteration (reverseproxy.go:547)"
}
```

I've performed a full `docker-compose down && docker-compose up -d` and this still happens.
