### ISSUE TITLE
Pass client headers

### ISSUE THREAD

**Issue by shaqaruden** [lucaslorentz/caddy-docker-proxy#509]
I have run into an issue where the client headers are not being sent through to my web app. Specifically the REMOTE_HOST header. The value of this header is the IP address of the reverse proxy container and I needed it to be the ip of the client connecting to me.

Here is my definition for the container that is proxied

```yaml
services:
  app:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    labels:
      caddy: app.example.com
      caddy.tls: /certs/containment.pem /certs/cert-key.pem
      caddy.tls.ca_root: /certs/ca.pem
      caddy.reverse_proxy: "{{upstreams 80}}"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src:/var/www/html
      - ./caddy_data:/data
    depends_on:
      - containment-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - routable
```

Here is the section of the var_dump in my php application
> ["REMOTE_ADDR"]=>
>  string(10) "172.17.5.3"
>  ["HTTP_REFERER"]=>
>  string(39) "https://app.example.com"
> ["SERVER_PROTOCOL"]=>
>  string(8) "HTTP/1.1"
>  ["HTTP_X_FORWARDED_FOR"]=>
>  string(10) "172.17.5.3"
>  ["DOCUMENT_URI"]=>
>  string(18) "/MOBILE/mobile.php"
>  ["REMOTE_HOST"]=>
>  string(10) "172.17.5.3"

Here is the Caddyfile for the app service
```
:80 {
	root * /var/www/html
	php_fastcgi containment-php:9000
	file_server
}


:443 {
	root * /var/www/html
	php_fastcgi containment-php:9000
	file_server
        tls internal
}
```

Here is what the reverse proxy generates for the service

```
app.example.com {
        reverse_proxy 172.17.5.11:80
        tls /certs/containment.pem /certs/cert-key.pem {
            ca_root /certs/ca.pem
        }
    }
```

How do I forward the client headers of even specific client header to my application?

**Comment by francislavoie** [comment]
`REMOTE_HOST` is not an HTTP header, it's a CGI variable. It's value is _always_ the IP address of the directly connecting client, not the original client.

If you need the real IP of the original client, you need to configure `trusted_proxies` to have your PHP Caddy trust connections from your proxy Caddy, then the `X-Forwarded-For` header will contain the original client IP, and your application can use that header.

(HTTP headers are passed via CGI, prefixed with `HTTP_`, all uppercase and `-` converted to `_`, and in PHP those are accessible in the `$_SERVER` superglobal of course).

**Comment by shaqaruden** [comment]
I have attempted to add the trusted_proxies option globally and locally to the container but X-Forwarded-For still gives me the ip of the caddy proxy. 

```yml
app:
    image: caddy:2.6.4-alpine
    restart: unless-stopped
    labels:
      caddy: app.example.com
      caddy.tls: /certs/containment.pem /certs/cert-key.pem
      caddy.tls.ca_root: /certs/ca.pem
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.reverse_proxy.trusted_proxies: "172.17.63.3"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./src:/var/www/html
      - ./caddy_data:/data
    depends_on:
      - containment-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default
      - routable
```

```yml
caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 443:443
      - 80:80
      - 6001:6001
    environment:
      - CADDY_INGRESS_NETWORKS=routable
    networks:
      - routable
    labels:
      caddy.servers.trusted_proxies: "static 172.17.63.0/24"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./caddy_data:/data
      - ./certs:/certs
    restart: unless-stopped
```

```caddyfile
{
    servers {
        trusted_proxies static 172.17.63.0/24
    }
}
app.example.com {
    reverse_proxy 172.17.63.2:80 {
        trusted_proxies 172.17.63.3
    }
    tls /certs/containment.pem /certs/cert-key.pem {
        ca_root /certs/ca.pem
    }
}
```
