### ISSUE TITLE
Docker Swarm and service Tags

### ISSUE THREAD

**Issue by cblomart** [lucaslorentz/caddy-docker-proxy#52]
Looks like caddy-docker-proxy doesn't recognize services labels correctly.
If i deploy caddy-docker-proxy on each nodes then i end up having one loadbalancing for the container.
But it should be able to only run on one node (a manager).

PS:
isn't reading informations from services and container redondant?
this is not much as they should result in the same directives but maybe choosing a mode:
* docker to look only at containers
* swarm to only look at services
Or retain the container ids that were already parsed trought services

**Comment by cblomart** [comment]
Look like labels of services are parsed and not label of containers in the service descriptions.

So in in generator.go:154 the service.Spec.Labels refers to labels of the service
```golang
func addServiceToCaddyFile(buffer *bytes.Buffer, service *swarm.Service) {
    directives, err := parseDirectives(service.Spec.Labels, service, func() (string, error) {
```
Considering a compose file as follows (with swarmpit as an example):
```yaml
version: '3'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmpit
      - caddy
    labels:
      caddy_1.address: docker.lan:80
      caddy_1.targetport: "8080"
      caddy_1.tls: "off"
    deploy:
      placement:
        constraints:
          - node.role == manager

  db:
    image: klaemo/couchdb:2.0.0
    volumes:
      - /var/volumes/swarmpit:/opt/couchdb/data
    networks:
      - swarmpit

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmpit
    deploy:
      mode: global

networks:
  swarmpit:
    driver: overlay
  caddy:
    external: true
```

To find labels back, the container spec labels should be parsed so relace generator.go:155
```golang
func addServiceToCaddyFile(buffer *bytes.Buffer, service *swarm.Service) {
    directives, err := parseDirectives(service.Spec.TaskTemplate.ContainerSpec.Labels, service, func() (string, error) {
```
Maybe you could also skip parsing a container if it has a "com.docker.swarm.service.*" label.
That is considering that tags should be declared at the service level

**Comment by lucaslorentz** [comment]
Some users doesn't use docker services, therefore reading labels from containers and proxying to container IP is useful to some people. But we don't support proxying into multiple containers yet.

I don't think they're redundant, they're complementary.

The recommended approach is to proxy to docker service, not to containers. That means your labels should be inside services, not containers. Therefore you must put your labels the deploy section. According to docs: https://docs.docker.com/compose/compose-file/#labels-1

```
services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmpit
      - caddy
    deploy:
      labels:
        caddy_1.address: docker.lan:80
        caddy_1.targetport: "8080"
        caddy_1.tls: "off"
      placement:
        constraints:
          - node.role == manager
```

I don't have any problems with that setup, I run a caddy docker service with 1 or 2 instances at manager nodes, and those instances proxies to every service that I have on my swarm cluster.

Can you please try that?
