### ISSUE TITLE
multiple caddy environment

### ISSUE THREAD

**Issue by hijak** [lucaslorentz/caddy-docker-proxy#53]
Hi

I have a situation where we want to use a 2 tier caddy setup in a frontend / backend configuration

Is it possible to introduce some sort of namespaces so we can chuck config to different caddys in the network?

ie

```yaml
---

version: '3.2'
services:
  caddy-front:
   image: jcowey/caddy
   volumes:
     - $(pwd)/caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    networks:
      - webnet1

  caddy-backend1:
    image: jcowey/caddy
    networks:
      - webnet2
      - webnet1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  caddy-backend2:
    image: jcowey/caddy
    networks:
      - webnet2
      - webnet1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app1:
    image: some/image
    networks:
      - webnet2
    labels:
      caddy1.address: apptest1.lvh.me:80
      caddy1.targetport: 80

  app2:
    image: some/image
    networks:
      - webnet2
    labels:
      caddy2.address: apptest2.lvh.me:80
      caddy2.targetport: 80

networks:
  webnet1:
    external: true
  webnet2:
    external: true
```

This will probably envovle starting caddy with a flag to define what id it is
 
hope this makes sense 
 
Regards

**Comment by hijak** [comment]
Or perhaps to configure the loader via env var?

```yaml
caddy-backend1:
    image: jcowey/caddy
    environment:
      - CADDY_DOCKER=caddy1
    networks:
      - webnet2
      - webnet1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by hijak** [comment]
awesome thanks

**Comment by revnelson** [comment]
Can you provide an example of how this would work? I can't seem to get it working. I want a main caddy that handles whole-server services like portainer and matomo. Then, in a separate docker-compose, I want a caddy that handles project-specific services like php-fpm, wordpress, etc.

My thought process:

- I can't mount project-specific static files to the main caddy instance (I'd like to be able to easily add/remove/move projects without needing to change the main server configs)
- I want to keep my request chain all `caddy`. i.e. it seems like a shame to use an apache-served wordpress to go `caddy -> apache -> wordpress static files` instead I'd prefer to have the project-level caddy act as a file_server for the static files with a php_fastcgi directive pointing to the project-level php-fpm service.

This is what I've tried:

**Server-level docker-compose**
```
version: "3.8"

services:
  caddy:
    container_name: caddy
    image: ${CADDY_IMAGE?err}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/data
      - ./caddy/config:/config
    labels:
      caddy.email: ${EMAIL?err}
    networks:
      - caddy
    logging:
      driver: syslog
      options:
        tag: docker-caddy

  matomo_db:
    container_name: matomo_db
    image: mariadb:${MATOMO_MARIADB_VERSION?err}
    restart: unless-stopped
    command: --max-allowed-packet=128MB
    environment:
      - MYSQL_ROOT_PASSWORD=${MATOMO_DB_ROOT_PASSWORD?err}
      - MYSQL_DATABASE=${MATOMO_DB_DATABASE?err}
      - MYSQL_USER=${MATOMO_DB_USER?err}
      - MYSQL_PASSWORD=${MATOMO_DB_PASSWORD?err}
      - MARIADB_INITDB_SKIP_TZINFO=1
    volumes:
      - matomo_db:/var/lib/mysql
    networks:
      - internal
    logging:
      driver: syslog
      options:
        tag: docker-matomo_db

  matomo:
    container_name: matomo
    image: matomo:${MATOMO_VERSION?err}
    restart: unless-stopped
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=${MATOMO_DB_USER?err}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DB_PASSWORD?err}
      - MATOMO_DATABASE_DBNAME=${MATOMO_DB_DATABASE?err}
      - PHP_MEMORY_LIMIT=2048M
    volumes:
      - matomo:/var/www/html/
      - ./matomo/config:/var/www/html/config:rw
    labels:
      caddy: ${MATOMO_URL?err}
      caddy.reverse_proxy: "{{upstreams}}"
    networks:
      - caddy
      - internal
    depends_on:
      - matomo_db
    logging:
      driver: syslog
      options:
        tag: docker-matomo

volumes:
  caddy:
  matomo:
  matomo_db:

networks:
  caddy:
    name: caddy
  internal:
    name: server_internal
    external: false
```

That is working fine and I can access the matomo dashboard.

**Project-level docker-compose:**
```
version: "3.8"

services:
  caddy:
    container_name: ${PROJECT_NAME?err}_caddy
    image: ${CADDY_IMAGE?err}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy:/data
      - ./files:/var/www
    environment:
      - CADDY_DOCKER_LABEL_PREFIX=project-caddy
    labels:
      caddy: ${DOMAIN?err}
      caddy.reverse_proxy: "{{upstreams 80}}"
      project-caddy: localhost
      project-caddy.root: "* /var/www/public"
      project-caddy.file_server:
      project-caddy.encode: gzip
      project-caddy.php_fastcgi: "php-fpm:9000"
    networks:
      - caddy
      - internal
    logging:
      driver: syslog
      options:
        tag: docker-${PROJECT_NAME?err}-caddy

  php-fpm:
    container_name: ${PROJECT_NAME?err}_php
    image: php:${PHP_VERSION?err}-fpm
    restart: unless-stopped
    volumes:
      - ./files:/var/www
    networks:
      - internal
    logging:
      driver: syslog
      options:
        tag: docker-${PROJECT_NAME?err}-caddy


volumes:
  caddy:
    name: ${PROJECT_NAME?err}_caddy

networks:
  caddy:
    external: true
  internal:
    name: ${PROJECT_NAME?err}_internal
    external: false
```
