### ISSUE TITLE
admin config ignored

### ISSUE THREAD

**Issue by teodorescuserban** [lucaslorentz/caddy-docker-proxy#534]
When trying to debug #533 I ran into a different issue. It looks like the admin configuration (at least the `listen` part) is ignored when running caddy with the docker plugin.

Please find below the results using the official `lucaslorentz/caddy-docker-proxy:2.8-alpine` image.
I got the same behaviour with my own image at first and was sure there something wrong with my build.

Note that other global options defined in the Caddyfile are taken into account (like the logging).

I would appreciate your input, this makes impossible for me to debug the other issue (#533) as I can't access `/debug/pprof` from outside the container.

Thank you!

### docker-compose.ym file

```
networks:
  proxy:
    external: true
    name: proxy

services:
  caddy:
    container_name: caddy
    environment:
      CADDY_DOCKER_CADDYFILE_PATH: /caddy/Caddyfile
      CADDY_INGRESS_NETWORKS: proxy
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    networks:
      proxy: null
    ports:
    - 0.0.0.0:2019:2019/tcp
    - 0.0.0.0:80:80/tcp
    volumes:
    - /caddy/caddy:/caddy:rw
    - /var/run/docker.sock:/var/run/docker.sock:rw
```

### Caddyfile

`$ docker-compose exec caddy cat /caddy/Caddyfile`

```
{
	local_certs
	log {
		output file /logs/main.log
		level INFO
		format json {
			time_format iso8601
		}
	}
	admin :2019
}

:80 {
	header Content-Type "text/html; charset=utf-8"
	respond "<html><head><title>yay</title></head><body><p>Hello world</body></html>"
}
```

### running the container with the provided entrypoint & cmd

` docker-compose exec caddy netstat -lntp`

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      1/caddy
tcp        0      0 127.0.0.11:43123        0.0.0.0:*               LISTEN      -
tcp        0      0 :::80                   :::*                    LISTEN      1/caddy
```

### overriding the container command to run plain caddy

`command: ["run", "--config", "/caddy/Caddyfile"]`

`docker-compose exec caddy netstat -lntp`

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:45447        0.0.0.0:*               LISTEN      -
tcp        0      0 :::80                   :::*                    LISTEN      1/caddy
tcp        0      0 :::2019                 :::*                    LISTEN      1/caddy
```

### resulting config.json when ran with the default CMD

```
{
  "admin": {
    "listen": "tcp/localhost:2019"
  },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":80"
          ],
          "routes": [
            {
 ...
  },
  "logging": {
    "logs": {
      "default": {
        "encoder": {
          "format": "json",
          "time_format": "iso8601"
        },
        "level": "INFO",
        "writer": {
          "filename": "/logs/main.log",
          "output": "file"
        }
      }
    }
  }
}
```

### resulting config.json when overriding the default command ro only run plain caddy

```
{
  "admin": {
    "listen": ":2019"
  },
  "apps": {
    "http": {
      "servers": {
        "srv0": {
          "listen": [
            ":80"
          ],
          "routes": [
            {
...
  },
  "logging": {
    "logs": {
      "default": {
        "encoder": {
          "format": "json",
          "time_format": "iso8601"
        },
        "level": "INFO",
        "writer": {
          "filename": "/logs/main.log",
          "output": "file"
        }
      }
    }
  }
}
```
