### ISSUE TITLE
How to make requests to reverse proxy inside docker network?

### ISSUE THREAD

**Issue by f1amy** [lucaslorentz/caddy-docker-proxy#543]
I added caddy docker proxy to my docker-compose file and configured services with labels to be accessible via proxy.
It is working great when making requests from the host system (I use localhost as base domain).

The question is, how to make requests to my services from inside the docker network?
For a hypothetical service A with configured caddy-docker-proxy label `caddy: https://service-a.something.localhost`, if I'm inside hypothetical service B, how do I make a request like this: `curl -X GET https://service-a.something.localhost/something`?

**Comment by francislavoie** [comment]
You can add `http://caddy` as a site address (comma separated) to allow requests from another container.

If you add that, depending on the level of paranoia, you may want to reject requests with that hostname from non-private IP ranges.

**Comment by f1amy** [comment]
@francislavoie, I don't quite understand where should I add this site address, let me add an example:
```yaml
services:
  proxy:
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 80
    environment:
      - CADDY_INGRESS_NETWORKS=docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker-proxy

  service-a:
    image: nginx:alpine
    labels:
      caddy: http://*.service-a.localhost
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - docker-proxy

  service-b:
    image: nginx:alpine
    labels:
      caddy: http://service-b.localhost
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - docker-proxy

networks:
  docker-proxy:
```

If I'm on host, I can `curl -X GET http://anything.service-a.localhost`.
But if I'm inside service-b, I get unknown host error.

**Comment by francislavoie** [comment]
`caddy: http://*.service-a.localhost` becomes `caddy: "http://*.service-a.localhost, http://caddy" and then make your services request `http://caddy/something`

**Comment by f1amy** [comment]
@francislavoie Thanks for the reply, using http://caddy does seem to work for one service, however, this does not solve my problem entirely.

I want to be able to use dynamic hosts to call the service that I need.

The example:
```yaml
services:
  proxy:
    image: lucaslorentz/caddy-docker-proxy
    ports:
      - 80:80
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    networks:
      - caddy

  service-a:
    image: nginx:alpine
    ports:
      - 8081:80
    networks:
      - caddy
    labels:
      caddy: http://*.service-a.localhost, http://*.service-a.proxy
      caddy.reverse_proxy: "{{upstreams 80}}"

  service-b:
    image: nginx:alpine
    ports:
      - 8082:80
    networks:
      - caddy
    labels:
      caddy: http://service-b.localhost, http://service-b.proxy
      caddy.reverse_proxy: "{{upstreams 80}}"

volumes:
  caddy_data:

networks:
  caddy:
```

Doing `curl -I http://service-b.proxy` from service-a results in:
```
curl: (6) Could not resolve host: service-b.proxy
```

I don't know how to make it work.
