### ISSUE TITLE
Service is not in same network as caddy in docker swarm

### ISSUE THREAD

**Issue by humbsolutions** [lucaslorentz/caddy-docker-proxy#544]
In case anyone also face the same issues

Please make sure in the network setting, you need to change from
```
networks:
  caddy:
    external: true
```

to
```
networks:
  caddy:
    name: caddy
    external: true
```

Otherwise, the docker stack will always give you a new network name in `<project>_caddy`
