### ISSUE TITLE
Error using php_fastcgi directive: two Caddy blocks are created 

### ISSUE THREAD

**Issue by gremo** [lucaslorentz/caddy-docker-proxy#545]
Pretty minimal configuration to get PHP up and running:

```yaml
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8
    container_name: ${COMPOSE_PROJECT_NAME}-caddy
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - ./public:/var/www/html/public
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels:
      caddy.debug:

  php:
    image: php:8.2-fpm
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      - ./:/var/www/html
    depends_on:
      - caddy
    labels:
      caddy: localhost
      caddy.root: "* /var/www/html/public"
      caddy.php_fastcgi: "{{ upstreams 9000 }}"
      caddy.encode: zstd gzip
      caddy.file_server:

volumes:
  caddy_data:

```

With the above the generated Caddyfile **looks wrong** to me:

```txt
{
	debug
}
localhost {
	encode zstd gzip
	file_server
	php_fastcgi 192.168.16.3:9000
	root * /var/www/html/public
}
localhost:80 {
	encode zstd gzip
	file_server
	php_fastcgi
	root * /var/www/html/public
}
```

Is this a bug, my fault... or something not yet implemented?

**EDIT**: using a real host like `api.example.com`:

```txt
{
	debug
}
api.example.com {
	encode zstd gzip
	file_server
	php_fastcgi 192.168.16.3:9000
	root * /var/www/html/public
}
localhost:80 {
	encode zstd gzip
	file_server
	php_fastcgi
	root * /var/www/html/public
}
```

**Comment by gremo** [comment]
@francislavoie yes, I've deleted the container and the caddy volume too. Double checked the image version and it's 2.8.

**Comment by gremo** [comment]
I can confirm that, no matter what, the caddy file show "old settings" (i.e. th debug option). Deleted all containers, with this new `compose.yaml`:

```yaml
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8
    container_name: ${COMPOSE_PROJECT_NAME}-caddy
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

  whoami:
    image: containous/whoami
    container_name: ${COMPOSE_PROJECT_NAME}-whoami
    labels:
      caddy: ${DOMAIN:-localhost}
      caddy.reverse_proxy: "{{upstreams 8080}}"

volumes:
  caddy_data:
```
