### ISSUE TITLE
Caddy is not reading my labels

### ISSUE THREAD

**Issue by sowinski** [lucaslorentz/caddy-docker-proxy#547]
Hi,

this is my docker-compose for caddy:

```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8.9-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
```

And this is my docker-compose for my django project.

```
version: '3.8'
services:
  django:
    image: django-backend:latest
    ports:
      - "8000:8000"
    command: gunicorn myapp.wsgi --bind 0.0.0.0:8000
    env_file:
      - ../django.env
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
    volumes:
      - logvolume:/code/logs
    networks:
      - caddy
    labels:
      caddy: www.example.com
      caddy.reverse_proxy: "{{upstreams 8000}}"


volumes:
  logvolume:

networks:
  caddy:
    external: true
```

The first time i used the port 9999 and changed it later to 8000.

I restarted several times caddy and also my django project.
I can locally connect to the django project and it works on port 8000.
If I connect externally from www.example.com i can see in the caddy logs that caddy is still trying to forward it to port 9999.

I do not undestand why it is not updating. 

Do I have to implement a healthcheck or something else to make caddy update this to port 8000?
