### ISSUE TITLE
Is it possible to automate reverse proxy entries?

### ISSUE THREAD

**Issue by alber70g** [lucaslorentz/caddy-docker-proxy#551]
I'd like to have a default reverse proxy entry for any container on the `{containername}.local.co`, is this possible? This would make my life so much more easy when installing new containers for local use only. 
Then I could make the public ones available by manually adding labels on the domains that I'd like to use.

**Comment by francislavoie** [comment]
I don't understand. Can't you just add labels to do that?

**Comment by francislavoie** [comment]
That's not supported (and I'm not sure it would be possible anyway).

The problem is the port number that a container is exposing it not known. So automatically proxying is not possible without some configuration.

**Comment by Mikle-Bond** [comment]
Depends on how much "automatic" you want it to be. And what sacrifices you're willing to make.

With docker-compose you can use YAML anchors . Add this on top of your configuration (before `services`):

```yaml
networks:
    ingress:
        
x-constants:
    - &default_restart unless-stopped

x-snippets:
    env: &with_env
        environment: &env
            PUID: 
            PGID:
            TZ:
    
    net: &with_net
        networks: &net
            ingress:

x-labels:
- &caddy_auto_name
    caddy: &auto_name '{{ index .Labels "com.docker.compose.service" }}.${BASE_DOMAIN}'

- &simple_expose
    caddy: *auto_name
    caddy.reverse_proxy: 'http://{{ index .Labels "com.docker.compose.service" }}:{{ (index .Ports 0).PrivatePort }}'

- &tls_strip
    caddy.reverse_proxy.transport: http
    caddy.reverse_proxy.transport.tls_insecure_skip_verify:

x-templates:
    default: &default
        environment: *env
        logging: *log
        networks: *net
        restart: *default_restart

    dummy: &dummy
        restart: *default_restart
        environment: *env
        init: true
        network_mode: none
        read_only: true
        image: alpine
        command: sleep infinity

```

This is part of my config, which I stripped down to your use-case. 

After that you can use it like this:

```yaml
services:
    qr:
        <<: *default
        build: ./build/qr
        environment:
            PORT: 8080
        labels: *simple_expose
    prometheus:
        <<: *default
        image: prom/prometheus:latest
        command:
            - --config.file=/etc/prometheus/config.yml
            - --web.external-url=https://prom.${BASE_DOMAIN}
            - --log.format=json
        volumes:
            - /config/prometheus:/etc/prometheus/
            - data_prometheus:/prometheus
        expose:
            - "9090/tcp"
        labels: *simple_expose

    graph:
        <<: *default
        image: grafana/grafana
        environment:
            <<: *env
            GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: jasonlashua-prtg-datasource,natel-discrete-panel,fatcloud-windrose-panel
            GF_SERVER_ROOT_URL: https://graf.${BASE_DOMAIN}
            GF_LOG_CONSOLE_FORMAT: json

        volumes:
            - data_grafana:/var/lib/grafana
            - conf_grafana:/etc/grafana/provisioning
        expose:
            - "3000/tcp"
        labels: *simple_expose

    # ....
```
It will use the service name, `$BASE_DOMAIN` from `.env` file, and first exposed/forwarded port of your container as parameters for `reverse_proxy` statement.

## yet another approach

You can use a snippet. Define it in global configuration file: 

```yaml
# enable global config in caddy service
environment:
    CADDY_DOCKER_CADDYFILE_PATH: /config/Caddyfile.globals
    CADDY_DOCKER_PROCESS_CADDYFILE: "true"
    BASE_DOMAIN: # null means "pick from the .env file"
```

```caddy
(rproxy) {
        {args[0]}.{env.BASE_DOMAIN} {
                reverse_proxy {args[1:]}
        }
}
```

```yaml
services:
    foo:
        <<: *default
        # ....
        labels:
            caddy: import rproxy foo "{{upstreams 8080}}"
````

I used this in the past. 
Pros: 
 - you have the most explicit configuration while being shorter than multiple statement
 - you can have exposed name to be different from service name
Cons: 
 - you still have to repeat a boilerplate
 - you only shorten configs by one label

This approach is better if you have to throw more labels at your containers (for example if you use `pawelmalak/flame`, `benphelps/homepage`  or something similar.

## yet another another approach

You can combine snippets and cryptic go-templates.

Disclaimer: I haven't tried this one. I use what I described in the first part, because I like autogenerated config to be more verbose

```caddy
(rproxy) {
        {args[0]}.{env.BASE_DOMAIN} {
                reverse_proxy {args[1:]}
        }
}
```

```yaml
x-labels:
- &simple_expose
    caddy: import rproxy {{ index .Labels "com.docker.compose.service" }} {{ (index .Ports 0).PrivatePort | upstreams }}
```

It should work like this, or maybe with some quotes thrown here or there.
