### ISSUE TITLE
Trying to use the LinuxServer Nextcloud Docker returns public IPs.

### ISSUE THREAD

**Issue by Hacker1245** [lucaslorentz/caddy-docker-proxy#564]
I am having this problem where all of my login attempts to Nextcloud end up outputting the public IP address.
My proxy docker-compose:
```
version: "3.7"
services:
  caddy:
    # see here for guidance on which image / tag to choose:
    # https://github.com/lucaslorentz/caddy-docker-proxy#docker-images
    image: lucaslorentz/caddy-docker-proxy:2.8.10
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      caddy:
        ipv4_address: 172.16.0.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true
```
Nextcloud docker-compose:
```
  nextcloud:
     image: lscr.io/linuxserver/nextcloud:latest
     container_name: nextcloud
     networks:
      caddy:
        ipv4_address: 172.16.0.7
     environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Warsaw
     volumes:
      - ./nextcloud:/config
      - /srv/dev-disk-by-uuid-bef15755-0d31-4edf-8d6c-c2d4786b312a/data:/data
     labels:
      caddy: example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.header.Strict-Transport-Security: '"max-age=15552000;"'
      caddy.rewrite_0: /.well-known/carddav /remote.php/dav
      caddy.rewrite_1: /.well-known/caldav /remote.php/dav
     links:
      - db

networks:
  caddy:
    external: true
```
This is all running on a OpenMediaVault 6.9.11-3 server with the openmediavault-compose plugin. I use DuckDNS for the domain.
