### ISSUE TITLE
How to activation logging? (error.log / access.log)

### ISSUE THREAD

**Issue by sowinski** [lucaslorentz/caddy-docker-proxy#588]
Hi,

this is my current caddy docker-compose file.

```
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8.10-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
```
In your readme file, i can not find anything about logging.

How can I have a access.log and error.log with logrotation and so on?

**Comment by francislavoie** [comment]
Use the [`log` directive](https://caddyserver.com/docs/caddyfile/directives/log). Read the Caddy docs, CDP is just a mapping of labels to Caddyfile.

**Comment by sowinski** [comment]
So I need to use labels in my application docker compose file and not in the "main" docker compose of caddy?

**Comment by francislavoie** [comment]
It depends. For global options, you'd put it on your Caddy service. For site directives, you put them on your app service.

**Comment by sowinski** [comment]
Okay, so if I want a global error.log and acces.log for all services I would do this also with labels in my main caddy docker compose file?

**Comment by francislavoie** [comment]
You always need at least `log` (with no options) in each site to enable access logs to be written to stdout, then you can configure global options to configure a logger that handles the logs as you want.

**Comment by sowinski** [comment]
I think I undestand know what you mean.

Would be nice if you could confirm that this is the correct way to activate the "access.log" in my service.

```
    labels:
      caddy: "www.example.com"
      caddy.log:
      caddy.reverse_proxy: "{{upstreams 8000}}"
```

I just set **caddy.log:** without any "parameter"
