### ISSUE TITLE
How to make requests to proxy service inside another proxy service?

### ISSUE THREAD

**Issue by annas-atchia-bocasay** [lucaslorentz/caddy-docker-proxy#590]
I have two API Platform projects (project 1 and 2) running through a Caddy docker proxy server. Requests to both projects inside the proxy server container works perfectly. 

However when I'm making requests to let's say for e.g. my project 1 container inside the 2nd project container, I'm getting a `200 OK` response but the body is always empty.

**My question is how do I make request to another service from inside the container of another service ?**

Below is a request and response for the above.

```
$ curl -v poc-api-platform-1-php-1
* Host poc-api-platform-1-php-1:80 was resolved.
* IPv6: (none)
* IPv4: 172.26.0.3
*   Trying 172.26.0.3:80...
* Connected to poc-api-platform-1-php-1 (172.26.0.3) port 80
> GET / HTTP/1.1
> Host: poc-api-platform-1-php-1
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Caddy
< Date: Thu, 07 Mar 2024 10:43:43 GMT
< Content-Length: 0
< 
* Connection #0 to host poc-api-platform-1-php-1 left intact
```

For testing purposes, I added a `whoami` service and I was able to make a successful request towards the `whoami` container inside the 2nd project container.

```
$ curl -v whoami1-whoami1-1
* Host whoami1-whoami1-1:80 was resolved.
* IPv6: (none)
* IPv4: 172.26.0.4
*   Trying 172.26.0.4:80...
* Connected to whoami1-whoami1-1 (172.26.0.4) port 80
> GET / HTTP/1.1
> Host: whoami1-whoami1-1
> User-Agent: curl/8.5.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Thu, 07 Mar 2024 10:48:17 GMT
< Content-Length: 161
< Content-Type: text/plain; charset=utf-8
< 
Hostname: a3afb7eed803
IP: 127.0.0.1
IP: 172.26.0.4
RemoteAddr: 172.26.0.5:38460
GET / HTTP/1.1
Host: whoami1-whoami1-1
User-Agent: curl/8.5.0
Accept: */*

* Connection #0 to host whoami1-whoami1-1 left intact
```

Below are my docker configurations:

1. Caddy docker proxy server

```
version: "3.7"

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy_proxy_test
    networks:
      - caddy_proxy_test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy_proxy_test:
    external: true
  default:

volumes:
  caddy_data: {}
```

2. Project 1

```
# Development environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_dev
    depends_on:
      - database
    volumes:
      - ./api:/app
      - /app/var
      - ./api/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      SERVER_NAME: http://${SERVER_NAME:-localhost}, php:80
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    labels:
      caddy: poc-api-platform-1.localhost
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.reverse_proxy.header_up: Custom-Forwarded-Proto {scheme}
    networks:
      - default
      - caddy_proxy_test

  pwa:
    build:
      context: ./pwa
      target: dev
    volumes:
      - ./pwa:/srv/app
    environment:
      API_PLATFORM_CREATE_CLIENT_ENTRYPOINT: http://php
      API_PLATFORM_CREATE_CLIENT_OUTPUT: .
      # On Linux, you may want to comment the following line for improved performance
      WATCHPACK_POLLING: "true"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: ${MYSQL_PORT:-5432}
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

networks:
  caddy_proxy_test:
    external: true
```

3. Project 2

```
# Development environment override
services:
  php:
    build:
      context: ./api
      target: frankenphp_dev
    depends_on:
      - database
    volumes:
      - ./api:/app
      - /app/var
      - ./api/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      SERVER_NAME: http://${SERVER_NAME:-localhost}, php:80
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    labels:
      caddy: poc-api-platform-2.localhost
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.reverse_proxy.header_up: Custom-Forwarded-Proto {scheme}
    networks:
      - default
      - caddy_proxy_test

  pwa:
    build:
      context: ./pwa
      target: dev
    volumes:
      - ./pwa:/srv/app
    environment:
      API_PLATFORM_CREATE_CLIENT_ENTRYPOINT: http://php
      API_PLATFORM_CREATE_CLIENT_OUTPUT: .
      # On Linux, you may want to comment the following line for improved performance
      WATCHPACK_POLLING: "true"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - target: 5432
        published: ${MYSQL_PORT:-5432}
        protocol: tcp
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

networks:
  caddy_proxy_test:
    external: true
```

4. Whoami

```
version: '3.7'
services:
  whoami1:
    image: traefik/whoami
    networks:
      - caddy_proxy_test
    labels:
      caddy: whoami1.localhost
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy_proxy_test:
    external: true
```

This is the generated in-memory Caddyfile inside the proxy server container:

```
poc-api-platform-1.localhost {
        reverse_proxy 172.26.0.3:80 {
                header_up Custom-Forwarded-Proto {scheme}
        }
}
poc-api-platform-2.localhost {
        reverse_proxy 172.26.0.5:80 {
                header_up Custom-Forwarded-Proto {scheme}
        }
}
whoami1.localhost {
        reverse_proxy 172.26.0.4:80
}
```
