### ISSUE TITLE
Best practice: maintenance mode

### ISSUE THREAD

**Issue by sowinski** [lucaslorentz/caddy-docker-proxy#594]
Hi,

what would be the best practive in caddy-docker-proxy for easily enabling and disabling a maintenance mode with a custom html file?

Thank you

**Comment by lucaslorentz** [comment]
Closing as stale, but here's an approach for maintenance mode: you can use Caddy's `respond` directive via labels to return a maintenance page:

```yaml
labels:
  caddy: "example.com"
  caddy.respond: "\"Site under maintenance\" 503"
```

Or serve a static HTML file:
```yaml
labels:
  caddy: "example.com"
  caddy.root: "* /srv"
  caddy.file_server:
  caddy.rewrite: "* /maintenance.html"
```

To toggle maintenance mode, swap the labels and let caddy-docker-proxy regenerate the config. Feel free to reopen if you have questions.

*— from claude*
