### ISSUE TITLE
IPv6 Logging not working

### ISSUE THREAD

**Issue by sowinski** [lucaslorentz/caddy-docker-proxy#620]
Hi,

this is my caddy docker compose file:

```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8.10-alpine
    ports:
      - 80:80
      - 443:443
      - 2019:2020
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped

networks:
  caddy:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    external: true

volumes:
  caddy_data: {}
```
The network supports only ipv4.  (DNS is externally configured for ipv4 and ipv6).

If I open my website with:
`curl https://mywebsite.com`
I see in the caddy log my ipv4 address.

If i open my website with ipv6:
`curl -6 https://mywebsite.com`
I see in the caddy log an internal docker ip.

I guess docker is translating my ipv6 address to an ipv4 address. Which is nice but I loose the ipv6 address in my logging.

What would be the correct way to make the ipv6 adress visible in the logs?
Also I want to forward this ipv6 later to my django/guncorn container.

Can I forward somehow the address or do I have to change all my docker networks and enable ipv6?

I would prefer to keep my docker networks and forward somehow the ipv6 address. Is this possible?

**Comment by sowinski** [comment]
https://github.com/mholt/caddy-ratelimit/issues/54

Hi, it would be interesting how you handle this case. Do you activate ipv6 for the container or do you extract the ipv6 from the NAT solution which ships with docker?

**Comment by sowinski** [comment]
So from what I found in the internet, most auf the users try to activate ipv6 instead of extracting the ipv6 addresses from the header coming from the NAT.

Because of this I also try to run caddy with activated ipv6. (With no success).

What have I done?
### 1. I enabled ipv6 support like here described on my ubuntu machine
[](https://docs.docker.com/config/daemon/ipv6/#use-ipv6-for-the-default-bridge-network)

created `/etc/docker/daemon.json`
with:
```
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64",
  "experimental": true,
  "ip6tables": true
}
```
and restarted docker:
`sudo systemctl restart docker`

### 2. Edited my docker compose file and recreated my caddy network with ipv6 support
`docker-compose.yml
````
...
networks:
  caddy:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
    external: true
    enable_ipv6: true
    ipam:
       config:
         - subnet: 2001:0DB8::/112
...
```
```
We need to remove the old caddy network and create a new one with:
`docker create --ipv6 --subnet 2001:0DB8::/112 caddy`


## Problems
If I run `docker network inspect caddy` then I can see that ipv6 is enabled.
`docker network inspect caddy`

```
[
    {
        "Name": "caddy",
        "Id": "a4175ba6b358258c3b2e95694b83c9f7c1db2f16fbf58306c7c85e46cc8cb063",
        "Created": "2024-06-06T10:45:00.723124194+02:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": true,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.24.0.0/16",
                    "Gateway": "172.24.0.1"
                },
                {
                    "Subnet": "2001:0DB8::/112",
                    "Gateway": "2001:db8::1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "1baf849ff58c74cccf8fbbf4a696cbd2fa0a417c5b4b8fcf787b0d5b33ee18c5": {
                "Name": "whoami-whoami-1",
                "EndpointID": "1a5f403d864e26922f383ce64e6d64716766d265efc5007baf70d7d145ae5ea0",
                "MacAddress": "02:42:ac:18:00:03",
                "IPv4Address": "172.24.0.3/16",
                "IPv6Address": "2001:db8::3/112"
            },
            "566ca3ed4950b476fd9fec341fc7eb5fa97e6926abed965cacc04f187e66f642": {
                "Name": "caddy-caddy-1",
                "EndpointID": "dd0bcf84f05d3592e3b158cda10dda8f88d039b8faa2a65fd092fc584da11d01",
                "MacAddress": "02:42:ac:18:00:02",
                "IPv4Address": "172.24.0.2/16",
                "IPv6Address": "2001:db8::2/112"
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```

But if I run netstat in the caddy container, it is not listening to ipv6 connections. What is wrong?

```
docker compose exec caddy /bin/sh
netstat -tulpen
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:41825        0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      1/caddy
tcp        0      0 :::80                   :::*                    LISTEN      1/caddy
tcp        0      0 :::443                  :::*                    LISTEN      1/caddy
tcp        0      0 :::2020                 :::*                    LISTEN      1/caddy
udp        0      0 127.0.0.11:34069        0.0.0.0:*                           -
udp        0      0 :::443                  :::*                                1/caddy
```

What I am missing? :)
