### ISSUE TITLE
Global options seems not working in caddy-docker-proxy itself

### ISSUE THREAD

**Issue by fky2015** [lucaslorentz/caddy-docker-proxy#632]
As the docs said:
> [Global options](https://caddyserver.com/docs/caddyfile/options) can be defined by not setting any value for caddy. They can be set in any container/service, **including caddy-docker-proxy itself.** [Here is an example](https://github.com/lucaslorentz/caddy-docker-proxy/blob/master/examples/standalone.yaml#L19)

A minimum reproducible example is here:

```
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    # build: ./
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    labels:
      caddy.email: you@example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - ./config:/config/caddy
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
```

Then run:

```
docker compose up -d
cat config/Caddyfile.autosave
```

Got:

```
# Empty caddyfile
```
