### ISSUE TITLE
Ignore services in other networks

### ISSUE THREAD

**Issue by pikeas** [lucaslorentz/caddy-docker-proxy#660]
I have two Caddy instances:

```
services:
    public-ingress:
        ...
        networks: [public]
    intranet-ingress:
        ...
        networks: [intranet]
```

And a bunch of services:

```
    service-a:
        ...
        networks: [intranet]
        deploy:
            labels:
                caddy: service-a.internal-corp.company.com
                caddy.reverse_proxy: "{{upstreams 1111}}"
    service-b:
        ...
        networks: [public]
        deploy:
            labels:
                caddy: api.company.com
                caddy.reverse_proxy: "{{upstreams 2222}}"
```

The issue is that the intranet Caddy sees the public labels, and vice versa:

```
{"level":"warn","logger":"docker-proxy","msg":"Service is not in same network as caddy","service":"service-b","serviceId":"1234"}
```

Everything is configured as intended, service-b attaches to only the public network and can't see the intranet Caddy. Because Caddy has the Docker socket, it sees the labels for every Swarm service and thinks service-b is misconfigured.

Possible changes:

- Reduce log level for this message from warn to debug.
- Only process services that share at least one network with the Caddy instance.
