### ISSUE TITLE
DNS Challenge with duckdns.org

### ISSUE THREAD

**Issue by fwarren** [lucaslorentz/caddy-docker-proxy#662]
Will need a custom build with the duckdns plugin
```
ARG CADDY_VERSION=2.8.4
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/caddy-dns/duckdns

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
Using a standard duckdns domain
```
    labels:
      caddy: domain.duckdns.org
      caddy.reverse_proxy: "{{upstreams http }}"
      caddy.tls.dns: duckdns xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
Using  a subdomain based on a duckdns domain
```
    labels:
      caddy: test.domain.duckdns.org
      caddy.reverse_proxy: "{{upstreams http }}"
      caddy.tls.dns: duckdns xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      caddy.tls.dns.override_domain: domain.duckdns.org
```

**Comment by timosturm** [comment]
Is this a working example, are the labels supposed to be in the compose file for caddy-docker or e.g., whoami? Using the template does not produce an output in `Caddyfile.autosave`.

**Comment by fwarren** [comment]
Here is as close as I can get to a real world example. Things that will need to be changed:

- replace-with-your-email@example.com
- duckdns xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
- domain.duckdns.org
- www.domain.duckdns.org
 
Things you may want to change: 
- network caddy
- /srv/caddy
- /srv/www

Let's do some setup:
```
mkdir /srv/caddy
mkdir /srv/www
docker network create caddy
```

No need to edit: `/srv/caddy/Buildfile`
```
ARG CADDY_VERSION=2.8.4
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/caddy-dns/duckdns

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

Need to edit labels in: `/srv/caddy/compose.yml`
```
---
services:
  caddy:
    build: .
    container_name: caddy
    ports:
      - 80:80     # open firewall port
      - 443:443   # open firewall port
      - 2019:2019 # control interface/api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./config:/config
    restart: unless-stopped
    labels:
      caddy.email: replace-with-your-email@example.com
      caddy.acme_ca: https://acme-staging-v02.api.letsencrypt.org/directory
```

Need to edit labels in: `/srv/www/compose.yml`
```
---
services:
  website:
    image: lscr.io/linuxserver/nginx:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./www:/config/www
    restart: unless-stopped
    labels:
      caddy: www.domain.duckdns.org
      caddy.reverse_proxy: "{{upstreams http }}"
      caddy.tls.dns: duckdns xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      caddy.tls.dns.override_domain: domain.duckdns.org

networks:
  default:
    external: true
    name: caddy
```


Starting Everything
```
# start webserver files in /srv/webserver/www
cd /srv/website
docker compose up -d

# only need --build flag the first time running caddy
cd /srv/caddy
docker compose up -d --build

# to dump the caddy config
docker compose exec caddy curl http://127.0.0.1:2019/config/
```
