### ISSUE TITLE
Plugin is always adding proxy directive

### ISSUE THREAD

**Issue by jtyr** [lucaslorentz/caddy-docker-proxy#67]
After the recent changes, the plugin is always adding the `proxy` directive regardless if the directive has any `proxy` related data defined. Before we could use:

```yaml
    labels:
      caddy_1.address: http://example.lan:8080
      caddy_1.redir: https://example.lan:8443{uri}

      caddy_2.address: https://example.lan:8443
      caddy_2.tls: self_signed
      caddy_2.targetport: 80
      caddy_2.proxy.keepalive: 0
```
which generated:
```
http://example.lan:8080 {
  redir https://example.lan:8443{uri}
}
https://example.lan:8443 {
  tls self_signed
  proxy / myservice:80 {
    keepalive 0
  }
}
```
but now it generates:
```
http://example.lan:8080 {
  ### SEE THE LINE BELLOW ###
  proxy / myservice:80
  redir https://example.lan:8443{uri}
}
https://example.lan:8443 {
  tls self_signed
  proxy / myservice:80  {
    keepalive 0
  }
}
```

**Comment by lucaslorentz** [comment]
Hey Jtyr.

The idea of the caddy.address directive was to be a shortcut to autogenerated proxies. But because caddy.targetport label was required, the proxy wasn't generated on your setup.

I didn't realize caddy.adress could be used alone.

What I would suggest is to use just caddy label when you don't want it to generate a proxy.

Like:
caddy_1=example.com
caddy_1.redir=...

Tomorrow I will think how I can avoid this breaking change on next release. Currently the breaking change is on ci tags only.

Thanks for reporting this


Em 12 de set de 2018 7:12 PM, Jiri Tyr <notifications@github.com> escreveu:

After the recent changes, the plugin is always adding the proxy directive regardless if the directive has any proxy related data defined. Before we could use:

    labels:
      caddy_1.address: http://example.lan:8080
      caddy_1.redir: https://disney.example.lan:8443{uri}

      caddy_2.address: https://example.lan:8443
      caddy_2.tls: self_signed
      caddy_2.targetport: 80
      caddy_2.proxy.keepalive: 0

which generated:

http://disney.example.lan:8080 {
  redir https://disney.example.lan:8443{uri}
}
https://disney.example.lan:8443 {
  import myTlsDefaults
  proxy / myservice:80 {
    keepalive 0
  }
}


but now it generates:

http://disney.example.lan:8080 {
  proxy / myservice:80
  redir https://disney.example.lan:8443{uri}
}
https://disney.example.lan:8443 {
  import myTlsDefaults
  proxy / myservice:80  {
    keepalive 0
  }
}

**Comment by jtyr** [comment]
Thanks for the hint @lucaslorentz. Unfortunately it doesn't work as expected. This is my Compose file:

```yaml
version: '3.2'

services:
  frontend:
    image: mycaddy
    labels:
      caddy_1: (myDefaults)
      caddy_1.log: / stdout

      caddy_2: (myTlsDefaults)
      caddy_2.import: myDefaults
      caddy_2.tls: self_signed
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend:
    image: mycaddy
    labels:
      caddy_1: http://example.lan
      caddy_1.import: myDefaults
      caddy_1.redir: https://example.lan{uri}

      caddy_2.address: https://example.lan
      caddy_2.import: myTlsDefaults
      caddy_2.targetport: 2015
      caddy_2.proxy.keepalive: 0
```

and this is the log from the `test_frontend` service:

```
test_frontend.1.7w9l2vi0vioz@swarm01    | 2018/09/13 09:43:02 [ERROR] CaddyFile error: :2 - Error during parsing: File to import not found: myDefaults
test_frontend.1.7w9l2vi0vioz@swarm01    | 2018/09/13 09:43:02 [INFO] Wrong CaddyFile:
test_frontend.1.7w9l2vi0vioz@swarm01    | (myTlsDefaults) {
test_frontend.1.7w9l2vi0vioz@swarm01    |   import myDefaults
test_frontend.1.7w9l2vi0vioz@swarm01    |   redir https://example.lan{uri}
test_frontend.1.7w9l2vi0vioz@swarm01    |   tls self_signed
test_frontend.1.7w9l2vi0vioz@swarm01    | }
test_frontend.1.7w9l2vi0vioz@swarm01    | https://example.lan {
test_frontend.1.7w9l2vi0vioz@swarm01    |   import myTlsDefaults
test_frontend.1.7w9l2vi0vioz@swarm01    |   proxy / 10.0.0.4:2015 {
test_frontend.1.7w9l2vi0vioz@swarm01    |     keepalive 0
test_frontend.1.7w9l2vi0vioz@swarm01    |   }
test_frontend.1.7w9l2vi0vioz@swarm01    | }
```

It seems to ignore the `_#` suffix and only takes the last directive.
