### ISSUE TITLE
Issues related to PR #63

### ISSUE THREAD

**Issue by mrdrup** [lucaslorentz/caddy-docker-proxy#68]
After recent changes we observe following problems with configuring [`caddy`](https://github.com/mholt/caddy) server using [`caddy-docker-proxy`](https://github.com/lucaslorentz/caddy-docker-proxy) plugin:
1. The `proxy` directive is always added to the resulted config.
2. Only first `caddy.address` directive argument is honoured, while remaining are ignored.
3. `caddy.proxy` directive value is prepended to resulting proxying directive, which brakes proxying.

### 1. The `proxy` directive is always added to the resulted config
@jtyr already [opened an issue related](#67 ) to the this problem

### 2. Only first `caddy.address` directive argument is honoured while remaining are ignored

Given compose file:
```yaml
labels:
  caddy.address:    http://domain.com https://domain.com
  caddy.targetport: 80
```

Expected generated config file:
```
http://domain.com https://domain.com {
  proxy / app1:80
}
```

Actual generated config file:
```
http://domain.com {
  proxy / app1:80
}
```

Issue can be reproduced with `lucaslorentz/caddy-docker-proxy:test` image.

### 3. `caddy.proxy` directive value is prepended to resulting proxying directive, which brakes proxying
Given compose file:
```yaml
labels:
  caddy.address: http://domain.com
  caddy.proxy:   / tasks.app:80
```

Expected generated config file:
```
http://domain.com {
  proxy / tasks.app:80 
}
```

Actual generated config file:
```
http://domain.com {
  proxy / tasks.app:80 / app1
}

```

Issue can be reproduced with `lucaslorentz/caddy-docker-proxy:test` image.

---

All listed issues have workarounds and are not critical, but all together they contribute to a much bigger problem - huge and repeatable configurations, which may result in mistakes adding/removing directives or simply in missing configuration directives, like `https` redirects.
Here is what I mean. Before changes our `docker-compose` file looked similar to this:

```yaml
services:
  proxy:
    command: ['-log', 'stdout']
    deploy:
      labels:
        caddy.address: (default)
        caddy.errors:
        caddy.header:   / -Server
        caddy.log:      / stdout "\{\"hostname\":\"{host}\",\"remote\":\"{remote}\",\"user\":\"{user}\",\"when_iso\":\"{when_iso}\",\"method\":\"{method}\",\"host\":\"{host}\",\"uri\":\"{uri}\",\"proto\":\"{proto}\",\"status\":{status},\"size\":{size},\"query\":\"{query}\",\"mitm\":\"{mitm}\",\"latency_ms\":{latency_ms},\"tls_cipher\":\"{tls_cipher}\",\"tls_version\":\"{tls_version}\",\"scheme\":\"{scheme}\",\"referer\":\"{>Referer}\",\"user_agent\":\"{>User-Agent}\",\"fragment\":\"{fragment}\"\}"
        caddy.redir.if: "{scheme} is http"
        caddy.redir./:  https://{host}{uri}
        caddy.redir:    301
        caddy.tls:      cert.pem key.pem
    image: lucaslorentz/caddy-docker-proxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app1:
    deploy:
      labels:
        caddy.address:           http://app1.domain.com https://app1.domain.com
        caddy.import:            default
        caddy.proxy.transparent:
        caddy.targetport:        80
    image: brndnmtthws/nginx-echo-headers

  app2:
    deploy:
      labels:
        caddy.address:           http://app2.domain.com https://app2.domain.com
        caddy.import:            default
        caddy.proxy.transparent:
        caddy.targetport:        80
    image: brndnmtthws/nginx-echo-headers

  app3:
  ...
```

Which resulted in following config:

```
(default) {
  errors
  header / -Server
  log / stdout "\{\"hostname\":\"{host}\",\"remote\":\"{remote}\",\"user\":\"{user}\",\"when_iso\":\"{when_iso}\",\"method\":\"{method}\",\"host\":\"{host}\",\"uri\":\"{uri}\",\"proto\":\"{proto}\",\"status\":{status},\"size\":{size},\"query\":\"{query}\",\"mitm\":\"{mitm}\",\"latency_ms\":{latency_ms},\"tls_cipher\":\"{tls_cipher}\",\"tls_version\":\"{tls_version}\",\"scheme\":\"{scheme}\",\"referer\":\"{>Referer}\",\"user_agent\":\"{>User-Agent}\",\"fragment\":\"{fragment}\"\}"
  redir 301 {
    / https://{host}{uri}
    if {scheme} is http
  }
  tls cert.pem key.pem
}
http://app1.domain.com https://app1.domain.com {
  import default
  proxy / caddy_app1:80 {
    transparent
  }
}
http://app2.domain.com https://app2.domain.com {
  import default
  proxy / caddy_app2:80 {
    transparent
  }
}
...
```

But now, we had to rewrite it to following:
```yaml
services:
  proxy:
    command: ['-log', 'stdout']
    image: lucaslorentz/caddy-docker-proxy:test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  app1:
    deploy:
      labels:
        caddy_1.address:           http://app1.domain.com
        caddy_1.redir:             https://{host}{uri}
        caddy_1.header:            / -Server
        caddy_1.log:               / stdout "\{\"hostname\":\"{host}\",\"remote\":\"{remote}\",\"user\":\"{user}\",\"when_iso\":\"{when_iso}\",\"method\":\"{method}\",\"host\":\"{host}\",\"uri\":\"{uri}\",\"proto\":\"{proto}\",\"status\":{status},\"size\":{size},\"query\":\"{query}\",\"mitm\":\"{mitm}\",\"latency_ms\":{latency_ms},\"tls_cipher\":\"{tls_cipher}\",\"tls_version\":\"{tls_version}\",\"scheme\":\"{scheme}\",\"referer\":\"{>Referer}\",\"user_agent\":\"{>User-Agent}\",\"fragment\":\"{fragment}\"\}"
        caddy_2.address:           https://app1.domain.com
        caddy_2.errors:
        caddy_2.header:            / -Server
        caddy_2.log:               / stdout "\{\"hostname\":\"{host}\",\"remote\":\"{remote}\",\"user\":\"{user}\",\"when_iso\":\"{when_iso}\",\"method\":\"{method}\",\"host\":\"{host}\",\"uri\":\"{uri}\",\"proto\":\"{proto}\",\"status\":{status},\"size\":{size},\"query\":\"{query}\",\"mitm\":\"{mitm}\",\"latency_ms\":{latency_ms},\"tls_cipher\":\"{tls_cipher}\",\"tls_version\":\"{tls_version}\",\"scheme\":\"{scheme}\",\"referer\":\"{>Referer}\",\"user_agent\":\"{>User-Agent}\",\"fragment\":\"{fragment}\"\}"
        caddy_2.proxy.transparent:
        caddy_2.targetport:        80
        caddy_2.tls:               cert.pem key.pem
    image: brndnmtthws/nginx-echo-headers

  app2:
    deploy:
      labels:
        caddy_1.address:           http://app2.domain.com
        caddy_1.redir:             https://{host}{uri}
        caddy_1.header:            / -Server
        caddy_1.log:               / stdout "\{\"hostname\":\"{host}\",\"remote\":\"{remote}\",\"user\":\"{user}\",\"when_iso\":\"{when_iso}\",\"method\":\"{method}\",\"host\":\"{host}\",\"uri\":\"{uri}\",\"proto\":\"{proto}\",\"status\":{status},\"size\":{size},\"query\":\"{query}\",\"mitm\":\"{mitm}\",\"latency_ms\":{latency_ms},\"tls_cipher\":\"{tls_cipher}\",\"tls_version\":\"{tls_version}\",\"scheme\":\"{scheme}\",\"referer\":\"{>Referer}\",\"user_agent\":\"{>User-Agent}\",\"fragment\":\"{fragment}\"\}"
        caddy_2.address:           https://app2.domain.com
        caddy_2.errors:
        caddy_2.header:            / -Server
        caddy_2.log:               / stdout "\{\"hostname\":\"{host}\",\"remote\":\"{remote}\",\"user\":\"{user}\",\"when_iso\":\"{when_iso}\",\"method\":\"{method}\",\"host\":\"{host}\",\"uri\":\"{uri}\",\"proto\":\"{proto}\",\"status\":{status},\"size\":{size},\"query\":\"{query}\",\"mitm\":\"{mitm}\",\"latency_ms\":{latency_ms},\"tls_cipher\":\"{tls_cipher}\",\"tls_version\":\"{tls_version}\",\"scheme\":\"{scheme}\",\"referer\":\"{>Referer}\",\"user_agent\":\"{>User-Agent}\",\"fragment\":\"{fragment}\"\}"
        caddy_2.proxy.transparent:
        caddy_2.targetport:        80
        caddy_2.tls:               cert.pem key.pem
    image: brndnmtthws/nginx-echo-headers

  app3:
  ...
```
