### ISSUE TITLE
[ERROR]  Removing invalid block: Caddyfile:70: unrecognized directive: speed.home.advik.one\nDid you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.\nspeed.home.advik.one {\n\treverse_proxy 172.27.0.11:80\n}

### ISSUE THREAD

**Issue by ADV1K** [lucaslorentz/caddy-docker-proxy#682]
```
[ERROR]  Removing invalid block: Caddyfile:47: unrecognized directive: whoami.local
Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.
whoami.local {
        reverse_proxy 172.27.0.11:8080
}
```

compose.yaml
```yaml
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - internal
    labels:
      caddy: whoami.local
      caddy.reverse_proxy: "{{upstreams 8080}}"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy-data:/data
    networks:
      - internal

volumes:
  caddy-data:
    external: true

networks:
  internal:
    external: true
```
