### ISSUE TITLE
Running with containerd/nerdctl environment

### ISSUE THREAD

**Issue by xas** [lucaslorentz/caddy-docker-proxy#683]
Hello,

I am trying to install seafile v12 on a server.
The current host configuration is an `Alpine` v3.21 with only `containerd` v2.0.0 and `nerdctl` v2.0.2

I run the script with the current YAML configuration for caddy:
```yaml
    image: lucaslorentz/caddy-docker-proxy:2.9.1
    environment:
      - CADDY_INGRESS_NETWORKS=seafile-net
      - CADDY_DOCKER_NO_SCOPE=true
      - DOCKER_TLS_CERTDIR=""
      - DOCKER_TLS_VERIFY=off
      - DOCKER_HOST=unix://var/run/docker.sock
    volumes:
      - /var/run/containerd/containerd.sock:/var/run/docker.sock
```

When I start the compose files, I got in the caddy logs:

```
caddy     |{"level":"info","ts":1736004620.4540226,"logger":"docker-proxy","msg":"Running caddy proxy server"}
caddy     |{"level":"info","ts":1736004620.4879189,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
caddy     |{"level":"info","ts":1736004620.4908206,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
caddy     |{"level":"info","ts":1736004620.4908638,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
caddy     |{"level":"error","ts":1736004620.5001018,"logger":"docker-proxy","msg":"Docker ping failed","error":"Head \"http://var%2Frun%2Fdocker.sock/_ping\": net/http: HTTP/1.x transport connection broken: malformed HTTP response \"\\x00\\x00\\x06\\x04\\x00\\x00\\x00\\x00\\x00\\x00\\x05\\x00\\x00@\\x00\".\n* Are you trying to connect to a TLS-enabled daemon without TLS?"}
caddy     |Error: Head "http://var%2Frun%2Fdocker.sock/_ping": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x06\x04\x00\x00\x00\x00\x00\x00\x05\x00\x00@\x00".
caddy     |* Are you trying to connect to a TLS-enabled daemon without TLS?
```

I tried a lot of settings (with/without `DOCKER_HOST`, TLS yes/no, ...) but always get the same error.

The `containerd` service is running, the sock is present. `nerdctl` commands work.

I don't know if I should ask here or to the `containerd` repo ?

Does someone have some ideas about it ?
