### ISSUE TITLE
How to add on_demand_tls to the config

### ISSUE THREAD

**Issue by arjendevos** [lucaslorentz/caddy-docker-proxy#684]
I can't figure it out. Current setup:

```yaml
name: caddy-reverse-proxy

services:
    caddy:
        restart: unless-stopped
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        networks:
            - caddy
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./caddy-data:/data
            - ./caddy-config:/config

        labels:
            caddy_global: |
                {
                    on_demand_tls {
                        ask http://api/v1/tls-domain-check
                    }
                }

networks:
    caddy:
        external: true
```

but i am missing things?

**Comment by arjendevos** [comment]
For anyone wondering:
```Caddyfile
 labels:
            caddy.on_demand_tls:
            caddy.on_demand_tls.ask: http://api:8080/v1/tls-domain-check

            caddy_0: https://
            caddy_0.tls_0.on_demand:
            caddy_0.reverse_proxy: '{{upstreams 4321}}'
```

**Comment by Jace254** [comment]
Hey can you please share the full config

**Comment by arjendevos** [comment]
@Jace254 here:

```
name: caddy-reverse-proxy

services:
    caddy:
        restart: unless-stopped
        image: lucaslorentz/caddy-docker-proxy:ci-alpine
        ports:
            - 80:80
            - 443:443
        networks:
            - caddy
        environment:
            - CADDY_INGRESS_NETWORKS=caddy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./caddy-data:/data
            - ./caddy-config:/config

         labels:
            caddy.on_demand_tls:
            caddy.on_demand_tls.ask: http://api:8080/v1/tls-domain-check

            caddy_0: https://
            caddy_0.tls_0.on_demand:
            caddy_0.reverse_proxy: '{{upstreams 4321}}'

networks:
    caddy:
        external: true
```
