### ISSUE TITLE
[Help] Generate a wildcard for `auto_https prefer_wildcard`

### ISSUE THREAD

**Issue by accforgithubtest** [lucaslorentz/caddy-docker-proxy#685]
Hello all,
I am looking for help to generate `auto_https prefer_wildcard`, to try the new feature [auto_https prefer_wildcard](https://github.com/caddyserver/caddy/pull/6146) thats released in caddy 2.9.1.

I tried below, but docker compose doesnt like the `*`, and throws an error.
Can anyone please help me generate this via cdp labels.

What is expected caddy config -
```
*.example.com {
	tls {
		dns <provider>
	}
	respond "fallback"
}
```

What I tried but failed with errors - 
```
      caddy: *.example.com
      caddy.tls: "/certs/cert.prm /certs/cert-key.pem"
      caddy.respond: "fallback"
```

**Comment by polarathene** [comment]
There isn't a new release of CDP with Caddy 2.9 yet, you'll need to do a custom build:

```yaml
networks:
  default:
    name: cdp-net

services:
  reverse-proxy:
    container_name: cdp
    image: localhost/caddy-docker-proxy:2.9.1
    # Build a custom image until CDP has an official release with Caddy 2.9 available:
    pull_policy: build
    build:
      # NOTE: `$$` escapes `$` to opt-out of the Docker Compose ENV interpolation feature.
      dockerfile_inline: |
        ARG CADDY_VERSION=2.9.1
        FROM caddy:$${CADDY_VERSION}-builder AS builder
        RUN xcaddy build v$${CADDY_VERSION} \
          --with github.com/lucaslorentz/caddy-docker-proxy/v2

        FROM caddy:$${CADDY_VERSION}-alpine
        COPY --link --from=builder /usr/bin/caddy /usr/bin/caddy
        CMD ["caddy", "docker-proxy"]
    # Configure global options + a dummy wildcard site-block (provisions/renews the wildcard):
    labels:
      # This global setting is for demo purposes, it'll provision certs akin to `tls internal`:
      caddy.local_certs:
      # Prefer using a wildcard certificate when already available instead of provisioning a new cert:
      caddy.auto_https: prefer_wildcard
      # Provision a wildcard cert:
      caddy_1: "*.example.internal"
      caddy_1.respond: "fallback"
    # Socket needed for CDP functionality to read other container labels:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Publish ports to access from the Docker host network interfaces:
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
    # TESTING: Only used for the `.internal` TLD example:
    # Containers in the same network can use internal DNS to send their query to
    # to this CDP container for the given aliases:
    networks:
      default:
        aliases:
          - whoami.example.internal

  example:
    image: traefik/whoami
    labels:
      caddy: whoami.example.internal
      caddy.reverse_proxy: "{{upstreams 80}}"
```

You can then try testing it out, for example:

```console
$ docker compose up -d
# Check site can be reached:
docker run --rm --network cdp-net fedora curl --insecure https://whoami.example.internal

# Check site responded with wildcard certificate:
docker run --rm --network cdp-net alpine ash -c 'apk add step-cli jq && step certificate inspect --insecure https://whoami.example.internal | jq -c .extensions.subject_alt_name.dns_names'

# Check fallback to wildcard site block if no other matching site block for subdomain:
docker run --rm --network cdp-net fedora curl https://anything-else.example.internal
```

I'm not able to run that locally atm, but that should work 🤔 

I have got a fully functional and verified example without CDP documented here: https://github.com/caddyserver/caddy/pull/6146#issuecomment-2581966621

---

Similar to older wildcard CDP config: https://github.com/lucaslorentz/caddy-docker-proxy/issues/581#issuecomment-1925578681

You might need to quote wrap like `caddy: "*.example.com"` too.

If you still have issues, make sure you test with a fresh container instance when you make config changes, use `docker compose up --force-recreate` (_or `docker compose down && docker compose up`_).
