### ISSUE TITLE
Redirecting http and https requests to different ports

### ISSUE THREAD

**Issue by amdavidson** [lucaslorentz/caddy-docker-proxy#689]
I am trying to put snikket behind an existing caddy-docker-proxy install. Snikket supports [being proxied](https://snikket.org/service/help/advanced/reverse_proxy/#caddy) but I'm having a hard time translating it to the label format.

I do not see a configuration example or previous issue indicating how one would redirect http and https requests to the underlying containers separately. If i just use `{{upstreams}}` I get an endless 301 redirect loop.

Is this a supported use case?

```yaml
services:
  snikket_proxy:
    container_name: snikket-proxy
    image: snikket/snikket-web-proxy:stable
    env_file: snikket.conf
    volumes:
      - ./data:/snikket
      - acme_challenges:/var/www/html/.well-known/acme-challenge
    restart: "unless-stopped"
    networks:
      - caddy
    labels:
      caddy: chat.amd.im, groups.chat.amd.im, share.chat.amd.im
      caddy.0_reverse_proxy: "{{upstreams http 80}}"
      caddy.1_reverse_proxy: "{{upstreams https 443}}"
```
