### ISSUE TITLE
"Found character that cannot start any token"

### ISSUE THREAD

**Issue by GitKalle** [lucaslorentz/caddy-docker-proxy#690]
I try to use the [example](https://github.com/lucaslorentz/caddy-docker-proxy#examples) from the readme.md:

```yml
caddy: example.com
caddy.@ws.0_header: Connection *Upgrade*
caddy.@ws.1_header: Upgrade websocket
caddy.0_reverse_proxy: @ws {{upstreams}}
caddy.1_reverse_proxy: /api* {{upstreams}}
```

But I get the error:

`found character that cannot start any token`

I guess the problem is because of the @ character. Does anybody have a solution?

**Comment by UnoYakshi** [comment]
I just wrapped it like so: `"@ws {{upstreams}}"`.

**Comment by UnoYakshi** [comment]
But I think examples in the documentation should work out of box. Otherwise, it's confusing whether you are understanding the concept correctly or not.

**Comment by lucaslorentz** [comment]
The `@` character has special meaning in YAML. You need to quote the label keys that contain it:

```yaml
labels:
  "caddy.@ws.0_header": "Connection *Upgrade*"
  "caddy.@ws.1_header": "Upgrade websocket"
  caddy.0_reverse_proxy: "@ws {{upstreams}}"
  caddy.1_reverse_proxy: "/api* {{upstreams}}"
```
