### ISSUE TITLE
Automatically display the new generated Caddyfile and JSON config on any container up and down

### ISSUE THREAD

**Issue by Kenya-West** [lucaslorentz/caddy-docker-proxy#691]
Right now, with this setup:

```yaml
---

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: caddy
    cpus: 0.5
    mem_limit: 200m
    ports:
      - 80:80
      - 443:443
      - "443:443/udp"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/config/Caddyfile
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/Caddyfile:/config/Caddyfile
      - ./logs:/var/log/caddy
      - caddy-data:/data
      - caddy-certs:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
    restart: unless-stopped

volumes:
  caddy-data: {}
  caddy-certs: {}
```

`caddy-docker-proxy` does not display the newly updated Caddyfile and JSON config when some container "joins" its network and adds own settings via labels. The same for containers that are "left".

How can I enforce `caddy-docker-proxy` record complete config and JSON at any update?
