### ISSUE TITLE
Issue with converting a global block to labels

### ISSUE THREAD

**Issue by Rupie17** [lucaslorentz/caddy-docker-proxy#695]
I have been going through the documentation and have had success converting all my blocks to labels except one.
Trying the various combinations in the docs still doesn't get the output I'm looking for to match my static Caddyfile so either I am missing something or it's not working for this use case.

Before I moved to labels I had this global block in my Caddyfile:
{
  dynamic_dns {
    provider cloudflare {env.CLOUDFLARE_API_TOKEN}
    domains {
      {env.DOMAIN}
    }
    check_interval 5m
    versions ipv4
  }
}

This works fine.
Going through the docs and converting to labels I tried this:
caddy_2.dynamic_dns.1_provider: "cloudflare {env.CLOUDFLARE_API_TOKEN}"
caddy_2.dynamic_dns.2_domains: "{env.DOMAIN}"
caddy_2.dynamic_dns.check_interval: 5m
caddy_2.dynamic_dns.versions: ipv4

The output I get is:
{
  dynamic_dns {
    provider cloudflare {env.CLOUDFLARE_API_TOKEN}
    domains {env.DOMAIN}
    check_interval 5m
    versions ipv4
  }
}

I cannot get the domains label to be it's own block like the Caddyfile.  I have tried every example in the docs but can't seem to get it formatted the way I had it in the static Caddyfile.
Looking for any ideas.  Thanks!

**Comment by polarathene** [comment]
Perhaps use a base `Caddyfile`, bit simpler for static config:

```yaml
# Connect all services to proxy via this network:
networks:
  default:
    name: caddy-net

services:
  reverse-proxy:
    image: lucaslorentz/caddy-docker-proxy:2.9
    # Providing your own base `Caddyfile` requires this ENV:
    environment:
      CADDY_DOCKER_CADDYFILE_PATH: /etc/caddy/Caddyfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
    configs:
      - source: caddy-config
        target: /etc/caddy/Caddyfile

configs:
  caddy-config:
    content: |
      # Global Settings
      {
        dynamic_dns {
          provider cloudflare {env.CLOUDFLARE_API_TOKEN}
          domains {
            {env.DOMAIN}
          }
          check_interval 5m
          versions ipv4
        }
      }
```

**Comment by lucaslorentz** [comment]
This is the same issue as #767 / #699 — dots in label keys are treated as nesting separators, so domain names get split incorrectly.

PR #784 adds support for escaping dots with `\.`, which will allow:

```yaml
labels:
  caddy.dynamic_dns.provider: "cloudflare {env.CLOUDFLARE_API_TOKEN}"
  caddy.dynamic_dns.domains.example\.com: ""
  caddy.dynamic_dns.check_interval: "5m"
  caddy.dynamic_dns.versions: "ipv4"
```
