### ISSUE TITLE
Trying to switch to podman-compose - caddy and podman socket

### ISSUE THREAD

**Issue by zilexa** [lucaslorentz/caddy-docker-proxy#697]
This is probably not an issue or bug, but more me who can't find documentation as how to do this.
Switching to Fedora Silverblue I am now using podman-compose:

```
  caddy-proxy:
    container_name: net-caddy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: always
    networks: 
      - net-caddy
    environment:
      - CADDY_INGRESS_NETWORKS=net-caddy
      - CADDY_DOCKER_NO_SCOPE=true
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - $DOCKERDIR/network/caddy-proxy/caddy_data:/data:Z
      - $DOCKERDIR/network/caddy-proxy/config:/config:Z
    ports:
      - 443:443
      - 80:80
    labels:
      caddy.email: $EMAIL
#      caddy_0: http://adguard.o
#      caddy_0.reverse_proxy: host.docker.internal:3000
#      caddy_1: http://vpn.o
#      caddy_1.reverse_proxy: host.docker.internal:5000
#      caddy_2: https://unifi.o
#      caddy_2.reverse_proxy: host.docker.internal:8080   
```

Unfortunately it has trouble connecting to the socket. I did check with `podman info` which clearly shows

```
{"level":"info","ts":1738271453.6760228,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
{"level":"error","ts":1738271453.676158,"logger":"docker-proxy","msg":"Docker ping failed","error":"permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head \"http://%2Fvar%2Frun%2Fdocker.sock/_ping\": dial unix /var/run/docker.sock: connect: permission denied"}
Error: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
```

```
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
```
Same result after `systemctl enable --now podman.socket`. The socket is running:
```
systemctl status podman.socket
● podman.socket - Podman API Socket
     Loaded: loaded (/usr/lib/systemd/system/podman.socket; enabled; preset: disabled)
     Active: active (listening) since Thu 2025-01-30 22:09:43 CET; 23min ago
 Invocation: 2a2ff8c48fea4973bd79421fd4136c09
   Triggers: ● podman.service
       Docs: man:podman-system-service(1)
     Listen: /run/podman/podman.sock (Stream)
     CGroup: /system.slice/podman.socket

Jan 30 22:09:43 obelix.o systemd[1]: Listening on podman.socket - Podman API Socket.
```

Also, the user does have access to the socket, if I use the right path:
```
❯ ls -al /run/podman/podman.sock
ls: cannot access '/run/podman/podman.sock': Permission denied

❯ ls -al /run/user/1000/podman/podman.sock
total 0
drwxr-xr-x. 2 asterix asterix 40 Jan 30 21:58 .
drwxr-xr-x. 3 asterix asterix 60 Jan 30 21:58 .
```

So I expect it to work... Caddy is my only container that needs the socket access hence I did not bump into this before.

**Comment by zilexa** [comment]
I started over again, `podman system migrate` and `podman system reset` also stopped the --user podman.socket service, disabled it, then enabled and started it. Did podman-compose up (after creating the network. 

`systemctl --user status podman.socket`
```
● podman.socket - Podman API Socket
     Loaded: loaded (/usr/lib/systemd/user/podman.socket; enabled; preset: disabled)
     Active: active (listening) since Sat 2025-02-01 14:09:04 CET; 13min ago
 Invocation: 49ed1168dec44588ac20f24d5cb8b0e5
   Triggers: ● podman.service
       Docs: man:podman-system-service(1)
     Listen: /run/user/1000/podman/podman.sock (Stream)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/podman.socket

Feb 01 14:09:04 obelix.o systemd[1449]: Listening on podman.socket - Podman API Socket.
```

`podman logs -f --tail 20 caddy-proxy`
```
{"level":"info","ts":1738416080.1704485,"logger":"docker-proxy","msg":"Running caddy proxy server"}
{"level":"info","ts":1738416080.1711955,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1738416080.171304,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1738416080.1713104,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
{"level":"error","ts":1738416080.1714833,"logger":"docker-proxy","msg":"Docker ping failed","error":"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"}
Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

with `compose.yml`
```
#
version: "2.4"
services:
##_______network SERVICES________
##
##_____________________ Caddy [network/web-proxy]
  caddy-proxy:
    container_name: caddy-proxy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: always
    networks: 
      - caddy-net
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-net
      - CADDY_DOCKER_NO_SCOPE=true
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
      - $DOCKERDIR/network/caddy-proxy/caddy_data:/data:Z
      - $DOCKERDIR/network/caddy-proxy/config:/config:Z
    ports:
      - 443:443
      - 80:80
    labels:
      caddy.email: $EMAIL
```

Makes no sense, this should work right?

**Comment by zilexa** [comment]
I figured it out. 
This is how I solved it (`    privileged: true` did the trick)

```
##_____________________ Caddy [network/web-proxy]
  caddy-proxy:
    container_name: caddy-proxy
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    privileged: true
    restart: always
    networks: 
      - caddy-net
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-net
      - CADDY_DOCKER_NO_SCOPE=true
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      - $DOCKERDIR/network/caddy-proxy/caddy_data:/data:Z
      - $DOCKERDIR/network/caddy-proxy/config:/config:Z
    ports:
      - 443:443
      - 80:80
    labels:
      caddy.email: $EMAIL
```
