### ISSUE TITLE
[Need Help]  Internal Domain only

### ISSUE THREAD

**Issue by bauerbyter** [lucaslorentz/caddy-docker-proxy#704]
I am trying this for hours and to be honest, I am pretty much a noob about this stuff :-)
I want to use caddy as a reverse proxy for only internal uses. So no open ports.
I have a cloudflare domain. I always get the Error:
```
{"level":"error","ts":1739880073.9724216,"msg":"challenge failed","identifier":"who.<mydomain>.casa","challenge_type":"http-01","problem":{"type":"urn:ietf:params:acme:error:dns","title":"","detail":"no valid A records found for who.<mydomain>.casa; no valid AAAA records found for who.<mydomain>.casa","instance":"","subproblems":null},"stacktrace":"github.com/mholt/acmez/v3.(*Client).pollAuthorization\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:557\ngithub.com/mholt/acmez/v3.(*Client).solveChallenges\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:378\ngithub.com/mholt/acmez/v3.(*Client).ObtainCertificate\n\tgithub.com/mholt/acmez/v3@v3.0.0/client.go:136\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:477\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/certmagic@v0.21.6/acmeissuer.go:371\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue\n\tgithub.com/caddyserver/caddy/v2@v2.9.1/modules/caddytls/acmeissuer.go:249\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:626\ngithub.com/caddyserver/certmagic.doWithRetry\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:104\ngithub.com/caddyserver/certmagic.(*Config).obtainCert\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:700\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:505\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1\n\tgithub.com/caddyserver/certmagic@v0.21.6/config.go:415\ngithub.com/caddyserver/certmagic.(*jobManager).worker\n\tgithub.com/caddyserver/certmagic@v0.21.6/async.go:73"}
```
I think this is because lets encrypt cannot resolve the local ip? Cann someone PLEASE push me in the right direction what I am missing?

What I Did:
- Adguard DNS rewrite: <mydomain>.casa and *.<mydomain>.casa to <LOCALIP>
- Cloudflare: A -  <mydomain>.casa - <LOCALIP>
- Cloudflare: CNAME - * - <mydomain>.casa

docker-compose.yml
```
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker/volumes/caddy/data:/data
    restart: unless-stopped
networks:
  caddy:
    external: true
```

```
services:
  whoami0:
    container_name: whoiam
    networks:
      - caddy
    image: jwilder/whoami:latest
    restart: unless-stopped
    labels:
      caddy: who.<mydomain>.casa
      caddy.reverse_proxy: "{{upstreams 8000}}" 
networks:
  caddy:
    external: true
```
