### ISSUE TITLE
Cannot get proxy_protocol to work

### ISSUE THREAD

**Issue by Qlii256** [lucaslorentz/caddy-docker-proxy#708]
I have a haproxy running in front of caddy and I'd like to enable proxy_protocol v1. However, I cannot seem to get it working, below is my config.

```
    labels:
      caddy.servers.trusted_proxies: "static 192.168.10.101"
      caddy_0: ${SEAFILE_SERVER_PROTOCOL:-http}://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      caddy_0.reverse_proxy: "{{upstreams 80}}"
      caddy_0.reverse_proxy.transport: "http proxy_protocol v1"
```

I have a webserver running on port 80 which is normal http. Caddy does https and does all the certification etc. However, I want my haproxy to correctly work with Caddy. I have proxy_protocol 1 enabled via `send-proxy`. The (local) ip address of the haproxy is `192.168.10.101` as I've have "trusted" that ip address as a global config. However, it looks like the proxy_protocol config is not being set. The `{{upstreams 80}}` is a template from Seafile docker which results in an ip address along the lines of `192.168.1.87` which is where the local webserver (nginx) is running.

I'm not sure if this configuration is correct to set up proxy_protocol.

**Comment by Qlii256** [comment]
Thank you for the reply.

Yes the haproxy is in front of the Caddy. So I need to put it up at the "global" settings just like I did the trusted proxies?

**Comment by Qlii256** [comment]
I managed to get it finally working using the code below:

```
    labels:
      caddy.servers.listener_wrappers.proxy_protocol.allow: "192.168.10.101/24"
      caddy.servers.listener_wrappers.tls:
      caddy_0: ${SEAFILE_SERVER_PROTOCOL:-http}://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      caddy_0.reverse_proxy: "{{upstreams 80}}"
```

Changing the haproxy backend from `send-proxy` to `send-proxy-v2` also works, I believe Caddy automatically detects the version.
