### ISSUE TITLE
Disable certificate generation for a specific domain

### ISSUE THREAD

**Issue by sowinski** [lucaslorentz/caddy-docker-proxy#709]
Hi,

I have the following labels in my docker compose:

```
labels:
  caddy: "caddy.example.com, www.example.com, www.example.se, www.example.pl, www.example.it"
  caddy.log:
  caddy.reverse_proxy: "{{upstreams 8000}}"
```

I have infront of www.example.it a CDN placed. The CDN is creating the certificate for me. Caddy can not create a certifcate for www.exmaple.it anymore, because the DNS entries are missing. 

So I want to disable the certificate generation for www.example.it but keep the certificate generation for the other domains.

How can I do this?

**Comment by francislavoie** [comment]
You would need separate site blocks to change the config for that domain.

**Comment by sowinski** [comment]
```
labels:
  caddy: "caddy.example.com, www.example.com, www.example.se, www.example.pl"
  caddy.log:
  caddy.reverse_proxy: "{{upstreams 8000}}"
  caddy_1: "www.example.it"
  caddy_1.reverse_proxy: "{{upstreams 8000}}"
  caddy_1.tls: "internal"
```

Do you mean like that? Is this the way how to stop creating a SSL certificate for www.example.it but still listening for incoming connections from www.example.it?

**Comment by polarathene** [comment]
> Is this the way how to stop creating a SSL certificate for `www.example.it` but still listening for incoming connections from `www.example.it`?

`tls internal` provisions a locally signed certificate from Caddy instead of a third-party like LetsEncrypt.

If you only want to access via HTTP you would use `http://www.example.it`, that will only listen on `:80` for that site-address, not `:443` / HTTPS.

**Comment by lucaslorentz** [comment]
Closing — use separate site blocks with `caddy_N` prefixes. As @polarathene explained, use `http://` prefix to serve only on port 80 without TLS:
```yaml
caddy: "www.example.com, www.example.se, www.example.pl"
caddy.reverse_proxy: "{{upstreams 8000}}"
caddy_1: "http://www.example.it"
caddy_1.reverse_proxy: "{{upstreams 8000}}"
```
Or use `tls internal` for a locally-signed cert if you still need HTTPS.

*— from claude*
