### ISSUE TITLE
Expired certificate doesn't get renewed

### ISSUE THREAD

**Issue by arminus** [lucaslorentz/caddy-docker-proxy#710]
I have a caddy-docker-proxy:2.9-alpine running which acts as proxy for 4 different domains/compose stacks. 3 of the certificates are still valid, the 4th (let's call it paperless.domain.com) has expired 4 days ago and won't renew automatically or during restart of caddy-docker-proxy or the proxied container. Browsing to that domain reports an expired certificate.

I also tried deleting the mounted data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/paperless.domain.com folder and restarted caddy-docker-proxy - getting an SSL error for that domain client side then. I've been using caddy-docker-proxy since years now with basically the same docker configs, never happened before. There's nothing hinting at any issue with the cert renewal in the docker log:

```
{"level":"info","ts":1742376233.5829422,"logger":"docker-proxy","msg":"Running caddy proxy server"}
{"level":"info","ts":1742376233.5843754,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1742376233.584792,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1742376233.5848584,"logger":"docker-proxy","msg":"Running caddy proxy controller"}
{"level":"info","ts":1742376233.5855832,"logger":"docker-proxy","msg":"Start","CaddyfilePath":"","EnvFile":"","LabelPrefix":"caddy","PollingInterval":30,"ProxyServiceTasks":true,"ProcessCaddyfile":true,"ScanStoppedContainers":false,"IngressNetworks":"[caddy-network]","DockerSockets":[""],"DockerCertsPath":[""],"DockerAPIsVersion":[""]}
{"level":"info","ts":1742376233.5865037,"logger":"docker-proxy","msg":"IngressNetworksMap","ingres":"map[6623c30073faf7c8a5a48b1eba1ef70c46497213b92668cf76d70fa990a62b4b:true caddy-network:true]"}
{"level":"info","ts":1742376233.5880756,"logger":"docker-proxy","msg":"Connecting to docker events","DockerSocket":""}
{"level":"info","ts":1742376233.6107135,"logger":"docker-proxy","msg":"Swarm is available","new":false}
{"level":"info","ts":1742376233.6260338,"logger":"docker-proxy","msg":"New Caddyfile","caddyfile":"{\n\tlog {\n\t\toutput file /var/log/access.log\n\t}\n}\nnextcloud.domain.com {\n\t@dav path /.well-known/carddav /.well-known/caldav\n\theader {\n\t\tStrict-Transport-Security \"max-age=15552000; includeSubDomains; preload\"\n\t}\n\tlog\n\tredir @dav /remote.php/dav\n\treverse_proxy 172.19.0.200:80\n}\npaperless.domain.com {\n\tlog\n\treverse_proxy 172.19.0.10:8000\n}\nportainer.domain.com {\n\tlog\n\treverse_proxy 172.19.0.22:9000\n}\n"}
{"level":"info","ts":1742376233.629451,"logger":"docker-proxy","msg":"New Config JSON","json":"{\"logging\":{\"logs\":{\"default\":{\"writer\":{\"filename\":\"/var/log/access.log\",\"output\":\"file\"}}}},\"apps\":{\"http\":{\"servers\":{\"srv0\":{\"listen\":[\":443\"],\"routes\":[{\"match\":[{\"host\":[\"nextcloud.domain.com\"]}],\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"headers\",\"response\":{\"set\":{\"Strict-Transport-Security\":[\"max-age=15552000; includeSubDomains; preload\"]}}}]},{\"handle\":[{\"handler\":\"static_response\",\"headers\":{\"Location\":[\"/remote.php/dav\"]},\"status_code\":302}],\"match\":[{\"path\":[\"/.well-known/carddav\",\"/.well-known/caldav\"]}]},{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.19.0.200:80\"}]}]}]}],\"terminal\":true},{\"match\":[{\"host\":[\"paperless.domain.com\"]}],\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.19.0.10:8000\"}]}]}]}],\"terminal\":true},{\"match\":[{\"host\":[\"portainer.domain.com\"]}],\"handle\":[{\"handler\":\"subroute\",\"routes\":[{\"handle\":[{\"handler\":\"reverse_proxy\",\"upstreams\":[{\"dial\":\"172.19.0.22:9000\"}]}]}]}],\"terminal\":true}],\"logs\":{\"logger_names\":{\"nextcloud.domain.com\":[\"\"],\"paperless.domain.com\":[\"\"],\"portainer.domain.com\":[\"\"]}}}}}}}"}
{"level":"info","ts":1742376233.6295934,"logger":"docker-proxy","msg":"Sending configuration to","server":"localhost"}
{"level":"info","ts":1742376233.660588,"logger":"admin.api","msg":"received request","method":"POST","host":"localhost:2019","uri":"/load","remote_ip":"127.0.0.1","remote_port":"33210","headers":{"Accept-Encoding":["gzip"],"Content-Length":["1194"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}}
{"level":"info","ts":1742376233.6617892,"msg":"redirected default logger","from":"stderr","to":"/var/log/access.log"}
{"level":"info","ts":1742376233.870698,"logger":"docker-proxy","msg":"Successfully configured","server":"localhost"}
```

Here's the respective configs:

```
services:

  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy-network
      - TZ=Europe/Berlin
    networks:
      caddy-network:
        ipv4_address: 172.19.0.100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data

networks:
  caddy-network:
    name: caddy-network
    ipam: 
      driver: default
      config:
        - subnet: 172.19.0.0/24
```

```
services:
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
...
    networks:
      caddy-network:
        ipv4_address: 172.19.0.10
    labels:
      caddy: paperless.domain.com
      caddy.log:
      caddy.reverse_proxy: "{{upstreams 8000}}"
```
