### ISSUE TITLE
Caddy seemingly unable to resolve multiple laravel websites

### ISSUE THREAD

**Issue by GiorgioPortalVBR** [lucaslorentz/caddy-docker-proxy#711]
The setup:

### Caddyfile
Work requires me to provide a particular certificate so that's the only changed option on the Caddyfile

```
*.targetwebsite.com {

        tls /etc/caddy/certs/cert.pem /etc/caddy/certs/server.key

}
```

### Caddy Compose
I've set up a docker-compose.yaml only for holding caddy's service it's set up as so:

```yaml 
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CADDY_INGRESS_NETWORKS=laravel-production,laravel-development
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    networks:
      - laravel-production
      - laravel-development
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
      - $PWD/conf:/etc/caddy/
      - $PWD/certs:/etc/caddy/certs:ro
    restart: unless-stopped
    container_name: caddy
```

Both networks are external.

### Services
I've a production service like so: 

```yaml
 web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    volumes:
      - laravel-storage-production:/var/www/storage:ro
    networks:
      - laravel-production
    #ports:
      #- "${NGINX_PORT:-80}:80" #Comented for reverse proxy
      #- "443:443" #Comented for reverse proxy
    depends_on:
      php-fpm:
        condition: service_healthy  # Wait for php-fpm health check
    labels:
      caddy: utilidades.targetwebsite.com
      caddy.reverse_proxy: "{{upstreams 80}}"

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-storage-production:/var/www/storage  
    env_file:
      - .env
    networks:
      - laravel-production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      caddy.reverse_proxy: "{{upstreams 9000}}"

```

And I'd like to have an identical test service like so:

```yaml
 web:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    volumes:
      - laravel-storage-development:/var/www/storage:ro
    networks:
      - laravel-development
    #ports:
      #- "${NGINX_PORT:-80}:80" #Comented for reverse proxy
      #- "443:443" #Comented for reverse proxy
    depends_on:
      php-fpm:
        condition: service_healthy  # Wait for php-fpm health check
    labels:
      caddy: test-utilidades.targetwebsite.com
      caddy.reverse_proxy: "{{upstreams 80}}"

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production
    restart: unless-stopped
    volumes:
      - laravel-storage-development:/var/www/storage  # Mount the storage volume
    env_file:
      - .env
    networks:
      - laravel-development
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      caddy.reverse_proxy: "{{upstreams 9000}}"

```

Both docker compose services start up without issue but when trying to access 'test-utilidades.targetwebsite.com' the page provides a time out error. Unlike 'utilidades.targetwebsite.com' that works as intended.

Caddy logs provide the following error:

```json
 {"level":"info","ts":1742816195.6119523,"logger":"docker-proxy","msg":"Process Caddyfile","logs":"[ERROR]  Removing invalid block: Caddyfile:2: unrecognized global option: reverse_proxy\n{\n\treverse_proxy 172.31.0.4:9000 172.29.0.6:9000\n}\n\n"}
```
Your help is greatly appreciated as I'm currently stuck on this and all my attempts at moving forward haven't been able to be resolved.
Best regards,
Giorgio.
