### ISSUE TITLE
Help with Labels needed please

### ISSUE THREAD

**Issue by plittlefield** [lucaslorentz/caddy-docker-proxy#712]
I need to get requests for the top level non-www domain to redirect to the www subdomain.

Is this correct?

```
labels:
  caddy: www.mydomain.com:443
  caddy.reverse_proxy: "{{upstreams 80}}"
  caddy.log:
  caddy: mydomain.com
  caddy.redir: https://www.{host}{uri}
```

should end up looking like this in the Caddyfile.autosave ...

```
www.mydomain.com:443 {
 reverse_proxy 172.20.0.4 80
 log
}

mydomain.com {
  redir https://www.{host}{uri}
}
```

Thanks for your help!

Paully

**Comment by plittlefield** [comment]
I have figuured this out now, for anyone who is reading this :-)

I had to add some numbering to the caddy labels in the docker compose file ...

```
    labels:
      caddy_0: www.mydomain.com:443
      caddy_0.reverse_proxy: "{{upstreams 80}}"
      caddy_0.log:
      caddy_1: mydomain.com
      caddy_1.redir: https://www.{host}{uri}
```

and then it made this Caddyfile.autosave ...

```
www.mydomain:443 {
	log
	reverse_proxy 172.18.0.4:80
}
mydomain.com {
	redir https://www.{host}{uri}
}
```

... and it's working :-)
