### ISSUE TITLE
Caddy redirect to another container on the caddy network

### ISSUE THREAD

**Issue by arrubiu** [lucaslorentz/caddy-docker-proxy#715]
I've a problem.
I'm using caddy-docker-proxy:alpine image on an ubuntu server.
In this server there four sites that work.
This is my docker-compose.yml for caddy:

```
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.9-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - caddy
    #labels:
    #  caddy.enable: "true"

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    external: true
```

There is one site (only that one) that caddy redirect always to another container on the "caddy" network.
This the definition of the container that doesn't work:

```
services:
  nginx:
   ## Other stuff
    labels:
      caddy: backend.example.com
      caddy.reverse_proxy: "ildepositoback_nginx:80"
    networks:
      - caddy
      - ildepositoback_internal
    expose:
      - "80"  

networks:
  ildepositoback_internal:
    name: ildepositoback_internal
    driver: bridge
    internal: true
  caddy:
    external: true
```

If I go from the browser to backend.example.com it returns me the document root of another site in the "caddy" network, the "asel_nginx" container. And this appens only for this backend.example.com site, other sites in the same server work well.

I've tried to ping, from the caddy container, the "ildepositoback_nginx" and the "asel_nginx" and they return different IP, so it seems that caddy resolves correctly containers.

So what could be the problem?
