### ISSUE TITLE
trusted proxy client IP

### ISSUE THREAD

**Issue by Thijxx** [lucaslorentz/caddy-docker-proxy#716]
I try to get Caddy to pass a clients real IP to a service behind a reverse proxy so it can log it and fail2ban can pick it up from there.
The past few hours I have been trying to implement the X-header for this but now I read this is no longer used, now I can use trusted_proxies. 

I don't think caddy recognizes the `caddy.reverse_proxy_trusted_proxies` directive.
Is this how it is supposed to be configured? I added the line `caddy.reverse_proxy_trusted_proxies: "172.2.0.0/24"`
Can I dynamically pickup the IP range docker uses?

```
version: '3'

services:
  myservice:
    image: myservice/server:latest
    container_name: myservice
    labels:
      caddy: my.domain.net
      caddy.reverse_proxy: "{{upstreams}}"
      caddy.reverse_proxy_trusted_proxies: "172.2.0.0/24"
    restart: always
    environment:
      - THINGS_ENABLED=true
    volumes:
      - myservice_data:/data
    networks:
      - myservice_network
    depends_on:
      - caddy

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name: reverse-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=myservice_network
    networks:
      - myservice_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  myservice_network:
    external: true
volumes:
  myservice_data: {}
  caddy_data: {}

```
