### ISSUE TITLE
Problem converting not.header with matcher

### ISSUE THREAD

**Issue by aviv926** [lucaslorentz/caddy-docker-proxy#720]
While trying to convert my Caddyfile to caddy-docker-proxy I encountered a problem, I can't convert this section to labels:

```caddyfile
mobile.site.mydomain.com {
 # Define non-mobile User-Agent matcher
 @not_mobile {
  not header User-Agent *Mobile*
  not header User-Agent Dart/3.*
  not header User-Agent Dalvik/2.*
 }
 # Redirect non-mobile users to desktop site
 redir @not_mobile https://site.mydomain.com{uri}
 # Proxy mobile users to the mobile backend
 reverse_proxy 127.0.0.1:2741
```

I tried so many options but none of them worked for example:

```yaml
  caddy_1: "t.mobile.mislp.de" # Main domain for the second configuration block

  caddy_1.matcher_0_name: "not_mobile"
  caddy_1.matcher_0_not_0.header: "User-Agent *Mobile*"
  caddy_1.matcher_0_not_1.header: "User-Agent Dart/3.*"
  caddy_1.matcher_0_not_2.header: "User-Agent Dalvik/2.*"

  caddy_1.redir: "@not_mobile https://t.mislp.de{http.request.uri}"

  caddy_1.reverse_proxy: "{{upstreams http 2283}}"
```

Can anyone show me the correct way to do this?

**Comment by lucaslorentz** [comment]
Closing — @lucaslorentz provided the solution:
```yaml
caddy_1: "mobile.site.mydomain.com"
caddy_1.@not_mobile.not_0: "header User-Agent *Mobile*"
caddy_1.@not_mobile.not_1: "header User-Agent Dart/3.*"
caddy_1.@not_mobile.not_2: "header User-Agent Dalvik/2.*"
caddy_1.redir: "@not_mobile https://site.mydomain.com{uri}"
caddy_1.reverse_proxy: "{{upstreams http 2741}}"
```

*— from claude*
