### ISSUE TITLE
caddy-docker-proxy skips services running on Swarm worker nodes

### ISSUE THREAD

**Issue by wangzexi** [lucaslorentz/caddy-docker-proxy#721]
### Environment

```yaml
services:
  caddy:
    image: ghcr.io/wangzexi/caddy:proxy
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: caddy docker-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/Caddyfile:/Caddyfile
      - ./data/data:/data
      - ./data/config:/config
    environment:
      - CADDY_DOCKER_CADDYFILE_PATH=/Caddyfile
      - CADDY_INGRESS_NETWORKS=caddy_web
    networks: [web]

  whoami:
    image: traefik/whoami
    deploy:
      placement:
        constraints:
          - node.role == manager   # works when on manager
    labels:
      caddy: whoami.bling.fans
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks: [web]

networks:
  web:
    driver: overlay
```

### Custom Caddy image

```Dockerfile
# Build stage
ARG CADDY_VERSION=2.10.0
FROM caddy:${CADDY_VERSION}-builder AS builder

RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/v2 \
    --with github.com/caddy-dns/tencentcloud \
    --with github.com/mholt/caddy-l4

# Runtime stage
FROM caddy:${CADDY_VERSION}-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "docker-proxy"]
```

### Observed behaviour

| Where **whoami** runs | `Caddyfile.autosave`                               | Result            |
| --------------------- | -------------------------------------------------- | ----------------- |
| Manager node          | `whoami.bling.fans { reverse_proxy 10.0.1.25:80 }` | Site works        |
| Worker node           | *(block missing)*                                  | Proxy not created |

The proxy logs still detect the service on a worker:

```txt
{"level":"debug","msg":"Swarm service","service":"caddy_whoami"}
```

Manually adding the block restores functionality:

```caddyfile
whoami.bling.fans {
    reverse_proxy whoami:80
}
```

### Question

Why doesn’t **caddy-docker-proxy** generate a site block for services scheduled on **worker** nodes, even though it detects the service? How can I enable automatic handling of worker‑hosted services?
