### ISSUE TITLE
Proxy wont forward domain.com/<subdir>

### ISSUE THREAD

**Issue by fenpaws** [lucaslorentz/caddy-docker-proxy#87]
Hello there, first of all, great proxy but I can't get it to work for me. I'm not the best in docker and I'm still learning so please forgive me when I ask stupid questions.

So this is my scenario, I want to proxy `domain.com/wp1` to a WordPress container. The Wordpress container has two networks attached. one for the backend and one for the frontend. The backend one is used for communication between WordPress and mySQL Server. The frontend one is used to proxy the request `domain.com/wp1` to the container.

I do this because I don't want that other containers can access my WordPress database.

And this approach worked somewhat. the proxy detects the container and generates a proxy directive
```
domain.com/wp1 {
  proxy / 172.19.0.3
}
```
But it, in the end, it won't work, I cannot access it.

The labels I uses are
```json
labels:
  - caddy.address=domain.com/wp1
  - caddy.proxy.transparent
```
am i doing something wrong here?

**Comment by lucaslorentz** [comment]
What is 192.168.178.37?
Is it the IP of the docker host? Or is it the IP of your container? Or is it the IP of your caddy container?

**Comment by lucaslorentz** [comment]
Are you using docker swarm or docker compose to deploy a yaml file?

**Comment by SoXX-TheFennec** [comment]
the up  `192.X.X.X`  is the docket host, I should have changed that in here.

I used a docker-conpose file to deploy the proxy and the WordPress containers

**Comment by SoXX-TheFennec** [comment]
I edited my initial post to stop confusion about the IP, also I have forgotten to include the `/wp1` after the `domain.com` part.

This is what it actually looks like, sorry my bad.
```
labels:
  - caddy.address=domain.com/wp1
  - caddy.proxy.transparent
```

**Comment by SoXX-TheFennec** [comment]
Heya can you help me with it? I tried nearly anything and it won't work. Do you need more information about my problem?

**Comment by lucaslorentz** [comment]
Well, I'm not sure if wordpress supports running entirely under a path (wp1).

I was able to get it partially working using settings WP_HOME and WP_SITEURL. But still wp-admin doesn't work very well, several times it redirects to a url without wp1.

See below a test I did for docker-compose, without swarm services: 
```
version: '3.7'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 8080:80
    networks:
    - frontend
    command: -email email@example.com -agree=true -log stdout
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    networks:
    - frontend
    - backend
    labels:
    - caddy.address=http://localhost/wp1
    - caddy.proxy.transparent
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://localhost/wp1' );
        define( 'WP_SITEURL', 'http://localhost/wp1' );

  mysql:
    image: mysql:5.7
    networks:
    - backend
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
````
