### ISSUE TITLE
 3 sites are statics, one website per container, how to work?

### ISSUE THREAD

**Issue by find456789** [lucaslorentz/caddy-docker-proxy#99]
hi

 i have 3 sites,  

they are statics, 

  all ` .html` files

i want to use 3 docker container,  one website per container

how to make them work on caddy-docker-proxy

this is my caddyfile 

```
www.exp11.com {
  root /www/exp11
}

www.exp22.com {
  root /www/exp22
}

www.exp33.com {
  root /www/exp33
}


```

![image](https://user-images.githubusercontent.com/6580897/56851174-b1008180-693e-11e9-93ec-f8a2a7802f60.png)

---

 
## i have a idea(add 3 caddys):

 
![image](https://user-images.githubusercontent.com/6580897/56851378-076ebf80-6941-11e9-9f6d-7a563ae8f6e4.png)

---

## how to do this(remove 3 caddys):

![image](https://user-images.githubusercontent.com/6580897/56851384-2705e800-6941-11e9-8e80-ec13af7fdb45.png)

thank you very much

and sorry my english is not well

>translate by google translate

**Comment by lucaslorentz** [comment]
> i have a idea(add 3 caddys)

That's correct

> how to do this(remove 3 caddys)

That's only possible if you put everything in the same container. Because caddy needs access to the files from 3 sites to be able to serve them.

**Comment by lucaslorentz** [comment]
Basic configuration to do what you described with 3 caddys.

Save file below as `sites.yaml`
```yaml
version: '3.7'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:alpine
    ports:
      - 9090:80 # Expose all http sites on port 9090
    command: -email email@example.com -agree=true -log stdout # Configure with your e-mail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  site-1:
    image: abiosoft/caddy
    volumes:
      - /c/Users/Lucas/projects/caddy-docker-proxy/examples/site-test/site1:/srv # Mount site-1 files
    labels:
      caddy.address: http://site1.example.com http://localhost # Hosts that will be exposed in caddy-docker-proxy
      caddy.targetport: "2015"
      caddy.tls: "off"

  site-2:
    image: abiosoft/caddy
    volumes:
      - /c/Users/Lucas/projects/caddy-docker-proxy/examples/site-test/site2:/srv # Mount site-2 files
    labels:
      caddy.address: http://site2.example.com http://127.0.0.1 # Hosts that will be exposed in caddy-docker-proxy
      caddy.targetport: "2015"
      caddy.tls: "off"
```

Deploy stack with `docker stack deploy -c sites.yaml sites`

Open pages in browser:
http://localhost:9090 (site 1)
http://127.0.0.1:9090 (site 2)

I used loopback names to simplify configuration and tests.
